/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.1
 */
export interface CampaignCreateDto {
  contactGroupIds?: string[];
  /** @nullable */
  messageTemplate?: string | null;
  /** @nullable */
  name?: string | null;
  /** @nullable */
  tenantPhoneId?: string | null;
}

export type CampaignStatus = (typeof CampaignStatus)[keyof typeof CampaignStatus];

export const CampaignStatus = {
  PENDING: "PENDING",
  SENDING: "SENDING",
  PAUSED_BY_USER: "PAUSED_BY_USER",
  PAUSED_BY_BILLING: "PAUSED_BY_BILLING",
  CANCELLED_BY_USER: "CANCELLED_BY_USER",
  CANCELLED_BY_TIMEOUT: "CANCELLED_BY_TIMEOUT",
  SENT: "SENT",
} as const;

export interface CampaignDto {
  contactGroupIds: string[];
  id: string;
  messageCount: number;
  messageTemplate: string;
  name: string;
  sentMessageCount: number;
  status: CampaignStatus;
}

export type ContainmentOperator = (typeof ContainmentOperator)[keyof typeof ContainmentOperator];

export const ContainmentOperator = {
  IN: "IN",
  NOT_IN: "NOT_IN",
} as const;

export interface ContainmentFilterUlid {
  operator: ContainmentOperator;
  value: string[];
}

export type ComparisonOperator = (typeof ComparisonOperator)[keyof typeof ComparisonOperator];

export const ComparisonOperator = {
  EQUAL: "EQUAL",
  NOT_EQUAL: "NOT_EQUAL",
  GREATER_THAN: "GREATER_THAN",
  LESS_THAN: "LESS_THAN",
  GREATER_OR_EQUAL: "GREATER_OR_EQUAL",
  LESS_OR_EQUAL: "LESS_OR_EQUAL",
} as const;

export interface ComparisonFilterString {
  operator: ComparisonOperator;
  value?: string;
}

export interface ComparisonFilterI32 {
  operator: ComparisonOperator;
  value?: number;
}

export type TextOperator = (typeof TextOperator)[keyof typeof TextOperator];

export const TextOperator = {
  CONTAINS: "CONTAINS",
  NOT_CONTAINS: "NOT_CONTAINS",
  STARTS_WITH: "STARTS_WITH",
  ENDS_WITH: "ENDS_WITH",
  EQUAL: "EQUAL",
  NOT_EQUAL: "NOT_EQUAL",
} as const;

export interface TextFilter {
  operator: TextOperator;
  /** @nullable */
  value?: string | null;
}

export type NestedOperator = (typeof NestedOperator)[keyof typeof NestedOperator];

export const NestedOperator = {
  AND: "AND",
  OR: "OR",
} as const;

export type ContainmentFilterCampaignStatusValueItem =
  (typeof ContainmentFilterCampaignStatusValueItem)[keyof typeof ContainmentFilterCampaignStatusValueItem];

export const ContainmentFilterCampaignStatusValueItem = {
  PENDING: "PENDING",
  SENDING: "SENDING",
  PAUSED_BY_USER: "PAUSED_BY_USER",
  PAUSED_BY_BILLING: "PAUSED_BY_BILLING",
  CANCELLED_BY_USER: "CANCELLED_BY_USER",
  CANCELLED_BY_TIMEOUT: "CANCELLED_BY_TIMEOUT",
  SENT: "SENT",
} as const;

export interface ContainmentFilterCampaignStatus {
  operator: ContainmentOperator;
  value: ContainmentFilterCampaignStatusValueItem[];
}

export interface CampaignFilterDto {
  contactGroupId?: null | ContainmentFilterUlid;
  createdAt?: null | ComparisonFilterString;
  id?: null | ContainmentFilterUlid;
  messageCount?: null | ComparisonFilterI32;
  messageTemplate?: null | TextFilter;
  name?: null | TextFilter;
  nested?: CampaignFilterDto[];
  operator?: NestedOperator;
  sentMessageCount?: null | ComparisonFilterI32;
  status?: null | ContainmentFilterCampaignStatus;
}

export type SortDirection = (typeof SortDirection)[keyof typeof SortDirection];

export const SortDirection = {
  ASC: "ASC",
  DESC: "DESC",
} as const;

export interface Sort {
  direction?: null | SortDirection;
  order: number;
}

export interface CampaignSortDto {
  createdAt?: null | Sort;
  id?: null | Sort;
  messageCount?: null | Sort;
  name?: null | Sort;
  sentMessageCount?: null | Sort;
  status?: null | Sort;
}

export interface ChangePasswordDto {
  newPassword: string;
  oldPassword: string;
}

export interface ChangeUserNameDto {
  /** @nullable */
  name?: string | null;
}

export type Ulid = string;

export interface CustomFieldValueInputDto {
  id: Ulid;
  value: string;
}

export interface ContactCreateDto {
  /** @nullable */
  birthday?: string | null;
  contactGroupIds?: Ulid[];
  /** @nullable */
  customFields?: CustomFieldValueInputDto[] | null;
  /** @nullable */
  email?: string | null;
  /** @nullable */
  firstName?: string | null;
  /** @nullable */
  lastName?: string | null;
  /** @nullable */
  notes?: string | null;
  /** @nullable */
  phoneNumber?: string | null;
}

export interface CustomFieldValueDto {
  id: Ulid;
  value: string;
}

export interface ContactDto {
  /** @nullable */
  birthday?: string | null;
  contactGroupIds: Ulid[];
  customFields: CustomFieldValueDto[];
  /** @nullable */
  email?: string | null;
  /** @nullable */
  firstName?: string | null;
  id: Ulid;
  /** @nullable */
  lastName?: string | null;
  /** @nullable */
  notes?: string | null;
  phoneNumber: string;
}

export interface ContactFilterDto {
  birthday?: null | ComparisonFilterString;
  contactGroupId?: null | ContainmentFilterUlid;
  email?: null | TextFilter;
  /** @nullable */
  filter?: string | null;
  firstName?: null | TextFilter;
  id?: null | ContainmentFilterUlid;
  lastName?: null | TextFilter;
  nested?: ContactFilterDto[];
  operator?: NestedOperator;
  phoneNumber?: null | TextFilter;
}

export type ContactExportFormatDto = (typeof ContactExportFormatDto)[keyof typeof ContactExportFormatDto];

export const ContactExportFormatDto = {
  CSV: "CSV",
  EXCEL: "EXCEL",
} as const;

export interface ContactSortDto {
  birthday?: null | Sort;
  email?: null | Sort;
  firstName?: null | Sort;
  lastName?: null | Sort;
  phoneNumber?: null | Sort;
}

export interface ContactExportDto {
  filter?: null | ContactFilterDto;
  format: ContactExportFormatDto;
  sort?: null | ContactSortDto;
}

export interface ContactGroupCreateDto {
  /** @nullable */
  name?: string | null;
}

export interface ContactGroupDto {
  contactCount: number;
  id: Ulid;
  name: string;
}

export interface ContactGroupFilterDto {
  contactCount?: null | ComparisonFilterI32;
  name?: null | TextFilter;
  nested?: ContactGroupFilterDto[];
  operator?: NestedOperator;
}

export interface ContactGroupSortDto {
  contactCount?: null | Sort;
  name?: null | Sort;
}

export interface ContactGroupUpdateDto {
  /** @nullable */
  name?: string | null;
}

export type RegularContactImportFieldDto =
  (typeof RegularContactImportFieldDto)[keyof typeof RegularContactImportFieldDto];

export const RegularContactImportFieldDto = {
  PhoneNumber: "PhoneNumber",
  FirstName: "FirstName",
  LastName: "LastName",
  Email: "Email",
  Birthday: "Birthday",
  Notes: "Notes",
} as const;

export type TableImportFieldDto =
  | {
      field: RegularContactImportFieldDto;
      type: "REGULAR";
    }
  | {
      custom_field_id: Ulid;
      type: "CUSTOM_FIELD";
    };

export interface ContactImportColumnDto {
  /** @minimum 0 */
  columnIndex: number;
  field: TableImportFieldDto;
}

export interface ContactImportDto {
  contactGroupIds?: Ulid[];
  fields: ContactImportColumnDto[];
  filename: string;
  skipFirstRow?: boolean;
}

export interface ContactImportResultDto {
  /** @minimum 0 */
  importedCount: number;
}

export interface ContactUpdateDto {
  /** @nullable */
  birthday?: string | null;
  contactGroupIds?: Ulid[];
  /** @nullable */
  customFields?: CustomFieldValueInputDto[] | null;
  /** @nullable */
  email?: string | null;
  /** @nullable */
  firstName?: string | null;
  /** @nullable */
  lastName?: string | null;
  /** @nullable */
  notes?: string | null;
  /** @nullable */
  phoneNumber?: string | null;
}

export type ContainmentFilterMessageStatusValueItem =
  (typeof ContainmentFilterMessageStatusValueItem)[keyof typeof ContainmentFilterMessageStatusValueItem];

export const ContainmentFilterMessageStatusValueItem = {
  PENDING: "PENDING",
  SENT: "SENT",
  FAILED: "FAILED",
} as const;

export interface ContainmentFilterMessageStatus {
  operator: ContainmentOperator;
  value: ContainmentFilterMessageStatusValueItem[];
}

export type CustomFieldType = (typeof CustomFieldType)[keyof typeof CustomFieldType];

export const CustomFieldType = {
  TEXT: "TEXT",
  NUMBER: "NUMBER",
  DATE: "DATE",
} as const;

export interface CreateCustomFieldDto {
  name: string;
  type: CustomFieldType;
}

export interface CustomFieldDto {
  id: Ulid;
  name: string;
  position: string;
  type: CustomFieldType;
}

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];

export const ErrorCode = {
  VALUE_REQUIRED: "VALUE_REQUIRED",
  INVALID_VALUE: "INVALID_VALUE",
  INTERNAL_ERROR: "INTERNAL_ERROR",
  NOT_FOUND: "NOT_FOUND",
  ACCOUNT_ALREADY_EXISTS: "ACCOUNT_ALREADY_EXISTS",
  TOO_MANY_EMAIL_CODE_REQUESTS: "TOO_MANY_EMAIL_CODE_REQUESTS",
  TOO_MANY_PHONE_CODE_REQUESTS: "TOO_MANY_PHONE_CODE_REQUESTS",
  SESSION_EXPIRED: "SESSION_EXPIRED",
  SESSION_CLIENT_CHANGED: "SESSION_CLIENT_CHANGED",
  SESSION_INVALID_USER: "SESSION_INVALID_USER",
  TEN_DLC_BRAND_REQUIRED: "TEN_DLC_BRAND_REQUIRED",
} as const;

export interface ErrorResponse {
  errorCode: ErrorCode;
  /** @nullable */
  errorDescription?: string | null;
}

export interface HealthResponse {
  status: string;
}

export interface IdDto {
  id: Ulid;
}

export type MessageStatus = (typeof MessageStatus)[keyof typeof MessageStatus];

export const MessageStatus = {
  PENDING: "PENDING",
  SENT: "SENT",
  FAILED: "FAILED",
} as const;

export interface MessageDto {
  /** @nullable */
  campaignId?: string | null;
  /** @nullable */
  contactId?: string | null;
  /** @nullable */
  conversationId?: string | null;
  id: string;
  /** @nullable */
  sentAt?: string | null;
  status: MessageStatus;
  tenantPhoneId: string;
  tenantPhoneNumber: string;
  text: string;
}

export type MessageExportFormatDto = (typeof MessageExportFormatDto)[keyof typeof MessageExportFormatDto];

export const MessageExportFormatDto = {
  CSV: "CSV",
  EXCEL: "EXCEL",
} as const;

export interface MessageSortDto {
  campaignId?: null | Sort;
  contactId?: null | Sort;
  conversationId?: null | Sort;
  id?: null | Sort;
  sentAt?: null | Sort;
  status?: null | Sort;
  tenantPhoneId?: null | Sort;
  tenantPhoneNumber?: null | Sort;
  text?: null | Sort;
}

export interface MessageExportDto {
  campaignId: string;
  format: MessageExportFormatDto;
  sort?: null | MessageSortDto;
}

export interface MessageFilterDto {
  campaignId?: null | ContainmentFilterUlid;
  contactId?: null | ContainmentFilterUlid;
  conversationId?: null | ContainmentFilterUlid;
  id?: null | ContainmentFilterUlid;
  nested?: MessageFilterDto[];
  operator?: NestedOperator;
  sentAt?: null | ComparisonFilterString;
  status?: null | ContainmentFilterMessageStatus;
  tenantPhoneId?: null | ContainmentFilterUlid;
  tenantPhoneNumber?: null | TextFilter;
  text?: null | TextFilter;
}

export type PageDirection = (typeof PageDirection)[keyof typeof PageDirection];

export const PageDirection = {
  NEXT: "NEXT",
  PREVIOUS: "PREVIOUS",
} as const;

export interface Value {}

export type PagePosition =
  | {
      /** @nullable */
      cursor?: Value[] | null;
      pageDirection?: PageDirection;
      type: "SEEK";
    }
  | {
      /** @minimum 0 */
      offset: number;
      type: "OFFSET";
    };

export type PageRequestCampaignFilterDtoCampaignSortDtoFilter = {
  contactGroupId?: null | ContainmentFilterUlid;
  createdAt?: null | ComparisonFilterString;
  id?: null | ContainmentFilterUlid;
  messageCount?: null | ComparisonFilterI32;
  messageTemplate?: null | TextFilter;
  name?: null | TextFilter;
  nested?: CampaignFilterDto[];
  operator?: NestedOperator;
  sentMessageCount?: null | ComparisonFilterI32;
  status?: null | ContainmentFilterCampaignStatus;
};

export type PageRequestCampaignFilterDtoCampaignSortDtoSort = {
  createdAt?: null | Sort;
  id?: null | Sort;
  messageCount?: null | Sort;
  name?: null | Sort;
  sentMessageCount?: null | Sort;
  status?: null | Sort;
};

export interface PageWindow {
  /** @minimum 0 */
  pageSize?: number;
  position?: PagePosition;
}

export type PageRequestCampaignFilterDtoCampaignSortDto = PageWindow & {
  filter?: PageRequestCampaignFilterDtoCampaignSortDtoFilter;
  sort?: PageRequestCampaignFilterDtoCampaignSortDtoSort;
};

export type PageRequestContactFilterDtoContactSortDtoFilter = {
  birthday?: null | ComparisonFilterString;
  contactGroupId?: null | ContainmentFilterUlid;
  email?: null | TextFilter;
  /** @nullable */
  filter?: string | null;
  firstName?: null | TextFilter;
  id?: null | ContainmentFilterUlid;
  lastName?: null | TextFilter;
  nested?: ContactFilterDto[];
  operator?: NestedOperator;
  phoneNumber?: null | TextFilter;
};

export type PageRequestContactFilterDtoContactSortDtoSort = {
  birthday?: null | Sort;
  email?: null | Sort;
  firstName?: null | Sort;
  lastName?: null | Sort;
  phoneNumber?: null | Sort;
};

export type PageRequestContactFilterDtoContactSortDto = PageWindow & {
  filter?: PageRequestContactFilterDtoContactSortDtoFilter;
  sort?: PageRequestContactFilterDtoContactSortDtoSort;
};

export type PageRequestContactGroupFilterDtoContactGroupSortDtoFilter = {
  contactCount?: null | ComparisonFilterI32;
  name?: null | TextFilter;
  nested?: ContactGroupFilterDto[];
  operator?: NestedOperator;
};

export type PageRequestContactGroupFilterDtoContactGroupSortDtoSort = {
  contactCount?: null | Sort;
  name?: null | Sort;
};

export type PageRequestContactGroupFilterDtoContactGroupSortDto = PageWindow & {
  filter?: PageRequestContactGroupFilterDtoContactGroupSortDtoFilter;
  sort?: PageRequestContactGroupFilterDtoContactGroupSortDtoSort;
};

export type PageRequestMessageFilterDtoMessageSortDtoFilter = {
  campaignId?: null | ContainmentFilterUlid;
  contactId?: null | ContainmentFilterUlid;
  conversationId?: null | ContainmentFilterUlid;
  id?: null | ContainmentFilterUlid;
  nested?: MessageFilterDto[];
  operator?: NestedOperator;
  sentAt?: null | ComparisonFilterString;
  status?: null | ContainmentFilterMessageStatus;
  tenantPhoneId?: null | ContainmentFilterUlid;
  tenantPhoneNumber?: null | TextFilter;
  text?: null | TextFilter;
};

export type PageRequestMessageFilterDtoMessageSortDtoSort = {
  campaignId?: null | Sort;
  contactId?: null | Sort;
  conversationId?: null | Sort;
  id?: null | Sort;
  sentAt?: null | Sort;
  status?: null | Sort;
  tenantPhoneId?: null | Sort;
  tenantPhoneNumber?: null | Sort;
  text?: null | Sort;
};

export type PageRequestMessageFilterDtoMessageSortDto = PageWindow & {
  filter?: PageRequestMessageFilterDtoMessageSortDtoFilter;
  sort?: PageRequestMessageFilterDtoMessageSortDtoSort;
};

export type PageCampaignDtoItemsItem = {
  contactGroupIds: string[];
  id: string;
  messageCount: number;
  messageTemplate: string;
  name: string;
  sentMessageCount: number;
  status: CampaignStatus;
};

export interface PageCampaignDto {
  items: PageCampaignDtoItemsItem[];
  /** @nullable */
  nextCursor?: Value[] | null;
  /** @nullable */
  prevCursor?: Value[] | null;
  /** @minimum 0 */
  size: number;
}

export type PageContactDtoItemsItem = {
  /** @nullable */
  birthday?: string | null;
  contactGroupIds: Ulid[];
  customFields: CustomFieldValueDto[];
  /** @nullable */
  email?: string | null;
  /** @nullable */
  firstName?: string | null;
  id: Ulid;
  /** @nullable */
  lastName?: string | null;
  /** @nullable */
  notes?: string | null;
  phoneNumber: string;
};

export interface PageContactDto {
  items: PageContactDtoItemsItem[];
  /** @nullable */
  nextCursor?: Value[] | null;
  /** @nullable */
  prevCursor?: Value[] | null;
  /** @minimum 0 */
  size: number;
}

export type PageContactGroupDtoItemsItem = {
  contactCount: number;
  id: Ulid;
  name: string;
};

export interface PageContactGroupDto {
  items: PageContactGroupDtoItemsItem[];
  /** @nullable */
  nextCursor?: Value[] | null;
  /** @nullable */
  prevCursor?: Value[] | null;
  /** @minimum 0 */
  size: number;
}

export type PageMessageDtoItemsItem = {
  /** @nullable */
  campaignId?: string | null;
  /** @nullable */
  contactId?: string | null;
  /** @nullable */
  conversationId?: string | null;
  id: string;
  /** @nullable */
  sentAt?: string | null;
  status: MessageStatus;
  tenantPhoneId: string;
  tenantPhoneNumber: string;
  text: string;
};

export interface PageMessageDto {
  items: PageMessageDtoItemsItem[];
  /** @nullable */
  nextCursor?: Value[] | null;
  /** @nullable */
  prevCursor?: Value[] | null;
  /** @minimum 0 */
  size: number;
}

export type PhoneType = (typeof PhoneType)[keyof typeof PhoneType];

export const PhoneType = {
  TEN_DLC: "TEN_DLC",
  SHORT_CODE: "SHORT_CODE",
  TOLL_FREE: "TOLL_FREE",
} as const;

export interface ProfileDto {
  email: string;
  /** @nullable */
  name?: string | null;
}

export interface SendEmailOtpDto {
  /** @nullable */
  email?: string | null;
}

export interface SendPhoneOtpDto {
  /** @nullable */
  phoneNumber?: string | null;
}

export interface SignInDto {
  email: string;
  password: string;
}

export interface SignUpDto {
  /** @nullable */
  email?: string | null;
  /** @nullable */
  emailCode?: string | null;
  password: string;
  /** @nullable */
  phoneNumber?: string | null;
  /** @nullable */
  phoneNumberCode?: string | null;
}

export interface TenDlcBrandDto {
  createdAt: string;
  id: string;
  name: string;
  updatedAt: string;
}

export interface TenDlcBrandUpdate {
  name: string;
}

export interface TenDlcCampaignCreateDto {
  /** @nullable */
  description?: string | null;
}

export interface TenDlcCampaignDto {
  createdAt: string;
  /** @nullable */
  description?: string | null;
  id: string;
  updatedAt: string;
}

export interface TenantPhoneDto {
  phoneNumber: string;
  phoneType: PhoneType;
}

export interface UpdateCustomFieldNameDto {
  name: string;
}

export interface UpdateCustomFieldPositionDto {
  position: string;
}

export interface UploadUrlDto {
  newFilename: string;
  url: string;
}

export type GetContactUploadUrlParams = {
  filename: string;
};

export type AvailableTenantPhonesParams = {
  number?: string;
  type: PhoneType;
};

export type BuyTenantPhoneParams = {
  number: string;
};
