/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
export interface SignUpDto {
  email?: string;
  emailCode?: string;
  phoneNumber?: string;
  phoneNumberCode?: string;
  password?: string;
}

export interface SendPhoneOtpDto {
  phoneNumber?: string;
}

export interface SendEmailOtpDto {
  email?: string;
}

export interface ChangePasswordDto {
  oldPassword?: string;
  newPassword?: string;
}

export interface ChangeUserNameDto {
  name?: string;
}

export interface ProfileDto {
  name?: string;
  email?: string;
}

export type ErrorResponseDtoErrorCode = (typeof ErrorResponseDtoErrorCode)[keyof typeof ErrorResponseDtoErrorCode];

export const ErrorResponseDtoErrorCode = {
  VALUE_REQUIRED: "VALUE_REQUIRED",
  INVALID_VALUE: "INVALID_VALUE",
  INTERNAL_ERROR: "INTERNAL_ERROR",
  NOT_FOUND: "NOT_FOUND",
  ACCOUNT_ALREADY_EXISTS: "ACCOUNT_ALREADY_EXISTS",
  TOO_MANY_EMAIL_CODE_REQUESTS: "TOO_MANY_EMAIL_CODE_REQUESTS",
  TOO_MANY_PHONE_CODE_REQUESTS: "TOO_MANY_PHONE_CODE_REQUESTS",
  SESSION_EXPIRED: "SESSION_EXPIRED",
  SESSION_CLIENT_CHANGED: "SESSION_CLIENT_CHANGED",
  SESSION_INVALID_USER: "SESSION_INVALID_USER",
  TEN_DLC_BRAND_REQUIRED: "TEN_DLC_BRAND_REQUIRED",
} as const;

export type FieldErrorDtoErrorCode = (typeof FieldErrorDtoErrorCode)[keyof typeof FieldErrorDtoErrorCode];

export const FieldErrorDtoErrorCode = {
  VALUE_REQUIRED: "VALUE_REQUIRED",
  INVALID_VALUE: "INVALID_VALUE",
  INTERNAL_ERROR: "INTERNAL_ERROR",
  NOT_FOUND: "NOT_FOUND",
  ACCOUNT_ALREADY_EXISTS: "ACCOUNT_ALREADY_EXISTS",
  TOO_MANY_EMAIL_CODE_REQUESTS: "TOO_MANY_EMAIL_CODE_REQUESTS",
  TOO_MANY_PHONE_CODE_REQUESTS: "TOO_MANY_PHONE_CODE_REQUESTS",
  SESSION_EXPIRED: "SESSION_EXPIRED",
  SESSION_CLIENT_CHANGED: "SESSION_CLIENT_CHANGED",
  SESSION_INVALID_USER: "SESSION_INVALID_USER",
  TEN_DLC_BRAND_REQUIRED: "TEN_DLC_BRAND_REQUIRED",
} as const;

export interface FieldErrorDto {
  field: string;
  errorCode: FieldErrorDtoErrorCode;
  errorDescription: string;
}

export interface ErrorResponseDto {
  errorCode?: ErrorResponseDtoErrorCode;
  errorDescription?: string;
  fields?: FieldErrorDto[];
}

export interface SignInDto {
  email?: string;
  password?: string;
}

export interface UpdateCustomFieldPositionDto {
  position: number;
}

export interface UpdateCustomFieldNameDto {
  name: string;
}

export interface ContactUpdateDto {
  contactGroupIds?: string[];
  firstName?: string;
  lastName?: string;
  email?: string;
  birthday?: string;
}

export interface ContactGroupUpdateDto {
  name?: string;
}

export type CreateCustomFieldDtoType = (typeof CreateCustomFieldDtoType)[keyof typeof CreateCustomFieldDtoType];

export const CreateCustomFieldDtoType = {
  TEXT: "TEXT",
  NUMBER: "NUMBER",
  DATE: "DATE",
} as const;

export interface CreateCustomFieldDto {
  name: string;
  type: CreateCustomFieldDtoType;
}

export interface IdDto {
  id: string;
}

export interface ContactCreateDto {
  contactGroupIds?: string[];
  phoneNumber: string;
  firstName?: string;
  lastName?: string;
  email?: string;
  birthday?: string;
}

export type ComparisonFilterLocalDateOperator =
  (typeof ComparisonFilterLocalDateOperator)[keyof typeof ComparisonFilterLocalDateOperator];

export const ComparisonFilterLocalDateOperator = {
  EQUAL: "EQUAL",
  NOT_EQUAL: "NOT_EQUAL",
  GREATER_THAN: "GREATER_THAN",
  LESS_THAN: "LESS_THAN",
  GREATER_OR_EQUAL: "GREATER_OR_EQUAL",
  LESS_OR_EQUAL: "LESS_OR_EQUAL",
} as const;

export interface ComparisonFilterLocalDate {
  operator?: ComparisonFilterLocalDateOperator;
  value?: string;
}

export type ContactFilterDtoOperator = (typeof ContactFilterDtoOperator)[keyof typeof ContactFilterDtoOperator];

export const ContactFilterDtoOperator = {
  AND: "AND",
  OR: "OR",
} as const;

export type ContainmentFilterULIDOperator =
  (typeof ContainmentFilterULIDOperator)[keyof typeof ContainmentFilterULIDOperator];

export const ContainmentFilterULIDOperator = {
  IN: "IN",
  NOT_IN: "NOT_IN",
} as const;

export interface ContainmentFilterULID {
  operator?: ContainmentFilterULIDOperator;
  value?: string[];
}

export type TextFilterOperator = (typeof TextFilterOperator)[keyof typeof TextFilterOperator];

export const TextFilterOperator = {
  CONTAINS: "CONTAINS",
  NOT_CONTAINS: "NOT_CONTAINS",
  STARTS_WITH: "STARTS_WITH",
  ENDS_WITH: "ENDS_WITH",
  EQUAL: "EQUAL",
  NOT_EQUAL: "NOT_EQUAL",
} as const;

export interface TextFilter {
  operator?: TextFilterOperator;
  value?: string;
}

export interface ContactFilterDto {
  operator?: ContactFilterDtoOperator;
  nested?: unknown[];
  id?: ContainmentFilterULID;
  contactGroupId?: ContainmentFilterULID;
  phoneNumber?: TextFilter;
  firstName?: TextFilter;
  lastName?: TextFilter;
  email?: TextFilter;
  birthday?: ComparisonFilterLocalDate;
  filter?: string;
}

export type SortDirection = (typeof SortDirection)[keyof typeof SortDirection];

export const SortDirection = {
  ASC: "ASC",
  DESC: "DESC",
} as const;

export interface Sort {
  order?: number;
  direction?: SortDirection;
}

export interface ContactSortDto {
  phoneNumber?: Sort;
  firstName?: Sort;
  lastName?: Sort;
  email?: Sort;
  birthday?: Sort;
}

export type PageRequestContactFilterDtoContactSortDtoPageDirection =
  (typeof PageRequestContactFilterDtoContactSortDtoPageDirection)[keyof typeof PageRequestContactFilterDtoContactSortDtoPageDirection];

export const PageRequestContactFilterDtoContactSortDtoPageDirection = {
  NEXT: "NEXT",
  PREVIOUS: "PREVIOUS",
} as const;

export interface PageRequestContactFilterDtoContactSortDto {
  filter?: ContactFilterDto;
  sort?: ContactSortDto;
  pageSize?: number;
  cursor?: unknown[];
  pageDirection?: PageRequestContactFilterDtoContactSortDtoPageDirection;
}

export interface ContactDto {
  id: string;
  contactGroupIds?: string[];
  phoneNumber: string;
  firstName?: string;
  lastName?: string;
  email?: string;
  birthday?: string;
}

export interface PageContactDto {
  items?: ContactDto[];
  size?: number;
  nextCursor?: unknown[];
  prevCursor?: unknown[];
}

export interface ContactGroupCreateDto {
  name?: string;
}

export type ComparisonFilterIntegerOperator =
  (typeof ComparisonFilterIntegerOperator)[keyof typeof ComparisonFilterIntegerOperator];

export const ComparisonFilterIntegerOperator = {
  EQUAL: "EQUAL",
  NOT_EQUAL: "NOT_EQUAL",
  GREATER_THAN: "GREATER_THAN",
  LESS_THAN: "LESS_THAN",
  GREATER_OR_EQUAL: "GREATER_OR_EQUAL",
  LESS_OR_EQUAL: "LESS_OR_EQUAL",
} as const;

export interface ComparisonFilterInteger {
  operator?: ComparisonFilterIntegerOperator;
  value?: number;
}

export type ContactGroupFilterDtoOperator =
  (typeof ContactGroupFilterDtoOperator)[keyof typeof ContactGroupFilterDtoOperator];

export const ContactGroupFilterDtoOperator = {
  AND: "AND",
  OR: "OR",
} as const;

export interface ContactGroupFilterDto {
  operator?: ContactGroupFilterDtoOperator;
  nested?: unknown[];
  name?: TextFilter;
  contactCount?: ComparisonFilterInteger;
}

export interface ContactGroupSortDto {
  name?: Sort;
  contactCount?: Sort;
}

export type PageRequestContactGroupFilterDtoContactGroupSortDtoPageDirection =
  (typeof PageRequestContactGroupFilterDtoContactGroupSortDtoPageDirection)[keyof typeof PageRequestContactGroupFilterDtoContactGroupSortDtoPageDirection];

export const PageRequestContactGroupFilterDtoContactGroupSortDtoPageDirection = {
  NEXT: "NEXT",
  PREVIOUS: "PREVIOUS",
} as const;

export interface PageRequestContactGroupFilterDtoContactGroupSortDto {
  filter?: ContactGroupFilterDto;
  sort?: ContactGroupSortDto;
  pageSize?: number;
  cursor?: unknown[];
  pageDirection?: PageRequestContactGroupFilterDtoContactGroupSortDtoPageDirection;
}

export interface ContactGroupDto {
  id?: string;
  name?: string;
  contactCount?: number;
}

export interface PageContactGroupDto {
  items?: ContactGroupDto[];
  size?: number;
  nextCursor?: unknown[];
  prevCursor?: unknown[];
}

export type CustomFieldDtoType = (typeof CustomFieldDtoType)[keyof typeof CustomFieldDtoType];

export const CustomFieldDtoType = {
  TEXT: "TEXT",
  NUMBER: "NUMBER",
  DATE: "DATE",
} as const;

export interface CustomFieldDto {
  id: string;
  name: string;
  type: CustomFieldDtoType;
  position: number;
}

export interface UploadUrlDto {
  url?: string;
  newFilename?: string;
}

export interface TenDlcBrandUpdateDto {
  name?: string;
}

export interface TenDlcBrandDto {
  id?: string;
  createdAt?: string;
  updatedAt?: string;
  name?: string;
}

export type TenantPhoneDtoPhoneType = (typeof TenantPhoneDtoPhoneType)[keyof typeof TenantPhoneDtoPhoneType];

export const TenantPhoneDtoPhoneType = {
  TEN_DLC: "TEN_DLC",
  SHORT_CODE: "SHORT_CODE",
  TOLL_FREE: "TOLL_FREE",
} as const;

export interface TenantPhoneDto {
  phoneNumber?: string;
  phoneType?: TenantPhoneDtoPhoneType;
}

export interface TenDlcCampaignCreateDto {
  description?: string;
}

export interface TenDlcCampaignDto {
  id?: string;
  createdAt?: string;
  updatedAt?: string;
  description?: string;
}

export interface CampaignCreateDto {
  name?: string;
  messageTemplate?: string;
  contactGroupIds?: string[];
  tenantPhoneId?: string;
}

export type CampaignFilterDtoOperator = (typeof CampaignFilterDtoOperator)[keyof typeof CampaignFilterDtoOperator];

export const CampaignFilterDtoOperator = {
  AND: "AND",
  OR: "OR",
} as const;

export type ContainmentFilterCampaignStatusOperator =
  (typeof ContainmentFilterCampaignStatusOperator)[keyof typeof ContainmentFilterCampaignStatusOperator];

export const ContainmentFilterCampaignStatusOperator = {
  IN: "IN",
  NOT_IN: "NOT_IN",
} as const;

export type ContainmentFilterCampaignStatusValueItem =
  (typeof ContainmentFilterCampaignStatusValueItem)[keyof typeof ContainmentFilterCampaignStatusValueItem];

export const ContainmentFilterCampaignStatusValueItem = {
  PENDING: "PENDING",
  SENDING: "SENDING",
  PAUSED_BY_USER: "PAUSED_BY_USER",
  PAUSED_BY_BILLING: "PAUSED_BY_BILLING",
  CANCELLED_BY_USER: "CANCELLED_BY_USER",
  CANCELLED_BY_TIMEOUT: "CANCELLED_BY_TIMEOUT",
  SENT: "SENT",
} as const;

export interface ContainmentFilterCampaignStatus {
  operator?: ContainmentFilterCampaignStatusOperator;
  value?: ContainmentFilterCampaignStatusValueItem[];
}

export type ComparisonFilterInstantOperator =
  (typeof ComparisonFilterInstantOperator)[keyof typeof ComparisonFilterInstantOperator];

export const ComparisonFilterInstantOperator = {
  EQUAL: "EQUAL",
  NOT_EQUAL: "NOT_EQUAL",
  GREATER_THAN: "GREATER_THAN",
  LESS_THAN: "LESS_THAN",
  GREATER_OR_EQUAL: "GREATER_OR_EQUAL",
  LESS_OR_EQUAL: "LESS_OR_EQUAL",
} as const;

export interface ComparisonFilterInstant {
  operator?: ComparisonFilterInstantOperator;
  value?: string;
}

export interface CampaignFilterDto {
  operator?: CampaignFilterDtoOperator;
  nested?: unknown[];
  id?: ContainmentFilterULID;
  contactGroupId?: ContainmentFilterULID;
  status?: ContainmentFilterCampaignStatus;
  name?: TextFilter;
  messageTemplate?: TextFilter;
  messageCount?: ComparisonFilterInteger;
  sentMessageCount?: ComparisonFilterInteger;
  createdAt?: ComparisonFilterInstant;
}

export interface CampaignSortDto {
  id?: Sort;
  name?: Sort;
  messageCount?: Sort;
  sentMessageCount?: Sort;
  createdAt?: Sort;
  status?: Sort;
}

export type PageRequestCampaignFilterDtoCampaignSortDtoPageDirection =
  (typeof PageRequestCampaignFilterDtoCampaignSortDtoPageDirection)[keyof typeof PageRequestCampaignFilterDtoCampaignSortDtoPageDirection];

export const PageRequestCampaignFilterDtoCampaignSortDtoPageDirection = {
  NEXT: "NEXT",
  PREVIOUS: "PREVIOUS",
} as const;

export interface PageRequestCampaignFilterDtoCampaignSortDto {
  filter?: CampaignFilterDto;
  sort?: CampaignSortDto;
  pageSize?: number;
  cursor?: unknown[];
  pageDirection?: PageRequestCampaignFilterDtoCampaignSortDtoPageDirection;
}

export type CampaignDtoStatus = (typeof CampaignDtoStatus)[keyof typeof CampaignDtoStatus];

export const CampaignDtoStatus = {
  PENDING: "PENDING",
  SENDING: "SENDING",
  PAUSED_BY_USER: "PAUSED_BY_USER",
  PAUSED_BY_BILLING: "PAUSED_BY_BILLING",
  CANCELLED_BY_USER: "CANCELLED_BY_USER",
  CANCELLED_BY_TIMEOUT: "CANCELLED_BY_TIMEOUT",
  SENT: "SENT",
} as const;

export interface CampaignDto {
  id?: string;
  name?: string;
  messageTemplate?: string;
  contactGroupIds?: string[];
  status?: CampaignDtoStatus;
  messageCount?: number;
  sentMessageCount?: number;
}

export interface PageCampaignDto {
  items?: CampaignDto[];
  size?: number;
  nextCursor?: unknown[];
  prevCursor?: unknown[];
}

export type GetUploadUrlParams = {
  filename: string;
};

export type BuyTenantPhoneParams = {
  number: string;
};

export type GetAvailableTenantPhonesParams = {
  number?: string;
  type: GetAvailableTenantPhonesType;
};

export type GetAvailableTenantPhonesType =
  (typeof GetAvailableTenantPhonesType)[keyof typeof GetAvailableTenantPhonesType];

export const GetAvailableTenantPhonesType = {
  TEN_DLC: "TEN_DLC",
  SHORT_CODE: "SHORT_CODE",
  TOLL_FREE: "TOLL_FREE",
} as const;
