/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type {
  CreateCustomFieldDto,
  CustomFieldDto,
  ErrorResponseDto,
  IdDto,
  UpdateCustomFieldNameDto,
  UpdateCustomFieldPositionDto,
} from "../index.schemas";

export type UpdateCustomFieldPositionResponse200 = {
  data: void;
  status: 200;
};

export type UpdateCustomFieldPositionResponse400 = {
  data: ErrorResponseDto;
  status: 400;
};

export type UpdateCustomFieldPositionResponse401 = {
  data: ErrorResponseDto;
  status: 401;
};

export type UpdateCustomFieldPositionResponse404 = {
  data: ErrorResponseDto;
  status: 404;
};

export type UpdateCustomFieldPositionResponse500 = {
  data: ErrorResponseDto;
  status: 500;
};

export type UpdateCustomFieldPositionResponseSuccess = UpdateCustomFieldPositionResponse200 & {
  headers: Headers;
};
export type UpdateCustomFieldPositionResponseError = (
  | UpdateCustomFieldPositionResponse400
  | UpdateCustomFieldPositionResponse401
  | UpdateCustomFieldPositionResponse404
  | UpdateCustomFieldPositionResponse500
) & {
  headers: Headers;
};

export type UpdateCustomFieldPositionResponse =
  | UpdateCustomFieldPositionResponseSuccess
  | UpdateCustomFieldPositionResponseError;

export const getUpdateCustomFieldPositionUrl = (id: string) => {
  return `/contact/custom-fields/${id}/position`;
};

export const updateCustomFieldPosition = async (
  id: string,
  updateCustomFieldPositionDto: UpdateCustomFieldPositionDto,
  options?: RequestInit,
): Promise<UpdateCustomFieldPositionResponse> => {
  const res = await fetch(getUpdateCustomFieldPositionUrl(id), {
    ...options,
    method: "PUT",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(updateCustomFieldPositionDto),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: UpdateCustomFieldPositionResponse["data"] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as UpdateCustomFieldPositionResponse;
};

export type UpdateCustomFieldNameResponse200 = {
  data: void;
  status: 200;
};

export type UpdateCustomFieldNameResponse400 = {
  data: ErrorResponseDto;
  status: 400;
};

export type UpdateCustomFieldNameResponse401 = {
  data: ErrorResponseDto;
  status: 401;
};

export type UpdateCustomFieldNameResponse404 = {
  data: ErrorResponseDto;
  status: 404;
};

export type UpdateCustomFieldNameResponse500 = {
  data: ErrorResponseDto;
  status: 500;
};

export type UpdateCustomFieldNameResponseSuccess = UpdateCustomFieldNameResponse200 & {
  headers: Headers;
};
export type UpdateCustomFieldNameResponseError = (
  | UpdateCustomFieldNameResponse400
  | UpdateCustomFieldNameResponse401
  | UpdateCustomFieldNameResponse404
  | UpdateCustomFieldNameResponse500
) & {
  headers: Headers;
};

export type UpdateCustomFieldNameResponse = UpdateCustomFieldNameResponseSuccess | UpdateCustomFieldNameResponseError;

export const getUpdateCustomFieldNameUrl = (id: string) => {
  return `/contact/custom-fields/${id}/name`;
};

export const updateCustomFieldName = async (
  id: string,
  updateCustomFieldNameDto: UpdateCustomFieldNameDto,
  options?: RequestInit,
): Promise<UpdateCustomFieldNameResponse> => {
  const res = await fetch(getUpdateCustomFieldNameUrl(id), {
    ...options,
    method: "PUT",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(updateCustomFieldNameDto),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: UpdateCustomFieldNameResponse["data"] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as UpdateCustomFieldNameResponse;
};

export type GetCustomFieldsResponse200 = {
  data: CustomFieldDto[];
  status: 200;
};

export type GetCustomFieldsResponse400 = {
  data: ErrorResponseDto;
  status: 400;
};

export type GetCustomFieldsResponse401 = {
  data: ErrorResponseDto;
  status: 401;
};

export type GetCustomFieldsResponse404 = {
  data: ErrorResponseDto;
  status: 404;
};

export type GetCustomFieldsResponse500 = {
  data: ErrorResponseDto;
  status: 500;
};

export type GetCustomFieldsResponseSuccess = GetCustomFieldsResponse200 & {
  headers: Headers;
};
export type GetCustomFieldsResponseError = (
  | GetCustomFieldsResponse400
  | GetCustomFieldsResponse401
  | GetCustomFieldsResponse404
  | GetCustomFieldsResponse500
) & {
  headers: Headers;
};

export type GetCustomFieldsResponse = GetCustomFieldsResponseSuccess | GetCustomFieldsResponseError;

export const getGetCustomFieldsUrl = () => {
  return `/contact/custom-fields`;
};

export const getCustomFields = async (options?: RequestInit): Promise<GetCustomFieldsResponse> => {
  const res = await fetch(getGetCustomFieldsUrl(), {
    ...options,
    method: "GET",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: GetCustomFieldsResponse["data"] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as GetCustomFieldsResponse;
};

export type CreateCustomFieldResponse200 = {
  data: IdDto;
  status: 200;
};

export type CreateCustomFieldResponse400 = {
  data: ErrorResponseDto;
  status: 400;
};

export type CreateCustomFieldResponse401 = {
  data: ErrorResponseDto;
  status: 401;
};

export type CreateCustomFieldResponse404 = {
  data: ErrorResponseDto;
  status: 404;
};

export type CreateCustomFieldResponse500 = {
  data: ErrorResponseDto;
  status: 500;
};

export type CreateCustomFieldResponseSuccess = CreateCustomFieldResponse200 & {
  headers: Headers;
};
export type CreateCustomFieldResponseError = (
  | CreateCustomFieldResponse400
  | CreateCustomFieldResponse401
  | CreateCustomFieldResponse404
  | CreateCustomFieldResponse500
) & {
  headers: Headers;
};

export type CreateCustomFieldResponse = CreateCustomFieldResponseSuccess | CreateCustomFieldResponseError;

export const getCreateCustomFieldUrl = () => {
  return `/contact/custom-fields`;
};

export const createCustomField = async (
  createCustomFieldDto: CreateCustomFieldDto,
  options?: RequestInit,
): Promise<CreateCustomFieldResponse> => {
  const res = await fetch(getCreateCustomFieldUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(createCustomFieldDto),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: CreateCustomFieldResponse["data"] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as CreateCustomFieldResponse;
};

export type GetCustomFieldByIdResponse200 = {
  data: CustomFieldDto;
  status: 200;
};

export type GetCustomFieldByIdResponse400 = {
  data: ErrorResponseDto;
  status: 400;
};

export type GetCustomFieldByIdResponse401 = {
  data: ErrorResponseDto;
  status: 401;
};

export type GetCustomFieldByIdResponse404 = {
  data: ErrorResponseDto;
  status: 404;
};

export type GetCustomFieldByIdResponse500 = {
  data: ErrorResponseDto;
  status: 500;
};

export type GetCustomFieldByIdResponseSuccess = GetCustomFieldByIdResponse200 & {
  headers: Headers;
};
export type GetCustomFieldByIdResponseError = (
  | GetCustomFieldByIdResponse400
  | GetCustomFieldByIdResponse401
  | GetCustomFieldByIdResponse404
  | GetCustomFieldByIdResponse500
) & {
  headers: Headers;
};

export type GetCustomFieldByIdResponse = GetCustomFieldByIdResponseSuccess | GetCustomFieldByIdResponseError;

export const getGetCustomFieldByIdUrl = (id: string) => {
  return `/contact/custom-fields/${id}`;
};

export const getCustomFieldById = async (id: string, options?: RequestInit): Promise<GetCustomFieldByIdResponse> => {
  const res = await fetch(getGetCustomFieldByIdUrl(id), {
    ...options,
    method: "GET",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: GetCustomFieldByIdResponse["data"] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as GetCustomFieldByIdResponse;
};

export type DeleteCustomFieldResponse200 = {
  data: void;
  status: 200;
};

export type DeleteCustomFieldResponse400 = {
  data: ErrorResponseDto;
  status: 400;
};

export type DeleteCustomFieldResponse401 = {
  data: ErrorResponseDto;
  status: 401;
};

export type DeleteCustomFieldResponse404 = {
  data: ErrorResponseDto;
  status: 404;
};

export type DeleteCustomFieldResponse500 = {
  data: ErrorResponseDto;
  status: 500;
};

export type DeleteCustomFieldResponseSuccess = DeleteCustomFieldResponse200 & {
  headers: Headers;
};
export type DeleteCustomFieldResponseError = (
  | DeleteCustomFieldResponse400
  | DeleteCustomFieldResponse401
  | DeleteCustomFieldResponse404
  | DeleteCustomFieldResponse500
) & {
  headers: Headers;
};

export type DeleteCustomFieldResponse = DeleteCustomFieldResponseSuccess | DeleteCustomFieldResponseError;

export const getDeleteCustomFieldUrl = (id: string) => {
  return `/contact/custom-fields/${id}`;
};

export const deleteCustomField = async (id: string, options?: RequestInit): Promise<DeleteCustomFieldResponse> => {
  const res = await fetch(getDeleteCustomFieldUrl(id), {
    ...options,
    method: "DELETE",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: DeleteCustomFieldResponse["data"] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as DeleteCustomFieldResponse;
};
