/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * utoipa-axum
 * Utoipa's axum bindings for seamless integration for the two
 * OpenAPI spec version: 0.2.0
 */
import type {
  CreateCustomFieldDto,
  CustomFieldDto,
  ErrorResponse,
  IdDto,
  Ulid,
  UpdateCustomFieldNameDto,
  UpdateCustomFieldPositionDto,
} from "../index.schemas";

export type ListCustomFieldsResponse200 = {
  data: CustomFieldDto[];
  status: 200;
};

export type ListCustomFieldsResponse500 = {
  data: ErrorResponse;
  status: 500;
};

export type ListCustomFieldsResponseSuccess = ListCustomFieldsResponse200 & {
  headers: Headers;
};
export type ListCustomFieldsResponseError = ListCustomFieldsResponse500 & {
  headers: Headers;
};

export type ListCustomFieldsResponse = ListCustomFieldsResponseSuccess | ListCustomFieldsResponseError;

export const getListCustomFieldsUrl = () => {
  return `/contact/custom-fields`;
};

export const listCustomFields = async (options?: RequestInit): Promise<ListCustomFieldsResponse> => {
  const res = await fetch(getListCustomFieldsUrl(), {
    ...options,
    method: "GET",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: ListCustomFieldsResponse["data"] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as ListCustomFieldsResponse;
};

export type CreateCustomFieldResponse200 = {
  data: IdDto;
  status: 200;
};

export type CreateCustomFieldResponse400 = {
  data: ErrorResponse;
  status: 400;
};

export type CreateCustomFieldResponse500 = {
  data: ErrorResponse;
  status: 500;
};

export type CreateCustomFieldResponseSuccess = CreateCustomFieldResponse200 & {
  headers: Headers;
};
export type CreateCustomFieldResponseError = (CreateCustomFieldResponse400 | CreateCustomFieldResponse500) & {
  headers: Headers;
};

export type CreateCustomFieldResponse = CreateCustomFieldResponseSuccess | CreateCustomFieldResponseError;

export const getCreateCustomFieldUrl = () => {
  return `/contact/custom-fields`;
};

export const createCustomField = async (
  createCustomFieldDto: CreateCustomFieldDto,
  options?: RequestInit,
): Promise<CreateCustomFieldResponse> => {
  const res = await fetch(getCreateCustomFieldUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(createCustomFieldDto),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: CreateCustomFieldResponse["data"] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as CreateCustomFieldResponse;
};

export type GetCustomFieldResponse200 = {
  data: CustomFieldDto;
  status: 200;
};

export type GetCustomFieldResponse404 = {
  data: ErrorResponse;
  status: 404;
};

export type GetCustomFieldResponse500 = {
  data: ErrorResponse;
  status: 500;
};

export type GetCustomFieldResponseSuccess = GetCustomFieldResponse200 & {
  headers: Headers;
};
export type GetCustomFieldResponseError = (GetCustomFieldResponse404 | GetCustomFieldResponse500) & {
  headers: Headers;
};

export type GetCustomFieldResponse = GetCustomFieldResponseSuccess | GetCustomFieldResponseError;

export const getGetCustomFieldUrl = (id: Ulid) => {
  return `/contact/custom-fields/${id}`;
};

export const getCustomField = async (id: Ulid, options?: RequestInit): Promise<GetCustomFieldResponse> => {
  const res = await fetch(getGetCustomFieldUrl(id), {
    ...options,
    method: "GET",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: GetCustomFieldResponse["data"] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as GetCustomFieldResponse;
};

export type DeleteCustomFieldResponse200 = {
  data: void;
  status: 200;
};

export type DeleteCustomFieldResponse404 = {
  data: ErrorResponse;
  status: 404;
};

export type DeleteCustomFieldResponse500 = {
  data: ErrorResponse;
  status: 500;
};

export type DeleteCustomFieldResponseSuccess = DeleteCustomFieldResponse200 & {
  headers: Headers;
};
export type DeleteCustomFieldResponseError = (DeleteCustomFieldResponse404 | DeleteCustomFieldResponse500) & {
  headers: Headers;
};

export type DeleteCustomFieldResponse = DeleteCustomFieldResponseSuccess | DeleteCustomFieldResponseError;

export const getDeleteCustomFieldUrl = (id: Ulid) => {
  return `/contact/custom-fields/${id}`;
};

export const deleteCustomField = async (id: Ulid, options?: RequestInit): Promise<DeleteCustomFieldResponse> => {
  const res = await fetch(getDeleteCustomFieldUrl(id), {
    ...options,
    method: "DELETE",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: DeleteCustomFieldResponse["data"] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as DeleteCustomFieldResponse;
};

export type UpdateCustomFieldNameResponse200 = {
  data: void;
  status: 200;
};

export type UpdateCustomFieldNameResponse400 = {
  data: ErrorResponse;
  status: 400;
};

export type UpdateCustomFieldNameResponse404 = {
  data: ErrorResponse;
  status: 404;
};

export type UpdateCustomFieldNameResponse500 = {
  data: ErrorResponse;
  status: 500;
};

export type UpdateCustomFieldNameResponseSuccess = UpdateCustomFieldNameResponse200 & {
  headers: Headers;
};
export type UpdateCustomFieldNameResponseError = (
  | UpdateCustomFieldNameResponse400
  | UpdateCustomFieldNameResponse404
  | UpdateCustomFieldNameResponse500
) & {
  headers: Headers;
};

export type UpdateCustomFieldNameResponse = UpdateCustomFieldNameResponseSuccess | UpdateCustomFieldNameResponseError;

export const getUpdateCustomFieldNameUrl = (id: Ulid) => {
  return `/contact/custom-fields/${id}/name`;
};

export const updateCustomFieldName = async (
  id: Ulid,
  updateCustomFieldNameDto: UpdateCustomFieldNameDto,
  options?: RequestInit,
): Promise<UpdateCustomFieldNameResponse> => {
  const res = await fetch(getUpdateCustomFieldNameUrl(id), {
    ...options,
    method: "PUT",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(updateCustomFieldNameDto),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: UpdateCustomFieldNameResponse["data"] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as UpdateCustomFieldNameResponse;
};

export type UpdateCustomFieldPositionResponse200 = {
  data: void;
  status: 200;
};

export type UpdateCustomFieldPositionResponse400 = {
  data: ErrorResponse;
  status: 400;
};

export type UpdateCustomFieldPositionResponse404 = {
  data: ErrorResponse;
  status: 404;
};

export type UpdateCustomFieldPositionResponse500 = {
  data: ErrorResponse;
  status: 500;
};

export type UpdateCustomFieldPositionResponseSuccess = UpdateCustomFieldPositionResponse200 & {
  headers: Headers;
};
export type UpdateCustomFieldPositionResponseError = (
  | UpdateCustomFieldPositionResponse400
  | UpdateCustomFieldPositionResponse404
  | UpdateCustomFieldPositionResponse500
) & {
  headers: Headers;
};

export type UpdateCustomFieldPositionResponse =
  | UpdateCustomFieldPositionResponseSuccess
  | UpdateCustomFieldPositionResponseError;

export const getUpdateCustomFieldPositionUrl = (id: Ulid) => {
  return `/contact/custom-fields/${id}/position`;
};

export const updateCustomFieldPosition = async (
  id: Ulid,
  updateCustomFieldPositionDto: UpdateCustomFieldPositionDto,
  options?: RequestInit,
): Promise<UpdateCustomFieldPositionResponse> => {
  const res = await fetch(getUpdateCustomFieldPositionUrl(id), {
    ...options,
    method: "PUT",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(updateCustomFieldPositionDto),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: UpdateCustomFieldPositionResponse["data"] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as UpdateCustomFieldPositionResponse;
};
