/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type {
  CreateCustomFieldDto,
  CustomFieldDto,
  ErrorResponseDto,
  IdDto,
  UpdateCustomFieldNameDto,
  UpdateCustomFieldPositionDto
} from '../index.schemas';


export type updateCustomFieldPositionResponse200 = {
  data: void
  status: 200
}

export type updateCustomFieldPositionResponse400 = {
  data: ErrorResponseDto
  status: 400
}

export type updateCustomFieldPositionResponse401 = {
  data: ErrorResponseDto
  status: 401
}

export type updateCustomFieldPositionResponse404 = {
  data: ErrorResponseDto
  status: 404
}

export type updateCustomFieldPositionResponse500 = {
  data: ErrorResponseDto
  status: 500
}

export type updateCustomFieldPositionResponseSuccess = (updateCustomFieldPositionResponse200) & {
  headers: Headers;
};
export type updateCustomFieldPositionResponseError = (updateCustomFieldPositionResponse400 | updateCustomFieldPositionResponse401 | updateCustomFieldPositionResponse404 | updateCustomFieldPositionResponse500) & {
  headers: Headers;
};

export type updateCustomFieldPositionResponse = (updateCustomFieldPositionResponseSuccess | updateCustomFieldPositionResponseError)

export const getUpdateCustomFieldPositionUrl = (id: string,) => {


  

  return `/contact/custom-fields/${id}/position`
}

export const updateCustomFieldPosition = async (id: string,
    updateCustomFieldPositionDto: UpdateCustomFieldPositionDto, options?: RequestInit): Promise<updateCustomFieldPositionResponse> => {
  
  const res = await fetch(getUpdateCustomFieldPositionUrl(id),
  {      
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      updateCustomFieldPositionDto,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: updateCustomFieldPositionResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as updateCustomFieldPositionResponse
}
  

export type updateCustomFieldNameResponse200 = {
  data: void
  status: 200
}

export type updateCustomFieldNameResponse400 = {
  data: ErrorResponseDto
  status: 400
}

export type updateCustomFieldNameResponse401 = {
  data: ErrorResponseDto
  status: 401
}

export type updateCustomFieldNameResponse404 = {
  data: ErrorResponseDto
  status: 404
}

export type updateCustomFieldNameResponse500 = {
  data: ErrorResponseDto
  status: 500
}

export type updateCustomFieldNameResponseSuccess = (updateCustomFieldNameResponse200) & {
  headers: Headers;
};
export type updateCustomFieldNameResponseError = (updateCustomFieldNameResponse400 | updateCustomFieldNameResponse401 | updateCustomFieldNameResponse404 | updateCustomFieldNameResponse500) & {
  headers: Headers;
};

export type updateCustomFieldNameResponse = (updateCustomFieldNameResponseSuccess | updateCustomFieldNameResponseError)

export const getUpdateCustomFieldNameUrl = (id: string,) => {


  

  return `/contact/custom-fields/${id}/name`
}

export const updateCustomFieldName = async (id: string,
    updateCustomFieldNameDto: UpdateCustomFieldNameDto, options?: RequestInit): Promise<updateCustomFieldNameResponse> => {
  
  const res = await fetch(getUpdateCustomFieldNameUrl(id),
  {      
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      updateCustomFieldNameDto,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: updateCustomFieldNameResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as updateCustomFieldNameResponse
}
  

export type getCustomFieldsResponse200 = {
  data: CustomFieldDto[]
  status: 200
}

export type getCustomFieldsResponse400 = {
  data: ErrorResponseDto
  status: 400
}

export type getCustomFieldsResponse401 = {
  data: ErrorResponseDto
  status: 401
}

export type getCustomFieldsResponse404 = {
  data: ErrorResponseDto
  status: 404
}

export type getCustomFieldsResponse500 = {
  data: ErrorResponseDto
  status: 500
}

export type getCustomFieldsResponseSuccess = (getCustomFieldsResponse200) & {
  headers: Headers;
};
export type getCustomFieldsResponseError = (getCustomFieldsResponse400 | getCustomFieldsResponse401 | getCustomFieldsResponse404 | getCustomFieldsResponse500) & {
  headers: Headers;
};

export type getCustomFieldsResponse = (getCustomFieldsResponseSuccess | getCustomFieldsResponseError)

export const getGetCustomFieldsUrl = () => {


  

  return `/contact/custom-fields`
}

export const getCustomFields = async ( options?: RequestInit): Promise<getCustomFieldsResponse> => {
  
  const res = await fetch(getGetCustomFieldsUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getCustomFieldsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getCustomFieldsResponse
}
  

export type createCustomFieldResponse200 = {
  data: IdDto
  status: 200
}

export type createCustomFieldResponse400 = {
  data: ErrorResponseDto
  status: 400
}

export type createCustomFieldResponse401 = {
  data: ErrorResponseDto
  status: 401
}

export type createCustomFieldResponse404 = {
  data: ErrorResponseDto
  status: 404
}

export type createCustomFieldResponse500 = {
  data: ErrorResponseDto
  status: 500
}

export type createCustomFieldResponseSuccess = (createCustomFieldResponse200) & {
  headers: Headers;
};
export type createCustomFieldResponseError = (createCustomFieldResponse400 | createCustomFieldResponse401 | createCustomFieldResponse404 | createCustomFieldResponse500) & {
  headers: Headers;
};

export type createCustomFieldResponse = (createCustomFieldResponseSuccess | createCustomFieldResponseError)

export const getCreateCustomFieldUrl = () => {


  

  return `/contact/custom-fields`
}

export const createCustomField = async (createCustomFieldDto: CreateCustomFieldDto, options?: RequestInit): Promise<createCustomFieldResponse> => {
  
  const res = await fetch(getCreateCustomFieldUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createCustomFieldDto,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: createCustomFieldResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as createCustomFieldResponse
}
  

export type getCustomFieldByIdResponse200 = {
  data: CustomFieldDto
  status: 200
}

export type getCustomFieldByIdResponse400 = {
  data: ErrorResponseDto
  status: 400
}

export type getCustomFieldByIdResponse401 = {
  data: ErrorResponseDto
  status: 401
}

export type getCustomFieldByIdResponse404 = {
  data: ErrorResponseDto
  status: 404
}

export type getCustomFieldByIdResponse500 = {
  data: ErrorResponseDto
  status: 500
}

export type getCustomFieldByIdResponseSuccess = (getCustomFieldByIdResponse200) & {
  headers: Headers;
};
export type getCustomFieldByIdResponseError = (getCustomFieldByIdResponse400 | getCustomFieldByIdResponse401 | getCustomFieldByIdResponse404 | getCustomFieldByIdResponse500) & {
  headers: Headers;
};

export type getCustomFieldByIdResponse = (getCustomFieldByIdResponseSuccess | getCustomFieldByIdResponseError)

export const getGetCustomFieldByIdUrl = (id: string,) => {


  

  return `/contact/custom-fields/${id}`
}

export const getCustomFieldById = async (id: string, options?: RequestInit): Promise<getCustomFieldByIdResponse> => {
  
  const res = await fetch(getGetCustomFieldByIdUrl(id),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getCustomFieldByIdResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getCustomFieldByIdResponse
}
  

export type deleteCustomFieldResponse200 = {
  data: void
  status: 200
}

export type deleteCustomFieldResponse400 = {
  data: ErrorResponseDto
  status: 400
}

export type deleteCustomFieldResponse401 = {
  data: ErrorResponseDto
  status: 401
}

export type deleteCustomFieldResponse404 = {
  data: ErrorResponseDto
  status: 404
}

export type deleteCustomFieldResponse500 = {
  data: ErrorResponseDto
  status: 500
}

export type deleteCustomFieldResponseSuccess = (deleteCustomFieldResponse200) & {
  headers: Headers;
};
export type deleteCustomFieldResponseError = (deleteCustomFieldResponse400 | deleteCustomFieldResponse401 | deleteCustomFieldResponse404 | deleteCustomFieldResponse500) & {
  headers: Headers;
};

export type deleteCustomFieldResponse = (deleteCustomFieldResponseSuccess | deleteCustomFieldResponseError)

export const getDeleteCustomFieldUrl = (id: string,) => {


  

  return `/contact/custom-fields/${id}`
}

export const deleteCustomField = async (id: string, options?: RequestInit): Promise<deleteCustomFieldResponse> => {
  
  const res = await fetch(getDeleteCustomFieldUrl(id),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: deleteCustomFieldResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as deleteCustomFieldResponse
}
  

