/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type {
  ErrorResponseDto,
  SendEmailOtpDto,
  SendPhoneOtpDto,
  SignUpDto
} from '../index.schemas';


/**
 * Sign up new account
 */
export type signUpResponse200 = {
  data: void
  status: 200
}

export type signUpResponse400 = {
  data: ErrorResponseDto
  status: 400
}

export type signUpResponse401 = {
  data: ErrorResponseDto
  status: 401
}

export type signUpResponse404 = {
  data: ErrorResponseDto
  status: 404
}

export type signUpResponse500 = {
  data: ErrorResponseDto
  status: 500
}

export type signUpResponseSuccess = (signUpResponse200) & {
  headers: Headers;
};
export type signUpResponseError = (signUpResponse400 | signUpResponse401 | signUpResponse404 | signUpResponse500) & {
  headers: Headers;
};

export type signUpResponse = (signUpResponseSuccess | signUpResponseError)

export const getSignUpUrl = () => {


  

  return `/tenant/sign-up`
}

export const signUp = async (signUpDto: SignUpDto, options?: RequestInit): Promise<signUpResponse> => {
  
  const res = await fetch(getSignUpUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      signUpDto,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: signUpResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as signUpResponse
}
  

/**
 * Send phone confirmation code
 */
export type sendPhoneCodeResponse200 = {
  data: void
  status: 200
}

export type sendPhoneCodeResponse400 = {
  data: ErrorResponseDto
  status: 400
}

export type sendPhoneCodeResponse401 = {
  data: ErrorResponseDto
  status: 401
}

export type sendPhoneCodeResponse404 = {
  data: ErrorResponseDto
  status: 404
}

export type sendPhoneCodeResponse500 = {
  data: ErrorResponseDto
  status: 500
}

export type sendPhoneCodeResponseSuccess = (sendPhoneCodeResponse200) & {
  headers: Headers;
};
export type sendPhoneCodeResponseError = (sendPhoneCodeResponse400 | sendPhoneCodeResponse401 | sendPhoneCodeResponse404 | sendPhoneCodeResponse500) & {
  headers: Headers;
};

export type sendPhoneCodeResponse = (sendPhoneCodeResponseSuccess | sendPhoneCodeResponseError)

export const getSendPhoneCodeUrl = () => {


  

  return `/tenant/sign-up/send-phone-code`
}

export const sendPhoneCode = async (sendPhoneOtpDto: SendPhoneOtpDto, options?: RequestInit): Promise<sendPhoneCodeResponse> => {
  
  const res = await fetch(getSendPhoneCodeUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      sendPhoneOtpDto,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: sendPhoneCodeResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as sendPhoneCodeResponse
}
  

/**
 * Send email confirmation code
 */
export type sendEmailCodeResponse200 = {
  data: void
  status: 200
}

export type sendEmailCodeResponse400 = {
  data: ErrorResponseDto
  status: 400
}

export type sendEmailCodeResponse401 = {
  data: ErrorResponseDto
  status: 401
}

export type sendEmailCodeResponse404 = {
  data: ErrorResponseDto
  status: 404
}

export type sendEmailCodeResponse500 = {
  data: ErrorResponseDto
  status: 500
}

export type sendEmailCodeResponseSuccess = (sendEmailCodeResponse200) & {
  headers: Headers;
};
export type sendEmailCodeResponseError = (sendEmailCodeResponse400 | sendEmailCodeResponse401 | sendEmailCodeResponse404 | sendEmailCodeResponse500) & {
  headers: Headers;
};

export type sendEmailCodeResponse = (sendEmailCodeResponseSuccess | sendEmailCodeResponseError)

export const getSendEmailCodeUrl = () => {


  

  return `/tenant/sign-up/send-email-code`
}

export const sendEmailCode = async (sendEmailOtpDto: SendEmailOtpDto, options?: RequestInit): Promise<sendEmailCodeResponse> => {
  
  const res = await fetch(getSendEmailCodeUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      sendEmailOtpDto,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: sendEmailCodeResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as sendEmailCodeResponse
}
  

