/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * utoipa-axum
 * Utoipa's axum bindings for seamless integration for the two
 * OpenAPI spec version: 0.2.0
 */
import type { ErrorResponse, SignInDto } from "../index.schemas";

export type CheckSessionResponse200 = {
  data: void;
  status: 200;
};

export type CheckSessionResponse401 = {
  data: ErrorResponse;
  status: 401;
};

export type CheckSessionResponse500 = {
  data: ErrorResponse;
  status: 500;
};

export type CheckSessionResponseSuccess = CheckSessionResponse200 & {
  headers: Headers;
};
export type CheckSessionResponseError = (CheckSessionResponse401 | CheckSessionResponse500) & {
  headers: Headers;
};

export type CheckSessionResponse = CheckSessionResponseSuccess | CheckSessionResponseError;

export const getCheckSessionUrl = () => {
  return `/auth/check-session`;
};

export const checkSession = async (options?: RequestInit): Promise<CheckSessionResponse> => {
  const res = await fetch(getCheckSessionUrl(), {
    ...options,
    method: "GET",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: CheckSessionResponse["data"] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as CheckSessionResponse;
};

export type SignInResponse200 = {
  data: void;
  status: 200;
};

export type SignInResponse400 = {
  data: ErrorResponse;
  status: 400;
};

export type SignInResponse500 = {
  data: ErrorResponse;
  status: 500;
};

export type SignInResponseSuccess = SignInResponse200 & {
  headers: Headers;
};
export type SignInResponseError = (SignInResponse400 | SignInResponse500) & {
  headers: Headers;
};

export type SignInResponse = SignInResponseSuccess | SignInResponseError;

export const getSignInUrl = () => {
  return `/auth/sign-in`;
};

export const signIn = async (signInDto: SignInDto, options?: RequestInit): Promise<SignInResponse> => {
  const res = await fetch(getSignInUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(signInDto),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: SignInResponse["data"] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as SignInResponse;
};

export type SignOutResponse200 = {
  data: void;
  status: 200;
};

export type SignOutResponseSuccess = SignOutResponse200 & {
  headers: Headers;
};
export type SignOutResponse = SignOutResponseSuccess;

export const getSignOutUrl = () => {
  return `/auth/sign-out`;
};

export const signOut = async (options?: RequestInit): Promise<SignOutResponse> => {
  const res = await fetch(getSignOutUrl(), {
    ...options,
    method: "POST",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: SignOutResponse["data"] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as SignOutResponse;
};
