/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { ErrorResponseDto, SignInDto } from "../index.schemas";

/**
 * Sign out
 */
export type SignOutResponse200 = {
  data: void;
  status: 200;
};

export type SignOutResponse400 = {
  data: ErrorResponseDto;
  status: 400;
};

export type SignOutResponse401 = {
  data: ErrorResponseDto;
  status: 401;
};

export type SignOutResponse404 = {
  data: ErrorResponseDto;
  status: 404;
};

export type SignOutResponse500 = {
  data: ErrorResponseDto;
  status: 500;
};

export type SignOutResponseSuccess = SignOutResponse200 & {
  headers: Headers;
};
export type SignOutResponseError = (
  | SignOutResponse400
  | SignOutResponse401
  | SignOutResponse404
  | SignOutResponse500
) & {
  headers: Headers;
};

export type SignOutResponse = SignOutResponseSuccess | SignOutResponseError;

export const getSignOutUrl = () => {
  return `/auth/sign-out`;
};

export const signOut = async (options?: RequestInit): Promise<SignOutResponse> => {
  const res = await fetch(getSignOutUrl(), {
    ...options,
    method: "POST",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: SignOutResponse["data"] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as SignOutResponse;
};

/**
 * Sign in
 */
export type SignInResponse200 = {
  data: void;
  status: 200;
};

export type SignInResponse400 = {
  data: ErrorResponseDto;
  status: 400;
};

export type SignInResponse401 = {
  data: ErrorResponseDto;
  status: 401;
};

export type SignInResponse404 = {
  data: ErrorResponseDto;
  status: 404;
};

export type SignInResponse500 = {
  data: ErrorResponseDto;
  status: 500;
};

export type SignInResponseSuccess = SignInResponse200 & {
  headers: Headers;
};
export type SignInResponseError = (SignInResponse400 | SignInResponse401 | SignInResponse404 | SignInResponse500) & {
  headers: Headers;
};

export type SignInResponse = SignInResponseSuccess | SignInResponseError;

export const getSignInUrl = () => {
  return `/auth/sign-in`;
};

export const signIn = async (signInDto: SignInDto, options?: RequestInit): Promise<SignInResponse> => {
  const res = await fetch(getSignInUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(signInDto),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: SignInResponse["data"] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as SignInResponse;
};

/**
 * Checks that session is not expired
 */
export type CheckSessionResponse200 = {
  data: void;
  status: 200;
};

export type CheckSessionResponse400 = {
  data: ErrorResponseDto;
  status: 400;
};

export type CheckSessionResponse401 = {
  data: ErrorResponseDto;
  status: 401;
};

export type CheckSessionResponse404 = {
  data: ErrorResponseDto;
  status: 404;
};

export type CheckSessionResponse500 = {
  data: ErrorResponseDto;
  status: 500;
};

export type CheckSessionResponseSuccess = CheckSessionResponse200 & {
  headers: Headers;
};
export type CheckSessionResponseError = (
  | CheckSessionResponse400
  | CheckSessionResponse401
  | CheckSessionResponse404
  | CheckSessionResponse500
) & {
  headers: Headers;
};

export type CheckSessionResponse = CheckSessionResponseSuccess | CheckSessionResponseError;

export const getCheckSessionUrl = () => {
  return `/auth/check-session`;
};

export const checkSession = async (options?: RequestInit): Promise<CheckSessionResponse> => {
  const res = await fetch(getCheckSessionUrl(), {
    ...options,
    method: "GET",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: CheckSessionResponse["data"] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as CheckSessionResponse;
};
