/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.1
 */
import type {
  AvailableTenantPhonesParams,
  BuyTenantPhoneParams,
  ErrorResponse,
  TenantPhoneDto,
} from "../index.schemas";

export type AvailableTenantPhonesResponse200 = {
  data: TenantPhoneDto[];
  status: 200;
};

export type AvailableTenantPhonesResponse500 = {
  data: ErrorResponse;
  status: 500;
};

export type AvailableTenantPhonesResponseSuccess = AvailableTenantPhonesResponse200 & {
  headers: Headers;
};
export type AvailableTenantPhonesResponseError = AvailableTenantPhonesResponse500 & {
  headers: Headers;
};

export type AvailableTenantPhonesResponse = AvailableTenantPhonesResponseSuccess | AvailableTenantPhonesResponseError;

export const getAvailableTenantPhonesUrl = (params: AvailableTenantPhonesParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/phone/tenant-phone/available?${stringifiedParams}`
    : `/phone/tenant-phone/available`;
};

export const availableTenantPhones = async (
  params: AvailableTenantPhonesParams,
  options?: RequestInit,
): Promise<AvailableTenantPhonesResponse> => {
  const res = await fetch(getAvailableTenantPhonesUrl(params), {
    ...options,
    method: "GET",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: AvailableTenantPhonesResponse["data"] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as AvailableTenantPhonesResponse;
};

export type BuyTenantPhoneResponse200 = {
  data: TenantPhoneDto;
  status: 200;
};

export type BuyTenantPhoneResponse404 = {
  data: ErrorResponse;
  status: 404;
};

export type BuyTenantPhoneResponse500 = {
  data: ErrorResponse;
  status: 500;
};

export type BuyTenantPhoneResponseSuccess = BuyTenantPhoneResponse200 & {
  headers: Headers;
};
export type BuyTenantPhoneResponseError = (BuyTenantPhoneResponse404 | BuyTenantPhoneResponse500) & {
  headers: Headers;
};

export type BuyTenantPhoneResponse = BuyTenantPhoneResponseSuccess | BuyTenantPhoneResponseError;

export const getBuyTenantPhoneUrl = (params: BuyTenantPhoneParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/phone/tenant-phone/buy?${stringifiedParams}` : `/phone/tenant-phone/buy`;
};

export const buyTenantPhone = async (
  params: BuyTenantPhoneParams,
  options?: RequestInit,
): Promise<BuyTenantPhoneResponse> => {
  const res = await fetch(getBuyTenantPhoneUrl(params), {
    ...options,
    method: "POST",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: BuyTenantPhoneResponse["data"] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as BuyTenantPhoneResponse;
};
