/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type {
  BuyTenantPhoneParams,
  ErrorResponseDto,
  GetAvailableTenantPhonesParams,
  TenantPhoneDto
} from '../index.schemas';


export type buyTenantPhoneResponse200 = {
  data: TenantPhoneDto
  status: 200
}

export type buyTenantPhoneResponse400 = {
  data: ErrorResponseDto
  status: 400
}

export type buyTenantPhoneResponse401 = {
  data: ErrorResponseDto
  status: 401
}

export type buyTenantPhoneResponse404 = {
  data: ErrorResponseDto
  status: 404
}

export type buyTenantPhoneResponse500 = {
  data: ErrorResponseDto
  status: 500
}

export type buyTenantPhoneResponseSuccess = (buyTenantPhoneResponse200) & {
  headers: Headers;
};
export type buyTenantPhoneResponseError = (buyTenantPhoneResponse400 | buyTenantPhoneResponse401 | buyTenantPhoneResponse404 | buyTenantPhoneResponse500) & {
  headers: Headers;
};

export type buyTenantPhoneResponse = (buyTenantPhoneResponseSuccess | buyTenantPhoneResponseError)

export const getBuyTenantPhoneUrl = (params: BuyTenantPhoneParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/phone/tenant-phone/buy?${stringifiedParams}` : `/phone/tenant-phone/buy`
}

export const buyTenantPhone = async (params: BuyTenantPhoneParams, options?: RequestInit): Promise<buyTenantPhoneResponse> => {
  
  const res = await fetch(getBuyTenantPhoneUrl(params),
  {      
    ...options,
    method: 'POST'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: buyTenantPhoneResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as buyTenantPhoneResponse
}
  

export type getAvailableTenantPhonesResponse200 = {
  data: TenantPhoneDto[]
  status: 200
}

export type getAvailableTenantPhonesResponse400 = {
  data: ErrorResponseDto
  status: 400
}

export type getAvailableTenantPhonesResponse401 = {
  data: ErrorResponseDto
  status: 401
}

export type getAvailableTenantPhonesResponse404 = {
  data: ErrorResponseDto
  status: 404
}

export type getAvailableTenantPhonesResponse500 = {
  data: ErrorResponseDto
  status: 500
}

export type getAvailableTenantPhonesResponseSuccess = (getAvailableTenantPhonesResponse200) & {
  headers: Headers;
};
export type getAvailableTenantPhonesResponseError = (getAvailableTenantPhonesResponse400 | getAvailableTenantPhonesResponse401 | getAvailableTenantPhonesResponse404 | getAvailableTenantPhonesResponse500) & {
  headers: Headers;
};

export type getAvailableTenantPhonesResponse = (getAvailableTenantPhonesResponseSuccess | getAvailableTenantPhonesResponseError)

export const getGetAvailableTenantPhonesUrl = (params: GetAvailableTenantPhonesParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/phone/tenant-phone/available?${stringifiedParams}` : `/phone/tenant-phone/available`
}

export const getAvailableTenantPhones = async (params: GetAvailableTenantPhonesParams, options?: RequestInit): Promise<getAvailableTenantPhonesResponse> => {
  
  const res = await fetch(getGetAvailableTenantPhonesUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getAvailableTenantPhonesResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getAvailableTenantPhonesResponse
}
  

