/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type {
  BuyTenantPhoneParams,
  ErrorResponseDto,
  GetAvailableTenantPhonesParams,
  TenantPhoneDto,
} from "../index.schemas";

export type BuyTenantPhoneResponse200 = {
  data: TenantPhoneDto;
  status: 200;
};

export type BuyTenantPhoneResponse400 = {
  data: ErrorResponseDto;
  status: 400;
};

export type BuyTenantPhoneResponse401 = {
  data: ErrorResponseDto;
  status: 401;
};

export type BuyTenantPhoneResponse404 = {
  data: ErrorResponseDto;
  status: 404;
};

export type BuyTenantPhoneResponse500 = {
  data: ErrorResponseDto;
  status: 500;
};

export type BuyTenantPhoneResponseSuccess = BuyTenantPhoneResponse200 & {
  headers: Headers;
};
export type BuyTenantPhoneResponseError = (
  | BuyTenantPhoneResponse400
  | BuyTenantPhoneResponse401
  | BuyTenantPhoneResponse404
  | BuyTenantPhoneResponse500
) & {
  headers: Headers;
};

export type BuyTenantPhoneResponse = BuyTenantPhoneResponseSuccess | BuyTenantPhoneResponseError;

export const getBuyTenantPhoneUrl = (params: BuyTenantPhoneParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/phone/tenant-phone/buy?${stringifiedParams}` : `/phone/tenant-phone/buy`;
};

export const buyTenantPhone = async (
  params: BuyTenantPhoneParams,
  options?: RequestInit,
): Promise<BuyTenantPhoneResponse> => {
  const res = await fetch(getBuyTenantPhoneUrl(params), {
    ...options,
    method: "POST",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: BuyTenantPhoneResponse["data"] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as BuyTenantPhoneResponse;
};

export type GetAvailableTenantPhonesResponse200 = {
  data: TenantPhoneDto[];
  status: 200;
};

export type GetAvailableTenantPhonesResponse400 = {
  data: ErrorResponseDto;
  status: 400;
};

export type GetAvailableTenantPhonesResponse401 = {
  data: ErrorResponseDto;
  status: 401;
};

export type GetAvailableTenantPhonesResponse404 = {
  data: ErrorResponseDto;
  status: 404;
};

export type GetAvailableTenantPhonesResponse500 = {
  data: ErrorResponseDto;
  status: 500;
};

export type GetAvailableTenantPhonesResponseSuccess = GetAvailableTenantPhonesResponse200 & {
  headers: Headers;
};
export type GetAvailableTenantPhonesResponseError = (
  | GetAvailableTenantPhonesResponse400
  | GetAvailableTenantPhonesResponse401
  | GetAvailableTenantPhonesResponse404
  | GetAvailableTenantPhonesResponse500
) & {
  headers: Headers;
};

export type GetAvailableTenantPhonesResponse =
  | GetAvailableTenantPhonesResponseSuccess
  | GetAvailableTenantPhonesResponseError;

export const getGetAvailableTenantPhonesUrl = (params: GetAvailableTenantPhonesParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/phone/tenant-phone/available?${stringifiedParams}`
    : `/phone/tenant-phone/available`;
};

export const getAvailableTenantPhones = async (
  params: GetAvailableTenantPhonesParams,
  options?: RequestInit,
): Promise<GetAvailableTenantPhonesResponse> => {
  const res = await fetch(getGetAvailableTenantPhonesUrl(params), {
    ...options,
    method: "GET",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: GetAvailableTenantPhonesResponse["data"] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as GetAvailableTenantPhonesResponse;
};
