/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.1
 */
import type {
  ChangePasswordDto,
  ChangeUserNameDto,
  ErrorResponse,
  ProfileDto,
  SendEmailOtpDto,
  SendPhoneOtpDto,
  SignUpDto,
} from "../index.schemas";

export type GetProfileResponse200 = {
  data: ProfileDto;
  status: 200;
};

export type GetProfileResponse404 = {
  data: ErrorResponse;
  status: 404;
};

export type GetProfileResponse500 = {
  data: ErrorResponse;
  status: 500;
};

export type GetProfileResponseSuccess = GetProfileResponse200 & {
  headers: Headers;
};
export type GetProfileResponseError = (GetProfileResponse404 | GetProfileResponse500) & {
  headers: Headers;
};

export type GetProfileResponse = GetProfileResponseSuccess | GetProfileResponseError;

export const getGetProfileUrl = () => {
  return `/tenant/profile`;
};

export const getProfile = async (options?: RequestInit): Promise<GetProfileResponse> => {
  const res = await fetch(getGetProfileUrl(), {
    ...options,
    method: "GET",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: GetProfileResponse["data"] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as GetProfileResponse;
};

export type ChangeNameResponse200 = {
  data: void;
  status: 200;
};

export type ChangeNameResponse400 = {
  data: ErrorResponse;
  status: 400;
};

export type ChangeNameResponse404 = {
  data: ErrorResponse;
  status: 404;
};

export type ChangeNameResponse500 = {
  data: ErrorResponse;
  status: 500;
};

export type ChangeNameResponseSuccess = ChangeNameResponse200 & {
  headers: Headers;
};
export type ChangeNameResponseError = (ChangeNameResponse400 | ChangeNameResponse404 | ChangeNameResponse500) & {
  headers: Headers;
};

export type ChangeNameResponse = ChangeNameResponseSuccess | ChangeNameResponseError;

export const getChangeNameUrl = () => {
  return `/tenant/profile/change-name`;
};

export const changeName = async (
  changeUserNameDto: ChangeUserNameDto,
  options?: RequestInit,
): Promise<ChangeNameResponse> => {
  const res = await fetch(getChangeNameUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(changeUserNameDto),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: ChangeNameResponse["data"] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as ChangeNameResponse;
};

export type ChangePasswordResponse200 = {
  data: void;
  status: 200;
};

export type ChangePasswordResponse400 = {
  data: ErrorResponse;
  status: 400;
};

export type ChangePasswordResponse404 = {
  data: ErrorResponse;
  status: 404;
};

export type ChangePasswordResponse500 = {
  data: ErrorResponse;
  status: 500;
};

export type ChangePasswordResponseSuccess = ChangePasswordResponse200 & {
  headers: Headers;
};
export type ChangePasswordResponseError = (
  | ChangePasswordResponse400
  | ChangePasswordResponse404
  | ChangePasswordResponse500
) & {
  headers: Headers;
};

export type ChangePasswordResponse = ChangePasswordResponseSuccess | ChangePasswordResponseError;

export const getChangePasswordUrl = () => {
  return `/tenant/profile/change-password`;
};

export const changePassword = async (
  changePasswordDto: ChangePasswordDto,
  options?: RequestInit,
): Promise<ChangePasswordResponse> => {
  const res = await fetch(getChangePasswordUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(changePasswordDto),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: ChangePasswordResponse["data"] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as ChangePasswordResponse;
};

export type SignUpResponse200 = {
  data: void;
  status: 200;
};

export type SignUpResponse400 = {
  data: ErrorResponse;
  status: 400;
};

export type SignUpResponse500 = {
  data: ErrorResponse;
  status: 500;
};

export type SignUpResponse501 = {
  data: ErrorResponse;
  status: 501;
};

export type SignUpResponseSuccess = SignUpResponse200 & {
  headers: Headers;
};
export type SignUpResponseError = (SignUpResponse400 | SignUpResponse500 | SignUpResponse501) & {
  headers: Headers;
};

export type SignUpResponse = SignUpResponseSuccess | SignUpResponseError;

export const getSignUpUrl = () => {
  return `/tenant/sign-up`;
};

export const signUp = async (signUpDto: SignUpDto, options?: RequestInit): Promise<SignUpResponse> => {
  const res = await fetch(getSignUpUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(signUpDto),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: SignUpResponse["data"] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as SignUpResponse;
};

export type SendEmailCodeResponse200 = {
  data: void;
  status: 200;
};

export type SendEmailCodeResponse400 = {
  data: ErrorResponse;
  status: 400;
};

export type SendEmailCodeResponse500 = {
  data: ErrorResponse;
  status: 500;
};

export type SendEmailCodeResponse501 = {
  data: ErrorResponse;
  status: 501;
};

export type SendEmailCodeResponseSuccess = SendEmailCodeResponse200 & {
  headers: Headers;
};
export type SendEmailCodeResponseError = (
  | SendEmailCodeResponse400
  | SendEmailCodeResponse500
  | SendEmailCodeResponse501
) & {
  headers: Headers;
};

export type SendEmailCodeResponse = SendEmailCodeResponseSuccess | SendEmailCodeResponseError;

export const getSendEmailCodeUrl = () => {
  return `/tenant/sign-up/send-email-code`;
};

export const sendEmailCode = async (
  sendEmailOtpDto: SendEmailOtpDto,
  options?: RequestInit,
): Promise<SendEmailCodeResponse> => {
  const res = await fetch(getSendEmailCodeUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(sendEmailOtpDto),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: SendEmailCodeResponse["data"] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as SendEmailCodeResponse;
};

export type SendPhoneCodeResponse200 = {
  data: void;
  status: 200;
};

export type SendPhoneCodeResponse400 = {
  data: ErrorResponse;
  status: 400;
};

export type SendPhoneCodeResponse500 = {
  data: ErrorResponse;
  status: 500;
};

export type SendPhoneCodeResponse501 = {
  data: ErrorResponse;
  status: 501;
};

export type SendPhoneCodeResponseSuccess = SendPhoneCodeResponse200 & {
  headers: Headers;
};
export type SendPhoneCodeResponseError = (
  | SendPhoneCodeResponse400
  | SendPhoneCodeResponse500
  | SendPhoneCodeResponse501
) & {
  headers: Headers;
};

export type SendPhoneCodeResponse = SendPhoneCodeResponseSuccess | SendPhoneCodeResponseError;

export const getSendPhoneCodeUrl = () => {
  return `/tenant/sign-up/send-phone-code`;
};

export const sendPhoneCode = async (
  sendPhoneOtpDto: SendPhoneOtpDto,
  options?: RequestInit,
): Promise<SendPhoneCodeResponse> => {
  const res = await fetch(getSendPhoneCodeUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(sendPhoneOtpDto),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: SendPhoneCodeResponse["data"] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as SendPhoneCodeResponse;
};
