/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type {
  CampaignCreateDto,
  CampaignDto,
  ErrorResponseDto,
  IdDto,
  PageCampaignDto,
  PageRequestCampaignFilterDtoCampaignSortDto,
} from "../index.schemas";

export type GetCampaignPageResponse200 = {
  data: PageCampaignDto;
  status: 200;
};

export type GetCampaignPageResponse400 = {
  data: ErrorResponseDto;
  status: 400;
};

export type GetCampaignPageResponse401 = {
  data: ErrorResponseDto;
  status: 401;
};

export type GetCampaignPageResponse404 = {
  data: ErrorResponseDto;
  status: 404;
};

export type GetCampaignPageResponse500 = {
  data: ErrorResponseDto;
  status: 500;
};

export type GetCampaignPageResponseSuccess = GetCampaignPageResponse200 & {
  headers: Headers;
};
export type GetCampaignPageResponseError = (
  | GetCampaignPageResponse400
  | GetCampaignPageResponse401
  | GetCampaignPageResponse404
  | GetCampaignPageResponse500
) & {
  headers: Headers;
};

export type GetCampaignPageResponse = GetCampaignPageResponseSuccess | GetCampaignPageResponseError;

export const getGetCampaignPageUrl = () => {
  return `/campaign/campaign`;
};

export const getCampaignPage = async (
  pageRequestCampaignFilterDtoCampaignSortDto: PageRequestCampaignFilterDtoCampaignSortDto,
  options?: RequestInit,
): Promise<GetCampaignPageResponse> => {
  const res = await fetch(getGetCampaignPageUrl(), {
    ...options,
    method: "GET",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(pageRequestCampaignFilterDtoCampaignSortDto),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: GetCampaignPageResponse["data"] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as GetCampaignPageResponse;
};

export type CreateCampaignResponse200 = {
  data: IdDto;
  status: 200;
};

export type CreateCampaignResponse400 = {
  data: ErrorResponseDto;
  status: 400;
};

export type CreateCampaignResponse401 = {
  data: ErrorResponseDto;
  status: 401;
};

export type CreateCampaignResponse404 = {
  data: ErrorResponseDto;
  status: 404;
};

export type CreateCampaignResponse500 = {
  data: ErrorResponseDto;
  status: 500;
};

export type CreateCampaignResponseSuccess = CreateCampaignResponse200 & {
  headers: Headers;
};
export type CreateCampaignResponseError = (
  | CreateCampaignResponse400
  | CreateCampaignResponse401
  | CreateCampaignResponse404
  | CreateCampaignResponse500
) & {
  headers: Headers;
};

export type CreateCampaignResponse = CreateCampaignResponseSuccess | CreateCampaignResponseError;

export const getCreateCampaignUrl = () => {
  return `/campaign/campaign`;
};

export const createCampaign = async (
  campaignCreateDto: CampaignCreateDto,
  options?: RequestInit,
): Promise<CreateCampaignResponse> => {
  const res = await fetch(getCreateCampaignUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(campaignCreateDto),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: CreateCampaignResponse["data"] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as CreateCampaignResponse;
};

export type GetCampaignByIdResponse200 = {
  data: CampaignDto;
  status: 200;
};

export type GetCampaignByIdResponse400 = {
  data: ErrorResponseDto;
  status: 400;
};

export type GetCampaignByIdResponse401 = {
  data: ErrorResponseDto;
  status: 401;
};

export type GetCampaignByIdResponse404 = {
  data: ErrorResponseDto;
  status: 404;
};

export type GetCampaignByIdResponse500 = {
  data: ErrorResponseDto;
  status: 500;
};

export type GetCampaignByIdResponseSuccess = GetCampaignByIdResponse200 & {
  headers: Headers;
};
export type GetCampaignByIdResponseError = (
  | GetCampaignByIdResponse400
  | GetCampaignByIdResponse401
  | GetCampaignByIdResponse404
  | GetCampaignByIdResponse500
) & {
  headers: Headers;
};

export type GetCampaignByIdResponse = GetCampaignByIdResponseSuccess | GetCampaignByIdResponseError;

export const getGetCampaignByIdUrl = (id: string) => {
  return `/campaign/campaign/${id}`;
};

export const getCampaignById = async (id: string, options?: RequestInit): Promise<GetCampaignByIdResponse> => {
  const res = await fetch(getGetCampaignByIdUrl(id), {
    ...options,
    method: "GET",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: GetCampaignByIdResponse["data"] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as GetCampaignByIdResponse;
};
