/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * utoipa-axum
 * Utoipa's axum bindings for seamless integration for the two
 * OpenAPI spec version: 0.2.0
 */
import type {
  CampaignCreateDto,
  CampaignDto,
  ErrorResponse,
  IdDto,
  PageCampaignDto,
  PageRequestCampaignFilterDtoCampaignSortDto,
  Ulid,
} from "../index.schemas";

export type CreateCampaignResponse200 = {
  data: IdDto;
  status: 200;
};

export type CreateCampaignResponse400 = {
  data: ErrorResponse;
  status: 400;
};

export type CreateCampaignResponse500 = {
  data: ErrorResponse;
  status: 500;
};

export type CreateCampaignResponse502 = {
  data: ErrorResponse;
  status: 502;
};

export type CreateCampaignResponseSuccess = CreateCampaignResponse200 & {
  headers: Headers;
};
export type CreateCampaignResponseError = (
  | CreateCampaignResponse400
  | CreateCampaignResponse500
  | CreateCampaignResponse502
) & {
  headers: Headers;
};

export type CreateCampaignResponse = CreateCampaignResponseSuccess | CreateCampaignResponseError;

export const getCreateCampaignUrl = () => {
  return `/campaign/campaign`;
};

export const createCampaign = async (
  campaignCreateDto: CampaignCreateDto,
  options?: RequestInit,
): Promise<CreateCampaignResponse> => {
  const res = await fetch(getCreateCampaignUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(campaignCreateDto),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: CreateCampaignResponse["data"] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as CreateCampaignResponse;
};

export type ListCampaignsResponse200 = {
  data: PageCampaignDto;
  status: 200;
};

export type ListCampaignsResponse400 = {
  data: ErrorResponse;
  status: 400;
};

export type ListCampaignsResponse500 = {
  data: ErrorResponse;
  status: 500;
};

export type ListCampaignsResponseSuccess = ListCampaignsResponse200 & {
  headers: Headers;
};
export type ListCampaignsResponseError = (ListCampaignsResponse400 | ListCampaignsResponse500) & {
  headers: Headers;
};

export type ListCampaignsResponse = ListCampaignsResponseSuccess | ListCampaignsResponseError;

export const getListCampaignsUrl = () => {
  return `/campaign/campaign/fetch`;
};

export const listCampaigns = async (
  pageRequestCampaignFilterDtoCampaignSortDto: PageRequestCampaignFilterDtoCampaignSortDto,
  options?: RequestInit,
): Promise<ListCampaignsResponse> => {
  const res = await fetch(getListCampaignsUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(pageRequestCampaignFilterDtoCampaignSortDto),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: ListCampaignsResponse["data"] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as ListCampaignsResponse;
};

export type GetCampaignResponse200 = {
  data: CampaignDto;
  status: 200;
};

export type GetCampaignResponse404 = {
  data: ErrorResponse;
  status: 404;
};

export type GetCampaignResponse500 = {
  data: ErrorResponse;
  status: 500;
};

export type GetCampaignResponseSuccess = GetCampaignResponse200 & {
  headers: Headers;
};
export type GetCampaignResponseError = (GetCampaignResponse404 | GetCampaignResponse500) & {
  headers: Headers;
};

export type GetCampaignResponse = GetCampaignResponseSuccess | GetCampaignResponseError;

export const getGetCampaignUrl = (id: Ulid) => {
  return `/campaign/campaign/${id}`;
};

export const getCampaign = async (id: Ulid, options?: RequestInit): Promise<GetCampaignResponse> => {
  const res = await fetch(getGetCampaignUrl(id), {
    ...options,
    method: "GET",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: GetCampaignResponse["data"] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as GetCampaignResponse;
};
