query ExportMessages($after: String, $filter: MessageFilterInput, $first: Int!, $sortBy: [MessageSortByInput!]! = []) {
  messages(after: $after, filter: $filter, first: $first, sortBy: $sortBy) {
    edges {
      node {
        campaign {
          id
        }
        contact {
          id
        }
        conversation {
          id
        }
        createdAt
        direction
        id
        media {
          contentType
          sizeBytes
          url
        }
        receivedAt
        sentAt
        status
        tenantPhone {
          id
        }
        tenantPhoneNumber
        text
      }
    }
    pageInfo {
      endCursor
      hasNextPage
    }
  }
}
