query Messages(
  $after: String
  $before: String
  $filter: MessageFilterInput
  $first: Int
  $last: Int
  $offset: Int
  $sortBy: [MessageSortByInput!]! = []
) {
  messages(
    after: $after
    before: $before
    filter: $filter
    first: $first
    last: $last
    offset: $offset
    sortBy: $sortBy
  ) {
    edges {
      node {
        campaign {
          id
        }
        contact {
          id
        }
        conversation {
          id
        }
        createdAt
        direction
        id
        media {
          contentType
          sizeBytes
          url
        }
        receivedAt
        sentAt
        status
        tenantPhone {
          id
        }
        tenantPhoneNumber
        text
      }
    }
    pageInfo {
      endCursor
      hasNextPage
      hasPreviousPage
      startCursor
    }
    totalCount
  }
}
