query WalletTransactions(
  $after: String
  $before: String
  $filter: WalletTransactionFilterInput
  $first: Int
  $last: Int
  $offset: Int
  $sortBy: [WalletTransactionSortByInput!]! = []
) {
  walletTransactions(
    after: $after
    before: $before
    filter: $filter
    first: $first
    last: $last
    offset: $offset
    sortBy: $sortBy
  ) {
    edges {
      node {
        amountUsdMicros
        createdAt
        currency
        entryType
        id
        source {
          __typename
          id
        }
      }
    }
    pageInfo {
      endCursor
      hasNextPage
      hasPreviousPage
      startCursor
    }
    totalCount
  }
}
