query ContactGroups(
  $after: String
  $before: String
  $filter: ContactGroupFilterInput
  $first: Int
  $last: Int
  $offset: Int
  $sortBy: [ContactGroupSortByInput!]! = []
) {
  contactGroups(
    after: $after
    before: $before
    filter: $filter
    first: $first
    last: $last
    offset: $offset
    sortBy: $sortBy
  ) {
    edges {
      node {
        id
        contactCount
        name
      }
    }
    pageInfo {
      endCursor
      hasNextPage
      hasPreviousPage
      startCursor
    }
    totalCount
  }
}
