/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type {
  ContactGroupCreateDto,
  ContactGroupDto,
  ContactGroupUpdateDto,
  ErrorResponseDto,
  IdDto,
  PageContactGroupDto,
  PageRequestContactGroupFilterDtoContactGroupSortDto,
} from "../index.schemas";

export type GetByIdResponse200 = {
  data: ContactGroupDto;
  status: 200;
};

export type GetByIdResponse400 = {
  data: ErrorResponseDto;
  status: 400;
};

export type GetByIdResponse401 = {
  data: ErrorResponseDto;
  status: 401;
};

export type GetByIdResponse404 = {
  data: ErrorResponseDto;
  status: 404;
};

export type GetByIdResponse500 = {
  data: ErrorResponseDto;
  status: 500;
};

export type GetByIdResponseSuccess = GetByIdResponse200 & {
  headers: Headers;
};
export type GetByIdResponseError = (
  | GetByIdResponse400
  | GetByIdResponse401
  | GetByIdResponse404
  | GetByIdResponse500
) & {
  headers: Headers;
};

export type GetByIdResponse = GetByIdResponseSuccess | GetByIdResponseError;

export const getGetByIdUrl = (id: string) => {
  return `/contact/contact-group/${id}`;
};

export const getById = async (id: string, options?: RequestInit): Promise<GetByIdResponse> => {
  const res = await fetch(getGetByIdUrl(id), {
    ...options,
    method: "GET",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: GetByIdResponse["data"] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as GetByIdResponse;
};

export type UpdateResponse200 = {
  data: void;
  status: 200;
};

export type UpdateResponse400 = {
  data: ErrorResponseDto;
  status: 400;
};

export type UpdateResponse401 = {
  data: ErrorResponseDto;
  status: 401;
};

export type UpdateResponse404 = {
  data: ErrorResponseDto;
  status: 404;
};

export type UpdateResponse500 = {
  data: ErrorResponseDto;
  status: 500;
};

export type UpdateResponseSuccess = UpdateResponse200 & {
  headers: Headers;
};
export type UpdateResponseError = (UpdateResponse400 | UpdateResponse401 | UpdateResponse404 | UpdateResponse500) & {
  headers: Headers;
};

export type UpdateResponse = UpdateResponseSuccess | UpdateResponseError;

export const getUpdateUrl = (id: string) => {
  return `/contact/contact-group/${id}`;
};

export const update = async (
  id: string,
  contactGroupUpdateDto: ContactGroupUpdateDto,
  options?: RequestInit,
): Promise<UpdateResponse> => {
  const res = await fetch(getUpdateUrl(id), {
    ...options,
    method: "PUT",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(contactGroupUpdateDto),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: UpdateResponse["data"] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as UpdateResponse;
};

export type _deleteResponse200 = {
  data: void;
  status: 200;
};

export type _deleteResponse400 = {
  data: ErrorResponseDto;
  status: 400;
};

export type _deleteResponse401 = {
  data: ErrorResponseDto;
  status: 401;
};

export type _deleteResponse404 = {
  data: ErrorResponseDto;
  status: 404;
};

export type _deleteResponse500 = {
  data: ErrorResponseDto;
  status: 500;
};

export type _deleteResponseSuccess = _deleteResponse200 & {
  headers: Headers;
};
export type _deleteResponseError = (
  | _deleteResponse400
  | _deleteResponse401
  | _deleteResponse404
  | _deleteResponse500
) & {
  headers: Headers;
};

export type _deleteResponse = _deleteResponseSuccess | _deleteResponseError;

export const getDeleteUrl = (id: string) => {
  return `/contact/contact-group/${id}`;
};

export const _delete = async (id: string, options?: RequestInit): Promise<_deleteResponse> => {
  const res = await fetch(getDeleteUrl(id), {
    ...options,
    method: "DELETE",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: _deleteResponse["data"] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as _deleteResponse;
};

export type CreateResponse200 = {
  data: IdDto;
  status: 200;
};

export type CreateResponse400 = {
  data: ErrorResponseDto;
  status: 400;
};

export type CreateResponse401 = {
  data: ErrorResponseDto;
  status: 401;
};

export type CreateResponse404 = {
  data: ErrorResponseDto;
  status: 404;
};

export type CreateResponse500 = {
  data: ErrorResponseDto;
  status: 500;
};

export type CreateResponseSuccess = CreateResponse200 & {
  headers: Headers;
};
export type CreateResponseError = (CreateResponse400 | CreateResponse401 | CreateResponse404 | CreateResponse500) & {
  headers: Headers;
};

export type CreateResponse = CreateResponseSuccess | CreateResponseError;

export const getCreateUrl = () => {
  return `/contact/contact-group`;
};

export const create = async (
  contactGroupCreateDto: ContactGroupCreateDto,
  options?: RequestInit,
): Promise<CreateResponse> => {
  const res = await fetch(getCreateUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(contactGroupCreateDto),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: CreateResponse["data"] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as CreateResponse;
};

export type GetPageResponse200 = {
  data: PageContactGroupDto;
  status: 200;
};

export type GetPageResponse400 = {
  data: ErrorResponseDto;
  status: 400;
};

export type GetPageResponse401 = {
  data: ErrorResponseDto;
  status: 401;
};

export type GetPageResponse404 = {
  data: ErrorResponseDto;
  status: 404;
};

export type GetPageResponse500 = {
  data: ErrorResponseDto;
  status: 500;
};

export type GetPageResponseSuccess = GetPageResponse200 & {
  headers: Headers;
};
export type GetPageResponseError = (
  | GetPageResponse400
  | GetPageResponse401
  | GetPageResponse404
  | GetPageResponse500
) & {
  headers: Headers;
};

export type GetPageResponse = GetPageResponseSuccess | GetPageResponseError;

export const getGetPageUrl = () => {
  return `/contact/contact-group/fetch`;
};

export const getPage = async (
  pageRequestContactGroupFilterDtoContactGroupSortDto: PageRequestContactGroupFilterDtoContactGroupSortDto,
  options?: RequestInit,
): Promise<GetPageResponse> => {
  const res = await fetch(getGetPageUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(pageRequestContactGroupFilterDtoContactGroupSortDto),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: GetPageResponse["data"] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as GetPageResponse;
};
