/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * utoipa-axum
 * Utoipa's axum bindings for seamless integration for the two
 * OpenAPI spec version: 0.2.0
 */
import type {
  ContactGroupCreateDto,
  ContactGroupDto,
  ContactGroupUpdateDto,
  ErrorResponse,
  IdDto,
  PageContactGroupDto,
  PageRequestContactGroupFilterDtoContactGroupSortDto,
  Ulid,
} from "../index.schemas";

export type CreateContactGroupResponse200 = {
  data: IdDto;
  status: 200;
};

export type CreateContactGroupResponse400 = {
  data: ErrorResponse;
  status: 400;
};

export type CreateContactGroupResponse500 = {
  data: ErrorResponse;
  status: 500;
};

export type CreateContactGroupResponseSuccess = CreateContactGroupResponse200 & {
  headers: Headers;
};
export type CreateContactGroupResponseError = (CreateContactGroupResponse400 | CreateContactGroupResponse500) & {
  headers: Headers;
};

export type CreateContactGroupResponse = CreateContactGroupResponseSuccess | CreateContactGroupResponseError;

export const getCreateContactGroupUrl = () => {
  return `/contact/contact-group`;
};

export const createContactGroup = async (
  contactGroupCreateDto: ContactGroupCreateDto,
  options?: RequestInit,
): Promise<CreateContactGroupResponse> => {
  const res = await fetch(getCreateContactGroupUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(contactGroupCreateDto),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: CreateContactGroupResponse["data"] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as CreateContactGroupResponse;
};

export type FetchContactGroupsResponse200 = {
  data: PageContactGroupDto;
  status: 200;
};

export type FetchContactGroupsResponse400 = {
  data: ErrorResponse;
  status: 400;
};

export type FetchContactGroupsResponse500 = {
  data: ErrorResponse;
  status: 500;
};

export type FetchContactGroupsResponseSuccess = FetchContactGroupsResponse200 & {
  headers: Headers;
};
export type FetchContactGroupsResponseError = (FetchContactGroupsResponse400 | FetchContactGroupsResponse500) & {
  headers: Headers;
};

export type FetchContactGroupsResponse = FetchContactGroupsResponseSuccess | FetchContactGroupsResponseError;

export const getFetchContactGroupsUrl = () => {
  return `/contact/contact-group/fetch`;
};

export const fetchContactGroups = async (
  pageRequestContactGroupFilterDtoContactGroupSortDto: PageRequestContactGroupFilterDtoContactGroupSortDto,
  options?: RequestInit,
): Promise<FetchContactGroupsResponse> => {
  const res = await fetch(getFetchContactGroupsUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(pageRequestContactGroupFilterDtoContactGroupSortDto),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: FetchContactGroupsResponse["data"] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as FetchContactGroupsResponse;
};

export type GetContactGroupResponse200 = {
  data: ContactGroupDto;
  status: 200;
};

export type GetContactGroupResponse404 = {
  data: ErrorResponse;
  status: 404;
};

export type GetContactGroupResponse500 = {
  data: ErrorResponse;
  status: 500;
};

export type GetContactGroupResponseSuccess = GetContactGroupResponse200 & {
  headers: Headers;
};
export type GetContactGroupResponseError = (GetContactGroupResponse404 | GetContactGroupResponse500) & {
  headers: Headers;
};

export type GetContactGroupResponse = GetContactGroupResponseSuccess | GetContactGroupResponseError;

export const getGetContactGroupUrl = (id: Ulid) => {
  return `/contact/contact-group/${id}`;
};

export const getContactGroup = async (id: Ulid, options?: RequestInit): Promise<GetContactGroupResponse> => {
  const res = await fetch(getGetContactGroupUrl(id), {
    ...options,
    method: "GET",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: GetContactGroupResponse["data"] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as GetContactGroupResponse;
};

export type UpdateContactGroupResponse200 = {
  data: void;
  status: 200;
};

export type UpdateContactGroupResponse400 = {
  data: ErrorResponse;
  status: 400;
};

export type UpdateContactGroupResponse404 = {
  data: ErrorResponse;
  status: 404;
};

export type UpdateContactGroupResponse500 = {
  data: ErrorResponse;
  status: 500;
};

export type UpdateContactGroupResponseSuccess = UpdateContactGroupResponse200 & {
  headers: Headers;
};
export type UpdateContactGroupResponseError = (
  | UpdateContactGroupResponse400
  | UpdateContactGroupResponse404
  | UpdateContactGroupResponse500
) & {
  headers: Headers;
};

export type UpdateContactGroupResponse = UpdateContactGroupResponseSuccess | UpdateContactGroupResponseError;

export const getUpdateContactGroupUrl = (id: Ulid) => {
  return `/contact/contact-group/${id}`;
};

export const updateContactGroup = async (
  id: Ulid,
  contactGroupUpdateDto: ContactGroupUpdateDto,
  options?: RequestInit,
): Promise<UpdateContactGroupResponse> => {
  const res = await fetch(getUpdateContactGroupUrl(id), {
    ...options,
    method: "PUT",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(contactGroupUpdateDto),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: UpdateContactGroupResponse["data"] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as UpdateContactGroupResponse;
};

export type DeleteContactGroupResponse200 = {
  data: void;
  status: 200;
};

export type DeleteContactGroupResponse404 = {
  data: ErrorResponse;
  status: 404;
};

export type DeleteContactGroupResponse500 = {
  data: ErrorResponse;
  status: 500;
};

export type DeleteContactGroupResponseSuccess = DeleteContactGroupResponse200 & {
  headers: Headers;
};
export type DeleteContactGroupResponseError = (DeleteContactGroupResponse404 | DeleteContactGroupResponse500) & {
  headers: Headers;
};

export type DeleteContactGroupResponse = DeleteContactGroupResponseSuccess | DeleteContactGroupResponseError;

export const getDeleteContactGroupUrl = (id: Ulid) => {
  return `/contact/contact-group/${id}`;
};

export const deleteContactGroup = async (id: Ulid, options?: RequestInit): Promise<DeleteContactGroupResponse> => {
  const res = await fetch(getDeleteContactGroupUrl(id), {
    ...options,
    method: "DELETE",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: DeleteContactGroupResponse["data"] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as DeleteContactGroupResponse;
};
