/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type {
  ContactGroupCreateDto,
  ContactGroupDto,
  ContactGroupUpdateDto,
  ErrorResponseDto,
  IdDto,
  PageContactGroupDto,
  PageRequestContactGroupFilterDtoContactGroupSortDto
} from '../index.schemas';


export type getByIdResponse200 = {
  data: ContactGroupDto
  status: 200
}

export type getByIdResponse400 = {
  data: ErrorResponseDto
  status: 400
}

export type getByIdResponse401 = {
  data: ErrorResponseDto
  status: 401
}

export type getByIdResponse404 = {
  data: ErrorResponseDto
  status: 404
}

export type getByIdResponse500 = {
  data: ErrorResponseDto
  status: 500
}

export type getByIdResponseSuccess = (getByIdResponse200) & {
  headers: Headers;
};
export type getByIdResponseError = (getByIdResponse400 | getByIdResponse401 | getByIdResponse404 | getByIdResponse500) & {
  headers: Headers;
};

export type getByIdResponse = (getByIdResponseSuccess | getByIdResponseError)

export const getGetByIdUrl = (id: string,) => {


  

  return `/contact/contact-group/${id}`
}

export const getById = async (id: string, options?: RequestInit): Promise<getByIdResponse> => {
  
  const res = await fetch(getGetByIdUrl(id),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getByIdResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getByIdResponse
}
  

export type updateResponse200 = {
  data: void
  status: 200
}

export type updateResponse400 = {
  data: ErrorResponseDto
  status: 400
}

export type updateResponse401 = {
  data: ErrorResponseDto
  status: 401
}

export type updateResponse404 = {
  data: ErrorResponseDto
  status: 404
}

export type updateResponse500 = {
  data: ErrorResponseDto
  status: 500
}

export type updateResponseSuccess = (updateResponse200) & {
  headers: Headers;
};
export type updateResponseError = (updateResponse400 | updateResponse401 | updateResponse404 | updateResponse500) & {
  headers: Headers;
};

export type updateResponse = (updateResponseSuccess | updateResponseError)

export const getUpdateUrl = (id: string,) => {


  

  return `/contact/contact-group/${id}`
}

export const update = async (id: string,
    contactGroupUpdateDto: ContactGroupUpdateDto, options?: RequestInit): Promise<updateResponse> => {
  
  const res = await fetch(getUpdateUrl(id),
  {      
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      contactGroupUpdateDto,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: updateResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as updateResponse
}
  

export type _deleteResponse200 = {
  data: void
  status: 200
}

export type _deleteResponse400 = {
  data: ErrorResponseDto
  status: 400
}

export type _deleteResponse401 = {
  data: ErrorResponseDto
  status: 401
}

export type _deleteResponse404 = {
  data: ErrorResponseDto
  status: 404
}

export type _deleteResponse500 = {
  data: ErrorResponseDto
  status: 500
}

export type _deleteResponseSuccess = (_deleteResponse200) & {
  headers: Headers;
};
export type _deleteResponseError = (_deleteResponse400 | _deleteResponse401 | _deleteResponse404 | _deleteResponse500) & {
  headers: Headers;
};

export type _deleteResponse = (_deleteResponseSuccess | _deleteResponseError)

export const getDeleteUrl = (id: string,) => {


  

  return `/contact/contact-group/${id}`
}

export const _delete = async (id: string, options?: RequestInit): Promise<_deleteResponse> => {
  
  const res = await fetch(getDeleteUrl(id),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: _deleteResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as _deleteResponse
}
  

export type createResponse200 = {
  data: IdDto
  status: 200
}

export type createResponse400 = {
  data: ErrorResponseDto
  status: 400
}

export type createResponse401 = {
  data: ErrorResponseDto
  status: 401
}

export type createResponse404 = {
  data: ErrorResponseDto
  status: 404
}

export type createResponse500 = {
  data: ErrorResponseDto
  status: 500
}

export type createResponseSuccess = (createResponse200) & {
  headers: Headers;
};
export type createResponseError = (createResponse400 | createResponse401 | createResponse404 | createResponse500) & {
  headers: Headers;
};

export type createResponse = (createResponseSuccess | createResponseError)

export const getCreateUrl = () => {


  

  return `/contact/contact-group`
}

export const create = async (contactGroupCreateDto: ContactGroupCreateDto, options?: RequestInit): Promise<createResponse> => {
  
  const res = await fetch(getCreateUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      contactGroupCreateDto,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: createResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as createResponse
}
  

export type getPageResponse200 = {
  data: PageContactGroupDto
  status: 200
}

export type getPageResponse400 = {
  data: ErrorResponseDto
  status: 400
}

export type getPageResponse401 = {
  data: ErrorResponseDto
  status: 401
}

export type getPageResponse404 = {
  data: ErrorResponseDto
  status: 404
}

export type getPageResponse500 = {
  data: ErrorResponseDto
  status: 500
}

export type getPageResponseSuccess = (getPageResponse200) & {
  headers: Headers;
};
export type getPageResponseError = (getPageResponse400 | getPageResponse401 | getPageResponse404 | getPageResponse500) & {
  headers: Headers;
};

export type getPageResponse = (getPageResponseSuccess | getPageResponseError)

export const getGetPageUrl = () => {


  

  return `/contact/contact-group/fetch`
}

export const getPage = async (pageRequestContactGroupFilterDtoContactGroupSortDto: PageRequestContactGroupFilterDtoContactGroupSortDto, options?: RequestInit): Promise<getPageResponse> => {
  
  const res = await fetch(getGetPageUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      pageRequestContactGroupFilterDtoContactGroupSortDto,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getPageResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getPageResponse
}
  

