/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.1
 */
import type { ErrorResponse, TenDlcBrandDto, TenDlcBrandUpdate } from "../index.schemas";

export type GetTenDlcBrandResponse200 = {
  data: TenDlcBrandDto;
  status: 200;
};

export type GetTenDlcBrandResponse404 = {
  data: ErrorResponse;
  status: 404;
};

export type GetTenDlcBrandResponse500 = {
  data: ErrorResponse;
  status: 500;
};

export type GetTenDlcBrandResponseSuccess = GetTenDlcBrandResponse200 & {
  headers: Headers;
};
export type GetTenDlcBrandResponseError = (GetTenDlcBrandResponse404 | GetTenDlcBrandResponse500) & {
  headers: Headers;
};

export type GetTenDlcBrandResponse = GetTenDlcBrandResponseSuccess | GetTenDlcBrandResponseError;

export const getGetTenDlcBrandUrl = () => {
  return `/phone/ten-dlc-brand`;
};

export const getTenDlcBrand = async (options?: RequestInit): Promise<GetTenDlcBrandResponse> => {
  const res = await fetch(getGetTenDlcBrandUrl(), {
    ...options,
    method: "GET",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: GetTenDlcBrandResponse["data"] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as GetTenDlcBrandResponse;
};

export type UpdateTenDlcBrandResponse200 = {
  data: TenDlcBrandDto;
  status: 200;
};

export type UpdateTenDlcBrandResponse404 = {
  data: ErrorResponse;
  status: 404;
};

export type UpdateTenDlcBrandResponse500 = {
  data: ErrorResponse;
  status: 500;
};

export type UpdateTenDlcBrandResponseSuccess = UpdateTenDlcBrandResponse200 & {
  headers: Headers;
};
export type UpdateTenDlcBrandResponseError = (UpdateTenDlcBrandResponse404 | UpdateTenDlcBrandResponse500) & {
  headers: Headers;
};

export type UpdateTenDlcBrandResponse = UpdateTenDlcBrandResponseSuccess | UpdateTenDlcBrandResponseError;

export const getUpdateTenDlcBrandUrl = () => {
  return `/phone/ten-dlc-brand`;
};

export const updateTenDlcBrand = async (
  tenDlcBrandUpdate: TenDlcBrandUpdate,
  options?: RequestInit,
): Promise<UpdateTenDlcBrandResponse> => {
  const res = await fetch(getUpdateTenDlcBrandUrl(), {
    ...options,
    method: "PUT",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(tenDlcBrandUpdate),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: UpdateTenDlcBrandResponse["data"] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as UpdateTenDlcBrandResponse;
};

export type CreateTenDlcBrandResponse200 = {
  data: TenDlcBrandDto;
  status: 200;
};

export type CreateTenDlcBrandResponse500 = {
  data: ErrorResponse;
  status: 500;
};

export type CreateTenDlcBrandResponseSuccess = CreateTenDlcBrandResponse200 & {
  headers: Headers;
};
export type CreateTenDlcBrandResponseError = CreateTenDlcBrandResponse500 & {
  headers: Headers;
};

export type CreateTenDlcBrandResponse = CreateTenDlcBrandResponseSuccess | CreateTenDlcBrandResponseError;

export const getCreateTenDlcBrandUrl = () => {
  return `/phone/ten-dlc-brand`;
};

export const createTenDlcBrand = async (
  tenDlcBrandUpdate: TenDlcBrandUpdate,
  options?: RequestInit,
): Promise<CreateTenDlcBrandResponse> => {
  const res = await fetch(getCreateTenDlcBrandUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(tenDlcBrandUpdate),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: CreateTenDlcBrandResponse["data"] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as CreateTenDlcBrandResponse;
};
