/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type {
  ErrorResponseDto,
  TenDlcBrandDto,
  TenDlcBrandUpdateDto
} from '../index.schemas';


export type getTenDlcBrandResponse200 = {
  data: TenDlcBrandDto
  status: 200
}

export type getTenDlcBrandResponse400 = {
  data: ErrorResponseDto
  status: 400
}

export type getTenDlcBrandResponse401 = {
  data: ErrorResponseDto
  status: 401
}

export type getTenDlcBrandResponse404 = {
  data: ErrorResponseDto
  status: 404
}

export type getTenDlcBrandResponse500 = {
  data: ErrorResponseDto
  status: 500
}

export type getTenDlcBrandResponseSuccess = (getTenDlcBrandResponse200) & {
  headers: Headers;
};
export type getTenDlcBrandResponseError = (getTenDlcBrandResponse400 | getTenDlcBrandResponse401 | getTenDlcBrandResponse404 | getTenDlcBrandResponse500) & {
  headers: Headers;
};

export type getTenDlcBrandResponse = (getTenDlcBrandResponseSuccess | getTenDlcBrandResponseError)

export const getGetTenDlcBrandUrl = () => {


  

  return `/phone/ten-dlc-brand`
}

export const getTenDlcBrand = async ( options?: RequestInit): Promise<getTenDlcBrandResponse> => {
  
  const res = await fetch(getGetTenDlcBrandUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getTenDlcBrandResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getTenDlcBrandResponse
}
  

export type updateTenDlcBrandResponse200 = {
  data: TenDlcBrandDto
  status: 200
}

export type updateTenDlcBrandResponse400 = {
  data: ErrorResponseDto
  status: 400
}

export type updateTenDlcBrandResponse401 = {
  data: ErrorResponseDto
  status: 401
}

export type updateTenDlcBrandResponse404 = {
  data: ErrorResponseDto
  status: 404
}

export type updateTenDlcBrandResponse500 = {
  data: ErrorResponseDto
  status: 500
}

export type updateTenDlcBrandResponseSuccess = (updateTenDlcBrandResponse200) & {
  headers: Headers;
};
export type updateTenDlcBrandResponseError = (updateTenDlcBrandResponse400 | updateTenDlcBrandResponse401 | updateTenDlcBrandResponse404 | updateTenDlcBrandResponse500) & {
  headers: Headers;
};

export type updateTenDlcBrandResponse = (updateTenDlcBrandResponseSuccess | updateTenDlcBrandResponseError)

export const getUpdateTenDlcBrandUrl = () => {


  

  return `/phone/ten-dlc-brand`
}

export const updateTenDlcBrand = async (tenDlcBrandUpdateDto: TenDlcBrandUpdateDto, options?: RequestInit): Promise<updateTenDlcBrandResponse> => {
  
  const res = await fetch(getUpdateTenDlcBrandUrl(),
  {      
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      tenDlcBrandUpdateDto,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: updateTenDlcBrandResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as updateTenDlcBrandResponse
}
  

export type createTenDlcBrandResponse200 = {
  data: TenDlcBrandDto
  status: 200
}

export type createTenDlcBrandResponse400 = {
  data: ErrorResponseDto
  status: 400
}

export type createTenDlcBrandResponse401 = {
  data: ErrorResponseDto
  status: 401
}

export type createTenDlcBrandResponse404 = {
  data: ErrorResponseDto
  status: 404
}

export type createTenDlcBrandResponse500 = {
  data: ErrorResponseDto
  status: 500
}

export type createTenDlcBrandResponseSuccess = (createTenDlcBrandResponse200) & {
  headers: Headers;
};
export type createTenDlcBrandResponseError = (createTenDlcBrandResponse400 | createTenDlcBrandResponse401 | createTenDlcBrandResponse404 | createTenDlcBrandResponse500) & {
  headers: Headers;
};

export type createTenDlcBrandResponse = (createTenDlcBrandResponseSuccess | createTenDlcBrandResponseError)

export const getCreateTenDlcBrandUrl = () => {


  

  return `/phone/ten-dlc-brand`
}

export const createTenDlcBrand = async (tenDlcBrandUpdateDto: TenDlcBrandUpdateDto, options?: RequestInit): Promise<createTenDlcBrandResponse> => {
  
  const res = await fetch(getCreateTenDlcBrandUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      tenDlcBrandUpdateDto,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: createTenDlcBrandResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as createTenDlcBrandResponse
}
  

