/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { ErrorResponseDto, TenDlcBrandDto, TenDlcBrandUpdateDto } from "../index.schemas";

export type GetTenDlcBrandResponse200 = {
  data: TenDlcBrandDto;
  status: 200;
};

export type GetTenDlcBrandResponse400 = {
  data: ErrorResponseDto;
  status: 400;
};

export type GetTenDlcBrandResponse401 = {
  data: ErrorResponseDto;
  status: 401;
};

export type GetTenDlcBrandResponse404 = {
  data: ErrorResponseDto;
  status: 404;
};

export type GetTenDlcBrandResponse500 = {
  data: ErrorResponseDto;
  status: 500;
};

export type GetTenDlcBrandResponseSuccess = GetTenDlcBrandResponse200 & {
  headers: Headers;
};
export type GetTenDlcBrandResponseError = (
  | GetTenDlcBrandResponse400
  | GetTenDlcBrandResponse401
  | GetTenDlcBrandResponse404
  | GetTenDlcBrandResponse500
) & {
  headers: Headers;
};

export type GetTenDlcBrandResponse = GetTenDlcBrandResponseSuccess | GetTenDlcBrandResponseError;

export const getGetTenDlcBrandUrl = () => {
  return `/phone/ten-dlc-brand`;
};

export const getTenDlcBrand = async (options?: RequestInit): Promise<GetTenDlcBrandResponse> => {
  const res = await fetch(getGetTenDlcBrandUrl(), {
    ...options,
    method: "GET",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: GetTenDlcBrandResponse["data"] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as GetTenDlcBrandResponse;
};

export type UpdateTenDlcBrandResponse200 = {
  data: TenDlcBrandDto;
  status: 200;
};

export type UpdateTenDlcBrandResponse400 = {
  data: ErrorResponseDto;
  status: 400;
};

export type UpdateTenDlcBrandResponse401 = {
  data: ErrorResponseDto;
  status: 401;
};

export type UpdateTenDlcBrandResponse404 = {
  data: ErrorResponseDto;
  status: 404;
};

export type UpdateTenDlcBrandResponse500 = {
  data: ErrorResponseDto;
  status: 500;
};

export type UpdateTenDlcBrandResponseSuccess = UpdateTenDlcBrandResponse200 & {
  headers: Headers;
};
export type UpdateTenDlcBrandResponseError = (
  | UpdateTenDlcBrandResponse400
  | UpdateTenDlcBrandResponse401
  | UpdateTenDlcBrandResponse404
  | UpdateTenDlcBrandResponse500
) & {
  headers: Headers;
};

export type UpdateTenDlcBrandResponse = UpdateTenDlcBrandResponseSuccess | UpdateTenDlcBrandResponseError;

export const getUpdateTenDlcBrandUrl = () => {
  return `/phone/ten-dlc-brand`;
};

export const updateTenDlcBrand = async (
  tenDlcBrandUpdateDto: TenDlcBrandUpdateDto,
  options?: RequestInit,
): Promise<UpdateTenDlcBrandResponse> => {
  const res = await fetch(getUpdateTenDlcBrandUrl(), {
    ...options,
    method: "PUT",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(tenDlcBrandUpdateDto),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: UpdateTenDlcBrandResponse["data"] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as UpdateTenDlcBrandResponse;
};

export type CreateTenDlcBrandResponse200 = {
  data: TenDlcBrandDto;
  status: 200;
};

export type CreateTenDlcBrandResponse400 = {
  data: ErrorResponseDto;
  status: 400;
};

export type CreateTenDlcBrandResponse401 = {
  data: ErrorResponseDto;
  status: 401;
};

export type CreateTenDlcBrandResponse404 = {
  data: ErrorResponseDto;
  status: 404;
};

export type CreateTenDlcBrandResponse500 = {
  data: ErrorResponseDto;
  status: 500;
};

export type CreateTenDlcBrandResponseSuccess = CreateTenDlcBrandResponse200 & {
  headers: Headers;
};
export type CreateTenDlcBrandResponseError = (
  | CreateTenDlcBrandResponse400
  | CreateTenDlcBrandResponse401
  | CreateTenDlcBrandResponse404
  | CreateTenDlcBrandResponse500
) & {
  headers: Headers;
};

export type CreateTenDlcBrandResponse = CreateTenDlcBrandResponseSuccess | CreateTenDlcBrandResponseError;

export const getCreateTenDlcBrandUrl = () => {
  return `/phone/ten-dlc-brand`;
};

export const createTenDlcBrand = async (
  tenDlcBrandUpdateDto: TenDlcBrandUpdateDto,
  options?: RequestInit,
): Promise<CreateTenDlcBrandResponse> => {
  const res = await fetch(getCreateTenDlcBrandUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(tenDlcBrandUpdateDto),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: CreateTenDlcBrandResponse["data"] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as CreateTenDlcBrandResponse;
};
