/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type {
  ChangePasswordDto,
  ChangeUserNameDto,
  ErrorResponseDto,
  ProfileDto
} from '../index.schemas';


/**
 * Change password for current authenticated user
 */
export type changePasswordResponse200 = {
  data: void
  status: 200
}

export type changePasswordResponse400 = {
  data: ErrorResponseDto
  status: 400
}

export type changePasswordResponse401 = {
  data: ErrorResponseDto
  status: 401
}

export type changePasswordResponse404 = {
  data: ErrorResponseDto
  status: 404
}

export type changePasswordResponse500 = {
  data: ErrorResponseDto
  status: 500
}

export type changePasswordResponseSuccess = (changePasswordResponse200) & {
  headers: Headers;
};
export type changePasswordResponseError = (changePasswordResponse400 | changePasswordResponse401 | changePasswordResponse404 | changePasswordResponse500) & {
  headers: Headers;
};

export type changePasswordResponse = (changePasswordResponseSuccess | changePasswordResponseError)

export const getChangePasswordUrl = () => {


  

  return `/tenant/profile/change-password`
}

export const changePassword = async (changePasswordDto: ChangePasswordDto, options?: RequestInit): Promise<changePasswordResponse> => {
  
  const res = await fetch(getChangePasswordUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      changePasswordDto,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: changePasswordResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as changePasswordResponse
}
  

/**
 * Change name for current authenticated user
 */
export type changeNameResponse200 = {
  data: void
  status: 200
}

export type changeNameResponse400 = {
  data: ErrorResponseDto
  status: 400
}

export type changeNameResponse401 = {
  data: ErrorResponseDto
  status: 401
}

export type changeNameResponse404 = {
  data: ErrorResponseDto
  status: 404
}

export type changeNameResponse500 = {
  data: ErrorResponseDto
  status: 500
}

export type changeNameResponseSuccess = (changeNameResponse200) & {
  headers: Headers;
};
export type changeNameResponseError = (changeNameResponse400 | changeNameResponse401 | changeNameResponse404 | changeNameResponse500) & {
  headers: Headers;
};

export type changeNameResponse = (changeNameResponseSuccess | changeNameResponseError)

export const getChangeNameUrl = () => {


  

  return `/tenant/profile/change-name`
}

export const changeName = async (changeUserNameDto: ChangeUserNameDto, options?: RequestInit): Promise<changeNameResponse> => {
  
  const res = await fetch(getChangeNameUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      changeUserNameDto,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: changeNameResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as changeNameResponse
}
  

/**
 * Returns info about authenticated user
 */
export type getProfileResponse200 = {
  data: ProfileDto
  status: 200
}

export type getProfileResponse400 = {
  data: ErrorResponseDto
  status: 400
}

export type getProfileResponse401 = {
  data: ErrorResponseDto
  status: 401
}

export type getProfileResponse404 = {
  data: ErrorResponseDto
  status: 404
}

export type getProfileResponse500 = {
  data: ErrorResponseDto
  status: 500
}

export type getProfileResponseSuccess = (getProfileResponse200) & {
  headers: Headers;
};
export type getProfileResponseError = (getProfileResponse400 | getProfileResponse401 | getProfileResponse404 | getProfileResponse500) & {
  headers: Headers;
};

export type getProfileResponse = (getProfileResponseSuccess | getProfileResponseError)

export const getGetProfileUrl = () => {


  

  return `/tenant/profile`
}

export const getProfile = async ( options?: RequestInit): Promise<getProfileResponse> => {
  
  const res = await fetch(getGetProfileUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getProfileResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getProfileResponse
}
  

