/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { ChangePasswordDto, ChangeUserNameDto, ErrorResponseDto, ProfileDto } from "../index.schemas";

/**
 * Change password for current authenticated user
 */
export type ChangePasswordResponse200 = {
  data: void;
  status: 200;
};

export type ChangePasswordResponse400 = {
  data: ErrorResponseDto;
  status: 400;
};

export type ChangePasswordResponse401 = {
  data: ErrorResponseDto;
  status: 401;
};

export type ChangePasswordResponse404 = {
  data: ErrorResponseDto;
  status: 404;
};

export type ChangePasswordResponse500 = {
  data: ErrorResponseDto;
  status: 500;
};

export type ChangePasswordResponseSuccess = ChangePasswordResponse200 & {
  headers: Headers;
};
export type ChangePasswordResponseError = (
  | ChangePasswordResponse400
  | ChangePasswordResponse401
  | ChangePasswordResponse404
  | ChangePasswordResponse500
) & {
  headers: Headers;
};

export type ChangePasswordResponse = ChangePasswordResponseSuccess | ChangePasswordResponseError;

export const getChangePasswordUrl = () => {
  return `/tenant/profile/change-password`;
};

export const changePassword = async (
  changePasswordDto: ChangePasswordDto,
  options?: RequestInit,
): Promise<ChangePasswordResponse> => {
  const res = await fetch(getChangePasswordUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(changePasswordDto),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: ChangePasswordResponse["data"] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as ChangePasswordResponse;
};

/**
 * Change name for current authenticated user
 */
export type ChangeNameResponse200 = {
  data: void;
  status: 200;
};

export type ChangeNameResponse400 = {
  data: ErrorResponseDto;
  status: 400;
};

export type ChangeNameResponse401 = {
  data: ErrorResponseDto;
  status: 401;
};

export type ChangeNameResponse404 = {
  data: ErrorResponseDto;
  status: 404;
};

export type ChangeNameResponse500 = {
  data: ErrorResponseDto;
  status: 500;
};

export type ChangeNameResponseSuccess = ChangeNameResponse200 & {
  headers: Headers;
};
export type ChangeNameResponseError = (
  | ChangeNameResponse400
  | ChangeNameResponse401
  | ChangeNameResponse404
  | ChangeNameResponse500
) & {
  headers: Headers;
};

export type ChangeNameResponse = ChangeNameResponseSuccess | ChangeNameResponseError;

export const getChangeNameUrl = () => {
  return `/tenant/profile/change-name`;
};

export const changeName = async (
  changeUserNameDto: ChangeUserNameDto,
  options?: RequestInit,
): Promise<ChangeNameResponse> => {
  const res = await fetch(getChangeNameUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(changeUserNameDto),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: ChangeNameResponse["data"] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as ChangeNameResponse;
};

/**
 * Returns info about authenticated user
 */
export type GetProfileResponse200 = {
  data: ProfileDto;
  status: 200;
};

export type GetProfileResponse400 = {
  data: ErrorResponseDto;
  status: 400;
};

export type GetProfileResponse401 = {
  data: ErrorResponseDto;
  status: 401;
};

export type GetProfileResponse404 = {
  data: ErrorResponseDto;
  status: 404;
};

export type GetProfileResponse500 = {
  data: ErrorResponseDto;
  status: 500;
};

export type GetProfileResponseSuccess = GetProfileResponse200 & {
  headers: Headers;
};
export type GetProfileResponseError = (
  | GetProfileResponse400
  | GetProfileResponse401
  | GetProfileResponse404
  | GetProfileResponse500
) & {
  headers: Headers;
};

export type GetProfileResponse = GetProfileResponseSuccess | GetProfileResponseError;

export const getGetProfileUrl = () => {
  return `/tenant/profile`;
};

export const getProfile = async (options?: RequestInit): Promise<GetProfileResponse> => {
  const res = await fetch(getGetProfileUrl(), {
    ...options,
    method: "GET",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: GetProfileResponse["data"] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as GetProfileResponse;
};
