/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.1
 */
import type {
  ErrorResponse,
  MessageDto,
  MessageExportDto,
  PageMessageDto,
  PageRequestMessageFilterDtoMessageSortDto,
  Ulid,
} from "../index.schemas";

export type GetPageResponse200 = {
  data: PageMessageDto;
  status: 200;
};

export type GetPageResponse400 = {
  data: ErrorResponse;
  status: 400;
};

export type GetPageResponse500 = {
  data: ErrorResponse;
  status: 500;
};

export type GetPageResponseSuccess = GetPageResponse200 & {
  headers: Headers;
};
export type GetPageResponseError = (GetPageResponse400 | GetPageResponse500) & {
  headers: Headers;
};

export type GetPageResponse = GetPageResponseSuccess | GetPageResponseError;

export const getGetPageUrl = () => {
  return `/message/message`;
};

export const getPage = async (
  pageRequestMessageFilterDtoMessageSortDto: PageRequestMessageFilterDtoMessageSortDto,
  options?: RequestInit,
): Promise<GetPageResponse> => {
  const res = await fetch(getGetPageUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(pageRequestMessageFilterDtoMessageSortDto),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: GetPageResponse["data"] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as GetPageResponse;
};

export type ExportMessagesResponse200 = {
  data: Blob;
  status: 200;
};

export type ExportMessagesResponse400 = {
  data: ErrorResponse;
  status: 400;
};

export type ExportMessagesResponse500 = {
  data: ErrorResponse;
  status: 500;
};

export type ExportMessagesResponseSuccess = ExportMessagesResponse200 & {
  headers: Headers;
};
export type ExportMessagesResponseError = (ExportMessagesResponse400 | ExportMessagesResponse500) & {
  headers: Headers;
};

export type ExportMessagesResponse = ExportMessagesResponseSuccess | ExportMessagesResponseError;

export const getExportMessagesUrl = () => {
  return `/message/message/export`;
};

export const exportMessages = async (
  messageExportDto: MessageExportDto,
  options?: RequestInit,
): Promise<ExportMessagesResponse> => {
  const res = await fetch(getExportMessagesUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(messageExportDto),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: ExportMessagesResponse["data"] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as ExportMessagesResponse;
};

export type GetByIdResponse200 = {
  data: MessageDto;
  status: 200;
};

export type GetByIdResponse400 = {
  data: ErrorResponse;
  status: 400;
};

export type GetByIdResponse404 = {
  data: ErrorResponse;
  status: 404;
};

export type GetByIdResponse500 = {
  data: ErrorResponse;
  status: 500;
};

export type GetByIdResponseSuccess = GetByIdResponse200 & {
  headers: Headers;
};
export type GetByIdResponseError = (GetByIdResponse400 | GetByIdResponse404 | GetByIdResponse500) & {
  headers: Headers;
};

export type GetByIdResponse = GetByIdResponseSuccess | GetByIdResponseError;

export const getGetByIdUrl = (id: Ulid) => {
  return `/message/message/${id}`;
};

export const getById = async (id: Ulid, options?: RequestInit): Promise<GetByIdResponse> => {
  const res = await fetch(getGetByIdUrl(id), {
    ...options,
    method: "GET",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: GetByIdResponse["data"] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as GetByIdResponse;
};
