/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.1
 */
import type {
  CreateTopupCheckoutSessionRequest,
  ErrorResponse,
  PageRequestWalletTransactionFilterDtoWalletTransactionSortDto,
  PageWalletTransactionDto,
  PaymentConfigDto,
  TopupCheckoutSessionDto,
  WalletBalanceDto,
  WalletTransactionFilterDto,
} from "../index.schemas";

export type TelnyxWebhookResponse200 = {
  data: void;
  status: 200;
};

export type TelnyxWebhookResponse400 = {
  data: ErrorResponse;
  status: 400;
};

export type TelnyxWebhookResponse403 = {
  data: ErrorResponse;
  status: 403;
};

export type TelnyxWebhookResponse500 = {
  data: ErrorResponse;
  status: 500;
};

export type TelnyxWebhookResponseSuccess = TelnyxWebhookResponse200 & {
  headers: Headers;
};
export type TelnyxWebhookResponseError = (
  | TelnyxWebhookResponse400
  | TelnyxWebhookResponse403
  | TelnyxWebhookResponse500
) & {
  headers: Headers;
};

export type TelnyxWebhookResponse = TelnyxWebhookResponseSuccess | TelnyxWebhookResponseError;

export const getTelnyxWebhookUrl = () => {
  return `/message-sender/webhooks/telnyx`;
};

export const telnyxWebhook = async (options?: RequestInit): Promise<TelnyxWebhookResponse> => {
  const res = await fetch(getTelnyxWebhookUrl(), {
    ...options,
    method: "POST",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: TelnyxWebhookResponse["data"] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as TelnyxWebhookResponse;
};

export type GetConfigResponse200 = {
  data: PaymentConfigDto;
  status: 200;
};

export type GetConfigResponse500 = {
  data: ErrorResponse;
  status: 500;
};

export type GetConfigResponseSuccess = GetConfigResponse200 & {
  headers: Headers;
};
export type GetConfigResponseError = GetConfigResponse500 & {
  headers: Headers;
};

export type GetConfigResponse = GetConfigResponseSuccess | GetConfigResponseError;

export const getGetConfigUrl = () => {
  return `/payment/config`;
};

export const getConfig = async (options?: RequestInit): Promise<GetConfigResponse> => {
  const res = await fetch(getGetConfigUrl(), {
    ...options,
    method: "GET",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: GetConfigResponse["data"] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as GetConfigResponse;
};

export type StripeWebhookResponse200 = {
  data: void;
  status: 200;
};

export type StripeWebhookResponse400 = {
  data: ErrorResponse;
  status: 400;
};

export type StripeWebhookResponse500 = {
  data: ErrorResponse;
  status: 500;
};

export type StripeWebhookResponseSuccess = StripeWebhookResponse200 & {
  headers: Headers;
};
export type StripeWebhookResponseError = (StripeWebhookResponse400 | StripeWebhookResponse500) & {
  headers: Headers;
};

export type StripeWebhookResponse = StripeWebhookResponseSuccess | StripeWebhookResponseError;

export const getStripeWebhookUrl = () => {
  return `/payment/stripe/webhook`;
};

export const stripeWebhook = async (
  stripeWebhookBody: string,
  options?: RequestInit,
): Promise<StripeWebhookResponse> => {
  const res = await fetch(getStripeWebhookUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "text/plain", ...options?.headers },
    body: stripeWebhookBody,
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: StripeWebhookResponse["data"] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as StripeWebhookResponse;
};

export type CreateCheckoutSessionResponse200 = {
  data: TopupCheckoutSessionDto;
  status: 200;
};

export type CreateCheckoutSessionResponse400 = {
  data: ErrorResponse;
  status: 400;
};

export type CreateCheckoutSessionResponse401 = {
  data: ErrorResponse;
  status: 401;
};

export type CreateCheckoutSessionResponse500 = {
  data: ErrorResponse;
  status: 500;
};

export type CreateCheckoutSessionResponseSuccess = CreateCheckoutSessionResponse200 & {
  headers: Headers;
};
export type CreateCheckoutSessionResponseError = (
  | CreateCheckoutSessionResponse400
  | CreateCheckoutSessionResponse401
  | CreateCheckoutSessionResponse500
) & {
  headers: Headers;
};

export type CreateCheckoutSessionResponse = CreateCheckoutSessionResponseSuccess | CreateCheckoutSessionResponseError;

export const getCreateCheckoutSessionUrl = () => {
  return `/payment/top-up/checkout-session`;
};

export const createCheckoutSession = async (
  createTopupCheckoutSessionRequest: CreateTopupCheckoutSessionRequest,
  options?: RequestInit,
): Promise<CreateCheckoutSessionResponse> => {
  const res = await fetch(getCreateCheckoutSessionUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(createTopupCheckoutSessionRequest),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: CreateCheckoutSessionResponse["data"] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as CreateCheckoutSessionResponse;
};

export type GetBalanceResponse200 = {
  data: WalletBalanceDto;
  status: 200;
};

export type GetBalanceResponse401 = {
  data: ErrorResponse;
  status: 401;
};

export type GetBalanceResponse500 = {
  data: ErrorResponse;
  status: 500;
};

export type GetBalanceResponseSuccess = GetBalanceResponse200 & {
  headers: Headers;
};
export type GetBalanceResponseError = (GetBalanceResponse401 | GetBalanceResponse500) & {
  headers: Headers;
};

export type GetBalanceResponse = GetBalanceResponseSuccess | GetBalanceResponseError;

export const getGetBalanceUrl = () => {
  return `/payment/wallet/balance`;
};

export const getBalance = async (options?: RequestInit): Promise<GetBalanceResponse> => {
  const res = await fetch(getGetBalanceUrl(), {
    ...options,
    method: "GET",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: GetBalanceResponse["data"] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as GetBalanceResponse;
};

export type CountTransactionsResponse200 = {
  data: number;
  status: 200;
};

export type CountTransactionsResponse401 = {
  data: ErrorResponse;
  status: 401;
};

export type CountTransactionsResponse500 = {
  data: ErrorResponse;
  status: 500;
};

export type CountTransactionsResponseSuccess = CountTransactionsResponse200 & {
  headers: Headers;
};
export type CountTransactionsResponseError = (CountTransactionsResponse401 | CountTransactionsResponse500) & {
  headers: Headers;
};

export type CountTransactionsResponse = CountTransactionsResponseSuccess | CountTransactionsResponseError;

export const getCountTransactionsUrl = () => {
  return `/payment/wallet/transactions/count`;
};

export const countTransactions = async (
  walletTransactionFilterDto: WalletTransactionFilterDto,
  options?: RequestInit,
): Promise<CountTransactionsResponse> => {
  const res = await fetch(getCountTransactionsUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(walletTransactionFilterDto),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: CountTransactionsResponse["data"] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as CountTransactionsResponse;
};

export type ListTransactionsResponse200 = {
  data: PageWalletTransactionDto;
  status: 200;
};

export type ListTransactionsResponse401 = {
  data: ErrorResponse;
  status: 401;
};

export type ListTransactionsResponse500 = {
  data: ErrorResponse;
  status: 500;
};

export type ListTransactionsResponseSuccess = ListTransactionsResponse200 & {
  headers: Headers;
};
export type ListTransactionsResponseError = (ListTransactionsResponse401 | ListTransactionsResponse500) & {
  headers: Headers;
};

export type ListTransactionsResponse = ListTransactionsResponseSuccess | ListTransactionsResponseError;

export const getListTransactionsUrl = () => {
  return `/payment/wallet/transactions/fetch`;
};

export const listTransactions = async (
  pageRequestWalletTransactionFilterDtoWalletTransactionSortDto: PageRequestWalletTransactionFilterDtoWalletTransactionSortDto,
  options?: RequestInit,
): Promise<ListTransactionsResponse> => {
  const res = await fetch(getListTransactionsUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(pageRequestWalletTransactionFilterDtoWalletTransactionSortDto),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: ListTransactionsResponse["data"] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as ListTransactionsResponse;
};
