query ContactExportContactsQuery(
  $after: String
  $before: String
  $filter: ContactFilterInput
  $first: Int
  $last: Int
  $offset: Int
  $sortBy: [ContactSortByInput!]! = []
) @cache(policy: NetworkOnly) {
  contacts(
    after: $after
    before: $before
    filter: $filter
    first: $first
    last: $last
    offset: $offset
    sortBy: $sortBy
  ) {
    edges {
      node {
        birthday
        contactGroups {
          id
        }
        email
        firstName
        id
        lastName
        notes
        phoneNumber
      }
    }
    pageInfo {
      endCursor
      hasNextPage
      hasPreviousPage
      startCursor
    }
    totalCount
  }
}
