query Campaigns($after: String, $filter: CampaignFilterInput, $first: Int, $sortBy: [CampaignSortInput!]! = [])
@cache(policy: NetworkOnly) {
  campaigns(after: $after, filter: $filter, first: $first, sortBy: $sortBy) {
    edges {
      node {
        contactGroups {
          id
          name
        }
        id
        messageCount
        messageTemplate
        name
        sentMessageCount
        status
      }
    }
    pageInfo {
      endCursor
      hasNextPage
    }
    totalCount
  }
}
