/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * utoipa-axum
 * Utoipa's axum bindings for seamless integration for the two
 * OpenAPI spec version: 0.2.0
 */
import type { ErrorResponse, IdDto, TenDlcCampaignCreateDto, TenDlcCampaignDto, Ulid } from "../index.schemas";

export type ListTenDlcCampaignsResponse200 = {
  data: TenDlcCampaignDto[];
  status: 200;
};

export type ListTenDlcCampaignsResponse500 = {
  data: ErrorResponse;
  status: 500;
};

export type ListTenDlcCampaignsResponseSuccess = ListTenDlcCampaignsResponse200 & {
  headers: Headers;
};
export type ListTenDlcCampaignsResponseError = ListTenDlcCampaignsResponse500 & {
  headers: Headers;
};

export type ListTenDlcCampaignsResponse = ListTenDlcCampaignsResponseSuccess | ListTenDlcCampaignsResponseError;

export const getListTenDlcCampaignsUrl = () => {
  return `/phone/ten-dlc-campaign`;
};

export const listTenDlcCampaigns = async (options?: RequestInit): Promise<ListTenDlcCampaignsResponse> => {
  const res = await fetch(getListTenDlcCampaignsUrl(), {
    ...options,
    method: "GET",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: ListTenDlcCampaignsResponse["data"] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as ListTenDlcCampaignsResponse;
};

export type CreateTenDlcCampaignResponse200 = {
  data: IdDto;
  status: 200;
};

export type CreateTenDlcCampaignResponse400 = {
  data: ErrorResponse;
  status: 400;
};

export type CreateTenDlcCampaignResponse500 = {
  data: ErrorResponse;
  status: 500;
};

export type CreateTenDlcCampaignResponseSuccess = CreateTenDlcCampaignResponse200 & {
  headers: Headers;
};
export type CreateTenDlcCampaignResponseError = (CreateTenDlcCampaignResponse400 | CreateTenDlcCampaignResponse500) & {
  headers: Headers;
};

export type CreateTenDlcCampaignResponse = CreateTenDlcCampaignResponseSuccess | CreateTenDlcCampaignResponseError;

export const getCreateTenDlcCampaignUrl = () => {
  return `/phone/ten-dlc-campaign`;
};

export const createTenDlcCampaign = async (
  tenDlcCampaignCreateDto: TenDlcCampaignCreateDto,
  options?: RequestInit,
): Promise<CreateTenDlcCampaignResponse> => {
  const res = await fetch(getCreateTenDlcCampaignUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(tenDlcCampaignCreateDto),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: CreateTenDlcCampaignResponse["data"] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as CreateTenDlcCampaignResponse;
};

export type GetTenDlcCampaignResponse200 = {
  data: TenDlcCampaignDto;
  status: 200;
};

export type GetTenDlcCampaignResponse404 = {
  data: ErrorResponse;
  status: 404;
};

export type GetTenDlcCampaignResponse500 = {
  data: ErrorResponse;
  status: 500;
};

export type GetTenDlcCampaignResponseSuccess = GetTenDlcCampaignResponse200 & {
  headers: Headers;
};
export type GetTenDlcCampaignResponseError = (GetTenDlcCampaignResponse404 | GetTenDlcCampaignResponse500) & {
  headers: Headers;
};

export type GetTenDlcCampaignResponse = GetTenDlcCampaignResponseSuccess | GetTenDlcCampaignResponseError;

export const getGetTenDlcCampaignUrl = (id: Ulid) => {
  return `/phone/ten-dlc-campaign/${id}`;
};

export const getTenDlcCampaign = async (id: Ulid, options?: RequestInit): Promise<GetTenDlcCampaignResponse> => {
  const res = await fetch(getGetTenDlcCampaignUrl(id), {
    ...options,
    method: "GET",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: GetTenDlcCampaignResponse["data"] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as GetTenDlcCampaignResponse;
};

export type DeleteTenDlcCampaignResponse200 = {
  data: void;
  status: 200;
};

export type DeleteTenDlcCampaignResponse404 = {
  data: ErrorResponse;
  status: 404;
};

export type DeleteTenDlcCampaignResponse500 = {
  data: ErrorResponse;
  status: 500;
};

export type DeleteTenDlcCampaignResponseSuccess = DeleteTenDlcCampaignResponse200 & {
  headers: Headers;
};
export type DeleteTenDlcCampaignResponseError = (DeleteTenDlcCampaignResponse404 | DeleteTenDlcCampaignResponse500) & {
  headers: Headers;
};

export type DeleteTenDlcCampaignResponse = DeleteTenDlcCampaignResponseSuccess | DeleteTenDlcCampaignResponseError;

export const getDeleteTenDlcCampaignUrl = (id: Ulid) => {
  return `/phone/ten-dlc-campaign/${id}`;
};

export const deleteTenDlcCampaign = async (id: Ulid, options?: RequestInit): Promise<DeleteTenDlcCampaignResponse> => {
  const res = await fetch(getDeleteTenDlcCampaignUrl(id), {
    ...options,
    method: "DELETE",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: DeleteTenDlcCampaignResponse["data"] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as DeleteTenDlcCampaignResponse;
};
