/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { ErrorResponseDto, IdDto, TenDlcCampaignCreateDto, TenDlcCampaignDto } from "../index.schemas";

export type GetTenDlcCampaignPageResponse200 = {
  data: TenDlcCampaignDto[];
  status: 200;
};

export type GetTenDlcCampaignPageResponse400 = {
  data: ErrorResponseDto;
  status: 400;
};

export type GetTenDlcCampaignPageResponse401 = {
  data: ErrorResponseDto;
  status: 401;
};

export type GetTenDlcCampaignPageResponse404 = {
  data: ErrorResponseDto;
  status: 404;
};

export type GetTenDlcCampaignPageResponse500 = {
  data: ErrorResponseDto;
  status: 500;
};

export type GetTenDlcCampaignPageResponseSuccess = GetTenDlcCampaignPageResponse200 & {
  headers: Headers;
};
export type GetTenDlcCampaignPageResponseError = (
  | GetTenDlcCampaignPageResponse400
  | GetTenDlcCampaignPageResponse401
  | GetTenDlcCampaignPageResponse404
  | GetTenDlcCampaignPageResponse500
) & {
  headers: Headers;
};

export type GetTenDlcCampaignPageResponse = GetTenDlcCampaignPageResponseSuccess | GetTenDlcCampaignPageResponseError;

export const getGetTenDlcCampaignPageUrl = () => {
  return `/phone/ten-dlc-campaign`;
};

export const getTenDlcCampaignPage = async (options?: RequestInit): Promise<GetTenDlcCampaignPageResponse> => {
  const res = await fetch(getGetTenDlcCampaignPageUrl(), {
    ...options,
    method: "GET",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: GetTenDlcCampaignPageResponse["data"] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as GetTenDlcCampaignPageResponse;
};

export type CreateTenDlcCampaignResponse200 = {
  data: IdDto;
  status: 200;
};

export type CreateTenDlcCampaignResponse400 = {
  data: ErrorResponseDto;
  status: 400;
};

export type CreateTenDlcCampaignResponse401 = {
  data: ErrorResponseDto;
  status: 401;
};

export type CreateTenDlcCampaignResponse404 = {
  data: ErrorResponseDto;
  status: 404;
};

export type CreateTenDlcCampaignResponse500 = {
  data: ErrorResponseDto;
  status: 500;
};

export type CreateTenDlcCampaignResponseSuccess = CreateTenDlcCampaignResponse200 & {
  headers: Headers;
};
export type CreateTenDlcCampaignResponseError = (
  | CreateTenDlcCampaignResponse400
  | CreateTenDlcCampaignResponse401
  | CreateTenDlcCampaignResponse404
  | CreateTenDlcCampaignResponse500
) & {
  headers: Headers;
};

export type CreateTenDlcCampaignResponse = CreateTenDlcCampaignResponseSuccess | CreateTenDlcCampaignResponseError;

export const getCreateTenDlcCampaignUrl = () => {
  return `/phone/ten-dlc-campaign`;
};

export const createTenDlcCampaign = async (
  tenDlcCampaignCreateDto: TenDlcCampaignCreateDto,
  options?: RequestInit,
): Promise<CreateTenDlcCampaignResponse> => {
  const res = await fetch(getCreateTenDlcCampaignUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(tenDlcCampaignCreateDto),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: CreateTenDlcCampaignResponse["data"] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as CreateTenDlcCampaignResponse;
};

export type GetTenDlcCampaignByIdResponse200 = {
  data: TenDlcCampaignDto;
  status: 200;
};

export type GetTenDlcCampaignByIdResponse400 = {
  data: ErrorResponseDto;
  status: 400;
};

export type GetTenDlcCampaignByIdResponse401 = {
  data: ErrorResponseDto;
  status: 401;
};

export type GetTenDlcCampaignByIdResponse404 = {
  data: ErrorResponseDto;
  status: 404;
};

export type GetTenDlcCampaignByIdResponse500 = {
  data: ErrorResponseDto;
  status: 500;
};

export type GetTenDlcCampaignByIdResponseSuccess = GetTenDlcCampaignByIdResponse200 & {
  headers: Headers;
};
export type GetTenDlcCampaignByIdResponseError = (
  | GetTenDlcCampaignByIdResponse400
  | GetTenDlcCampaignByIdResponse401
  | GetTenDlcCampaignByIdResponse404
  | GetTenDlcCampaignByIdResponse500
) & {
  headers: Headers;
};

export type GetTenDlcCampaignByIdResponse = GetTenDlcCampaignByIdResponseSuccess | GetTenDlcCampaignByIdResponseError;

export const getGetTenDlcCampaignByIdUrl = (id: string) => {
  return `/phone/ten-dlc-campaign/${id}`;
};

export const getTenDlcCampaignById = async (
  id: string,
  options?: RequestInit,
): Promise<GetTenDlcCampaignByIdResponse> => {
  const res = await fetch(getGetTenDlcCampaignByIdUrl(id), {
    ...options,
    method: "GET",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: GetTenDlcCampaignByIdResponse["data"] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as GetTenDlcCampaignByIdResponse;
};

export type DeleteTenDlcCampaignResponse200 = {
  data: void;
  status: 200;
};

export type DeleteTenDlcCampaignResponse400 = {
  data: ErrorResponseDto;
  status: 400;
};

export type DeleteTenDlcCampaignResponse401 = {
  data: ErrorResponseDto;
  status: 401;
};

export type DeleteTenDlcCampaignResponse404 = {
  data: ErrorResponseDto;
  status: 404;
};

export type DeleteTenDlcCampaignResponse500 = {
  data: ErrorResponseDto;
  status: 500;
};

export type DeleteTenDlcCampaignResponseSuccess = DeleteTenDlcCampaignResponse200 & {
  headers: Headers;
};
export type DeleteTenDlcCampaignResponseError = (
  | DeleteTenDlcCampaignResponse400
  | DeleteTenDlcCampaignResponse401
  | DeleteTenDlcCampaignResponse404
  | DeleteTenDlcCampaignResponse500
) & {
  headers: Headers;
};

export type DeleteTenDlcCampaignResponse = DeleteTenDlcCampaignResponseSuccess | DeleteTenDlcCampaignResponseError;

export const getDeleteTenDlcCampaignUrl = (id: string) => {
  return `/phone/ten-dlc-campaign/${id}`;
};

export const deleteTenDlcCampaign = async (
  id: string,
  options?: RequestInit,
): Promise<DeleteTenDlcCampaignResponse> => {
  const res = await fetch(getDeleteTenDlcCampaignUrl(id), {
    ...options,
    method: "DELETE",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: DeleteTenDlcCampaignResponse["data"] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as DeleteTenDlcCampaignResponse;
};
