/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type {
  ErrorResponseDto,
  IdDto,
  TenDlcCampaignCreateDto,
  TenDlcCampaignDto
} from '../index.schemas';


export type getTenDlcCampaignPageResponse200 = {
  data: TenDlcCampaignDto[]
  status: 200
}

export type getTenDlcCampaignPageResponse400 = {
  data: ErrorResponseDto
  status: 400
}

export type getTenDlcCampaignPageResponse401 = {
  data: ErrorResponseDto
  status: 401
}

export type getTenDlcCampaignPageResponse404 = {
  data: ErrorResponseDto
  status: 404
}

export type getTenDlcCampaignPageResponse500 = {
  data: ErrorResponseDto
  status: 500
}

export type getTenDlcCampaignPageResponseSuccess = (getTenDlcCampaignPageResponse200) & {
  headers: Headers;
};
export type getTenDlcCampaignPageResponseError = (getTenDlcCampaignPageResponse400 | getTenDlcCampaignPageResponse401 | getTenDlcCampaignPageResponse404 | getTenDlcCampaignPageResponse500) & {
  headers: Headers;
};

export type getTenDlcCampaignPageResponse = (getTenDlcCampaignPageResponseSuccess | getTenDlcCampaignPageResponseError)

export const getGetTenDlcCampaignPageUrl = () => {


  

  return `/phone/ten-dlc-campaign`
}

export const getTenDlcCampaignPage = async ( options?: RequestInit): Promise<getTenDlcCampaignPageResponse> => {
  
  const res = await fetch(getGetTenDlcCampaignPageUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getTenDlcCampaignPageResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getTenDlcCampaignPageResponse
}
  

export type createTenDlcCampaignResponse200 = {
  data: IdDto
  status: 200
}

export type createTenDlcCampaignResponse400 = {
  data: ErrorResponseDto
  status: 400
}

export type createTenDlcCampaignResponse401 = {
  data: ErrorResponseDto
  status: 401
}

export type createTenDlcCampaignResponse404 = {
  data: ErrorResponseDto
  status: 404
}

export type createTenDlcCampaignResponse500 = {
  data: ErrorResponseDto
  status: 500
}

export type createTenDlcCampaignResponseSuccess = (createTenDlcCampaignResponse200) & {
  headers: Headers;
};
export type createTenDlcCampaignResponseError = (createTenDlcCampaignResponse400 | createTenDlcCampaignResponse401 | createTenDlcCampaignResponse404 | createTenDlcCampaignResponse500) & {
  headers: Headers;
};

export type createTenDlcCampaignResponse = (createTenDlcCampaignResponseSuccess | createTenDlcCampaignResponseError)

export const getCreateTenDlcCampaignUrl = () => {


  

  return `/phone/ten-dlc-campaign`
}

export const createTenDlcCampaign = async (tenDlcCampaignCreateDto: TenDlcCampaignCreateDto, options?: RequestInit): Promise<createTenDlcCampaignResponse> => {
  
  const res = await fetch(getCreateTenDlcCampaignUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      tenDlcCampaignCreateDto,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: createTenDlcCampaignResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as createTenDlcCampaignResponse
}
  

export type getTenDlcCampaignByIdResponse200 = {
  data: TenDlcCampaignDto
  status: 200
}

export type getTenDlcCampaignByIdResponse400 = {
  data: ErrorResponseDto
  status: 400
}

export type getTenDlcCampaignByIdResponse401 = {
  data: ErrorResponseDto
  status: 401
}

export type getTenDlcCampaignByIdResponse404 = {
  data: ErrorResponseDto
  status: 404
}

export type getTenDlcCampaignByIdResponse500 = {
  data: ErrorResponseDto
  status: 500
}

export type getTenDlcCampaignByIdResponseSuccess = (getTenDlcCampaignByIdResponse200) & {
  headers: Headers;
};
export type getTenDlcCampaignByIdResponseError = (getTenDlcCampaignByIdResponse400 | getTenDlcCampaignByIdResponse401 | getTenDlcCampaignByIdResponse404 | getTenDlcCampaignByIdResponse500) & {
  headers: Headers;
};

export type getTenDlcCampaignByIdResponse = (getTenDlcCampaignByIdResponseSuccess | getTenDlcCampaignByIdResponseError)

export const getGetTenDlcCampaignByIdUrl = (id: string,) => {


  

  return `/phone/ten-dlc-campaign/${id}`
}

export const getTenDlcCampaignById = async (id: string, options?: RequestInit): Promise<getTenDlcCampaignByIdResponse> => {
  
  const res = await fetch(getGetTenDlcCampaignByIdUrl(id),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getTenDlcCampaignByIdResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getTenDlcCampaignByIdResponse
}
  

export type deleteTenDlcCampaignResponse200 = {
  data: void
  status: 200
}

export type deleteTenDlcCampaignResponse400 = {
  data: ErrorResponseDto
  status: 400
}

export type deleteTenDlcCampaignResponse401 = {
  data: ErrorResponseDto
  status: 401
}

export type deleteTenDlcCampaignResponse404 = {
  data: ErrorResponseDto
  status: 404
}

export type deleteTenDlcCampaignResponse500 = {
  data: ErrorResponseDto
  status: 500
}

export type deleteTenDlcCampaignResponseSuccess = (deleteTenDlcCampaignResponse200) & {
  headers: Headers;
};
export type deleteTenDlcCampaignResponseError = (deleteTenDlcCampaignResponse400 | deleteTenDlcCampaignResponse401 | deleteTenDlcCampaignResponse404 | deleteTenDlcCampaignResponse500) & {
  headers: Headers;
};

export type deleteTenDlcCampaignResponse = (deleteTenDlcCampaignResponseSuccess | deleteTenDlcCampaignResponseError)

export const getDeleteTenDlcCampaignUrl = (id: string,) => {


  

  return `/phone/ten-dlc-campaign/${id}`
}

export const deleteTenDlcCampaign = async (id: string, options?: RequestInit): Promise<deleteTenDlcCampaignResponse> => {
  
  const res = await fetch(getDeleteTenDlcCampaignUrl(id),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: deleteTenDlcCampaignResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as deleteTenDlcCampaignResponse
}
  

