// Generated by filesystem-routing. Do not edit.
// Regenerated whenever a route file is added, changed or removed.

declare module "virtual:file-routes" {
  /** A code-split ref: the delivery adapter emits it as a dynamic import. */
  export interface FileRouteLazyRef<M = Record<string, unknown>> {
    src: string;
    import(): Promise<M>;
  }

  /** An eager ref: its picked exports are imported statically. */
  export interface FileRouteEagerRef<M = Record<string, unknown>> {
    /** The source module path — present when the convention emitted the ref lazy and `codeSplitting: false` delivered it eagerly. */
    src?: string;
    require(): M;
  }

  /** A flat entry of the route manifest. */
  export interface FileRouteEntry {
    path: string;
    page?: boolean;
    $component?: FileRouteLazyRef<any> | FileRouteEagerRef<any>;
    $$route?: FileRouteEagerRef<any>;
    [key: string]: unknown;
  }

  /** An entry of the nested `pageRoutes` view. */
  export interface FileRouteTreeEntry extends FileRouteEntry {
    id: string;
    children?: readonly FileRouteTreeEntry[];
  }

  /** The flat route manifest, in scan order. */
  const routes: readonly [
    {
      path: "/";
      page: true;
      $component: FileRouteLazyRef<typeof import("./routes/+page")>;
      $$route?: undefined;
    },
    {
      path: "/(app)";
      page: true;
      $component: FileRouteLazyRef<typeof import("./routes/(app)/+layout")>;
      $$route?: undefined;
    },
    {
      path: "/*path";
      page: true;
      $component: FileRouteLazyRef<typeof import("./routes/[...path]/+page")>;
      $$route?: undefined;
    },
    {
      path: "/account-closed/";
      page: true;
      $component: FileRouteLazyRef<typeof import("./routes/account-closed/+page")>;
      $$route?: undefined;
    },
    {
      path: "/account-suspended/";
      page: true;
      $component: FileRouteLazyRef<typeof import("./routes/account-suspended/+page")>;
      $$route?: undefined;
    },
    {
      path: "/account-unavailable/";
      page: true;
      $component: FileRouteLazyRef<typeof import("./routes/account-unavailable/+page")>;
      $$route?: undefined;
    },
    {
      path: "/reset-password/";
      page: true;
      $component: FileRouteLazyRef<typeof import("./routes/reset-password/+page")>;
      $$route?: undefined;
    },
    {
      path: "/sign-in/";
      page: true;
      $component: FileRouteLazyRef<typeof import("./routes/sign-in/+page")>;
      $$route?: undefined;
    },
    {
      path: "/sign-up/";
      page: true;
      $component: FileRouteLazyRef<typeof import("./routes/sign-up/+page")>;
      $$route?: undefined;
    },
    {
      path: "/trial-expired/";
      page: true;
      $component: FileRouteLazyRef<typeof import("./routes/trial-expired/+page")>;
      $$route?: undefined;
    },
    {
      path: "/(app)/business/";
      page: true;
      $component: FileRouteLazyRef<typeof import("./routes/(app)/business/+page")>;
      $$route?: undefined;
    },
    {
      path: "/(app)/campaign/";
      page: true;
      $component: FileRouteLazyRef<typeof import("./routes/(app)/campaign/+page")>;
      $$route?: undefined;
    },
    {
      path: "/(app)/conversation/";
      page: true;
      $component: FileRouteLazyRef<typeof import("./routes/(app)/conversation/+page")>;
      $$route?: undefined;
    },
    {
      path: "/(app)/dashboard/";
      page: true;
      $component: FileRouteLazyRef<typeof import("./routes/(app)/dashboard/+page")>;
      $$route?: undefined;
    },
    {
      path: "/(app)/payment/";
      page: true;
      $component: FileRouteLazyRef<typeof import("./routes/(app)/payment/+page")>;
      $$route?: undefined;
    },
    {
      path: "/(app)/phone/";
      page: true;
      $component: FileRouteLazyRef<typeof import("./routes/(app)/phone/+page")>;
      $$route?: undefined;
    },
    {
      path: "/(app)/profile/";
      page: true;
      $component: FileRouteLazyRef<typeof import("./routes/(app)/profile/+page")>;
      $$route?: undefined;
    },
    {
      path: "/(app)/smart-group/";
      page: true;
      $component: FileRouteLazyRef<typeof import("./routes/(app)/smart-group/+page")>;
      $$route?: undefined;
    },
    {
      path: "/(app)/upgrade/";
      page: true;
      $component: FileRouteLazyRef<typeof import("./routes/(app)/upgrade/+page")>;
      $$route?: undefined;
    },
    {
      path: "/(app)/business/edit/";
      page: true;
      $component: FileRouteLazyRef<typeof import("./routes/(app)/business/edit/+page")>;
      $$route?: undefined;
    },
    {
      path: "/(app)/contact/(list)/";
      page: true;
      $component: FileRouteLazyRef<typeof import("./routes/(app)/contact/(list)/+page")>;
      $$route?: undefined;
    },
    {
      path: "/(app)/contact-group/(list)/";
      page: true;
      $component: FileRouteLazyRef<typeof import("./routes/(app)/contact-group/(list)/+page")>;
      $$route?: undefined;
    },
    {
      path: "/(app)/custom-field/(list)/";
      page: true;
      $component: FileRouteLazyRef<typeof import("./routes/(app)/custom-field/(list)/+page")>;
      $$route?: undefined;
    },
    {
      path: "/(app)/payment/top-up/";
      page: true;
      $component: FileRouteLazyRef<typeof import("./routes/(app)/payment/top-up/+page")>;
      $$route?: undefined;
    },
    {
      path: "/(app)/payment/transaction/";
      page: true;
      $component: FileRouteLazyRef<typeof import("./routes/(app)/payment/transaction/+page")>;
      $$route?: undefined;
    },
    {
      path: "/(app)/phone/10dlc/";
      page: true;
      $component: FileRouteLazyRef<typeof import("./routes/(app)/phone/10dlc/+page")>;
      $$route?: undefined;
    },
    {
      path: "/(app)/phone/buy/";
      page: true;
      $component: FileRouteLazyRef<typeof import("./routes/(app)/phone/buy/+page")>;
      $$route?: undefined;
    },
    {
      path: "/(app)/user/(list)/";
      page: true;
      $component: FileRouteLazyRef<typeof import("./routes/(app)/user/(list)/+page")>;
      $$route?: undefined;
    },
    {
      path: "/(app)/campaign/:id/messages/";
      page: true;
      $component: FileRouteLazyRef<typeof import("./routes/(app)/campaign/[id]/messages/+page")>;
      $$route?: undefined;
    },
    {
      path: "/(app)/contact/export/history/";
      page: true;
      $component: FileRouteLazyRef<typeof import("./routes/(app)/contact/export/history/+page")>;
      $$route?: undefined;
    },
    {
      path: "/(app)/contact/import/history/";
      page: true;
      $component: FileRouteLazyRef<typeof import("./routes/(app)/contact/import/history/+page")>;
      $$route?: undefined;
    },
    {
      path: "/(app)/contact/import/upload/";
      page: true;
      $component: FileRouteLazyRef<typeof import("./routes/(app)/contact/import/upload/+page")>;
      $$route?: undefined;
    },
    {
      path: "/(app)/phone/10dlc/brand/";
      page: true;
      $component: FileRouteLazyRef<typeof import("./routes/(app)/phone/10dlc/brand/+page")>;
      $$route?: undefined;
    },
    {
      path: "/(app)/campaign/(form)/(routes)/add/";
      page: true;
      $component: FileRouteLazyRef<typeof import("./routes/(app)/campaign/(form)/(routes)/add/+page")>;
      $$route?: undefined;
    },
    {
      path: "/(app)/contact/(form)/(routes)/add/";
      page: true;
      $component: FileRouteLazyRef<typeof import("./routes/(app)/contact/(form)/(routes)/add/+page")>;
      $$route?: undefined;
    },
    {
      path: "/(app)/contact-group/(form)/(routes)/add/";
      page: true;
      $component: FileRouteLazyRef<typeof import("./routes/(app)/contact-group/(form)/(routes)/add/+page")>;
      $$route?: undefined;
    },
    {
      path: "/(app)/custom-field/(form)/(routes)/add/";
      page: true;
      $component: FileRouteLazyRef<typeof import("./routes/(app)/custom-field/(form)/(routes)/add/+page")>;
      $$route?: undefined;
    },
    {
      path: "/(app)/user/(form)/(routes)/add/";
      page: true;
      $component: FileRouteLazyRef<typeof import("./routes/(app)/user/(form)/(routes)/add/+page")>;
      $$route?: undefined;
    },
    {
      path: "/(app)/contact/(form)/(routes)/:id/edit/";
      page: true;
      $component: FileRouteLazyRef<typeof import("./routes/(app)/contact/(form)/(routes)/[id]/edit/+page")>;
      $$route?: undefined;
    },
    {
      path: "/(app)/contact-group/(form)/(routes)/:id/edit/";
      page: true;
      $component: FileRouteLazyRef<typeof import("./routes/(app)/contact-group/(form)/(routes)/[id]/edit/+page")>;
      $$route?: undefined;
    },
    {
      path: "/(app)/custom-field/(form)/(routes)/:id/edit/";
      page: true;
      $component: FileRouteLazyRef<typeof import("./routes/(app)/custom-field/(form)/(routes)/[id]/edit/+page")>;
      $$route?: undefined;
    },
    {
      path: "/(app)/user/(form)/(routes)/:id/edit/";
      page: true;
      $component: FileRouteLazyRef<typeof import("./routes/(app)/user/(form)/(routes)/[id]/edit/+page")>;
      $$route?: undefined;
    },
    {
      path: "/(app)/phone/10dlc/campaign/(form)/(routes)/add/";
      page: true;
      $component: FileRouteLazyRef<typeof import("./routes/(app)/phone/10dlc/campaign/(form)/(routes)/add/+page")>;
      $$route?: undefined;
    }
  ];
  export default routes;

  /** The page entries, nested by path with grouping segments stripped. */
  export const pageRoutes: readonly [
    {
      path: "/";
      id: "/";
      page: true;
      $component: FileRouteLazyRef<typeof import("./routes/+page")>;
      $$route?: undefined;
      children?: undefined;
    },
    {
      path: "/";
      id: "/(app)";
      page: true;
      $component: FileRouteLazyRef<typeof import("./routes/(app)/+layout")>;
      $$route?: undefined;
      children: readonly [
        {
          path: "/phone/";
          id: "/phone/";
          page: true;
          $component: FileRouteLazyRef<typeof import("./routes/(app)/phone/+page")>;
          $$route?: undefined;
          children?: undefined;
        },
        {
          path: "/payment/";
          id: "/payment/";
          page: true;
          $component: FileRouteLazyRef<typeof import("./routes/(app)/payment/+page")>;
          $$route?: undefined;
          children?: undefined;
        },
        {
          path: "/profile/";
          id: "/profile/";
          page: true;
          $component: FileRouteLazyRef<typeof import("./routes/(app)/profile/+page")>;
          $$route?: undefined;
          children?: undefined;
        },
        {
          path: "/upgrade/";
          id: "/upgrade/";
          page: true;
          $component: FileRouteLazyRef<typeof import("./routes/(app)/upgrade/+page")>;
          $$route?: undefined;
          children?: undefined;
        },
        {
          path: "/business/";
          id: "/business/";
          page: true;
          $component: FileRouteLazyRef<typeof import("./routes/(app)/business/+page")>;
          $$route?: undefined;
          children?: undefined;
        },
        {
          path: "/campaign/";
          id: "/campaign/";
          page: true;
          $component: FileRouteLazyRef<typeof import("./routes/(app)/campaign/+page")>;
          $$route?: undefined;
          children?: undefined;
        },
        {
          path: "/dashboard/";
          id: "/dashboard/";
          page: true;
          $component: FileRouteLazyRef<typeof import("./routes/(app)/dashboard/+page")>;
          $$route?: undefined;
          children?: undefined;
        },
        {
          path: "/phone/buy/";
          id: "/phone/buy/";
          page: true;
          $component: FileRouteLazyRef<typeof import("./routes/(app)/phone/buy/+page")>;
          $$route?: undefined;
          children?: undefined;
        },
        {
          path: "/smart-group/";
          id: "/smart-group/";
          page: true;
          $component: FileRouteLazyRef<typeof import("./routes/(app)/smart-group/+page")>;
          $$route?: undefined;
          children?: undefined;
        },
        {
          path: "/phone/10dlc/";
          id: "/phone/10dlc/";
          page: true;
          $component: FileRouteLazyRef<typeof import("./routes/(app)/phone/10dlc/+page")>;
          $$route?: undefined;
          children?: undefined;
        },
        {
          path: "/user/";
          id: "/user/(list)/";
          page: true;
          $component: FileRouteLazyRef<typeof import("./routes/(app)/user/(list)/+page")>;
          $$route?: undefined;
          children?: undefined;
        },
        {
          path: "/conversation/";
          id: "/conversation/";
          page: true;
          $component: FileRouteLazyRef<typeof import("./routes/(app)/conversation/+page")>;
          $$route?: undefined;
          children?: undefined;
        },
        {
          path: "/business/edit/";
          id: "/business/edit/";
          page: true;
          $component: FileRouteLazyRef<typeof import("./routes/(app)/business/edit/+page")>;
          $$route?: undefined;
          children?: undefined;
        },
        {
          path: "/contact/";
          id: "/contact/(list)/";
          page: true;
          $component: FileRouteLazyRef<typeof import("./routes/(app)/contact/(list)/+page")>;
          $$route?: undefined;
          children?: undefined;
        },
        {
          path: "/payment/top-up/";
          id: "/payment/top-up/";
          page: true;
          $component: FileRouteLazyRef<typeof import("./routes/(app)/payment/top-up/+page")>;
          $$route?: undefined;
          children?: undefined;
        },
        {
          path: "/phone/10dlc/brand/";
          id: "/phone/10dlc/brand/";
          page: true;
          $component: FileRouteLazyRef<typeof import("./routes/(app)/phone/10dlc/brand/+page")>;
          $$route?: undefined;
          children?: undefined;
        },
        {
          path: "/custom-field/";
          id: "/custom-field/(list)/";
          page: true;
          $component: FileRouteLazyRef<typeof import("./routes/(app)/custom-field/(list)/+page")>;
          $$route?: undefined;
          children?: undefined;
        },
        {
          path: "/payment/transaction/";
          id: "/payment/transaction/";
          page: true;
          $component: FileRouteLazyRef<typeof import("./routes/(app)/payment/transaction/+page")>;
          $$route?: undefined;
          children?: undefined;
        },
        {
          path: "/contact-group/";
          id: "/contact-group/(list)/";
          page: true;
          $component: FileRouteLazyRef<typeof import("./routes/(app)/contact-group/(list)/+page")>;
          $$route?: undefined;
          children?: undefined;
        },
        {
          path: "/campaign/:id/messages/";
          id: "/campaign/:id/messages/";
          page: true;
          $component: FileRouteLazyRef<typeof import("./routes/(app)/campaign/[id]/messages/+page")>;
          $$route?: undefined;
          children?: undefined;
        },
        {
          path: "/contact/import/upload/";
          id: "/contact/import/upload/";
          page: true;
          $component: FileRouteLazyRef<typeof import("./routes/(app)/contact/import/upload/+page")>;
          $$route?: undefined;
          children?: undefined;
        },
        {
          path: "/contact/export/history/";
          id: "/contact/export/history/";
          page: true;
          $component: FileRouteLazyRef<typeof import("./routes/(app)/contact/export/history/+page")>;
          $$route?: undefined;
          children?: undefined;
        },
        {
          path: "/contact/import/history/";
          id: "/contact/import/history/";
          page: true;
          $component: FileRouteLazyRef<typeof import("./routes/(app)/contact/import/history/+page")>;
          $$route?: undefined;
          children?: undefined;
        },
        {
          path: "/user/add/";
          id: "/user/(form)/(routes)/add/";
          page: true;
          $component: FileRouteLazyRef<typeof import("./routes/(app)/user/(form)/(routes)/add/+page")>;
          $$route?: undefined;
          children?: undefined;
        },
        {
          path: "/contact/add/";
          id: "/contact/(form)/(routes)/add/";
          page: true;
          $component: FileRouteLazyRef<typeof import("./routes/(app)/contact/(form)/(routes)/add/+page")>;
          $$route?: undefined;
          children?: undefined;
        },
        {
          path: "/campaign/add/";
          id: "/campaign/(form)/(routes)/add/";
          page: true;
          $component: FileRouteLazyRef<typeof import("./routes/(app)/campaign/(form)/(routes)/add/+page")>;
          $$route?: undefined;
          children?: undefined;
        },
        {
          path: "/user/:id/edit/";
          id: "/user/(form)/(routes)/:id/edit/";
          page: true;
          $component: FileRouteLazyRef<typeof import("./routes/(app)/user/(form)/(routes)/[id]/edit/+page")>;
          $$route?: undefined;
          children?: undefined;
        },
        {
          path: "/custom-field/add/";
          id: "/custom-field/(form)/(routes)/add/";
          page: true;
          $component: FileRouteLazyRef<typeof import("./routes/(app)/custom-field/(form)/(routes)/add/+page")>;
          $$route?: undefined;
          children?: undefined;
        },
        {
          path: "/contact/:id/edit/";
          id: "/contact/(form)/(routes)/:id/edit/";
          page: true;
          $component: FileRouteLazyRef<typeof import("./routes/(app)/contact/(form)/(routes)/[id]/edit/+page")>;
          $$route?: undefined;
          children?: undefined;
        },
        {
          path: "/contact-group/add/";
          id: "/contact-group/(form)/(routes)/add/";
          page: true;
          $component: FileRouteLazyRef<typeof import("./routes/(app)/contact-group/(form)/(routes)/add/+page")>;
          $$route?: undefined;
          children?: undefined;
        },
        {
          path: "/custom-field/:id/edit/";
          id: "/custom-field/(form)/(routes)/:id/edit/";
          page: true;
          $component: FileRouteLazyRef<typeof import("./routes/(app)/custom-field/(form)/(routes)/[id]/edit/+page")>;
          $$route?: undefined;
          children?: undefined;
        },
        {
          path: "/contact-group/:id/edit/";
          id: "/contact-group/(form)/(routes)/:id/edit/";
          page: true;
          $component: FileRouteLazyRef<typeof import("./routes/(app)/contact-group/(form)/(routes)/[id]/edit/+page")>;
          $$route?: undefined;
          children?: undefined;
        },
        {
          path: "/phone/10dlc/campaign/add/";
          id: "/phone/10dlc/campaign/(form)/(routes)/add/";
          page: true;
          $component: FileRouteLazyRef<typeof import("./routes/(app)/phone/10dlc/campaign/(form)/(routes)/add/+page")>;
          $$route?: undefined;
          children?: undefined;
        }
      ];
    },
    {
      path: "/*path";
      id: "/*path";
      page: true;
      $component: FileRouteLazyRef<typeof import("./routes/[...path]/+page")>;
      $$route?: undefined;
      children?: undefined;
    },
    {
      path: "/sign-in/";
      id: "/sign-in/";
      page: true;
      $component: FileRouteLazyRef<typeof import("./routes/sign-in/+page")>;
      $$route?: undefined;
      children?: undefined;
    },
    {
      path: "/sign-up/";
      id: "/sign-up/";
      page: true;
      $component: FileRouteLazyRef<typeof import("./routes/sign-up/+page")>;
      $$route?: undefined;
      children?: undefined;
    },
    {
      path: "/trial-expired/";
      id: "/trial-expired/";
      page: true;
      $component: FileRouteLazyRef<typeof import("./routes/trial-expired/+page")>;
      $$route?: undefined;
      children?: undefined;
    },
    {
      path: "/account-closed/";
      id: "/account-closed/";
      page: true;
      $component: FileRouteLazyRef<typeof import("./routes/account-closed/+page")>;
      $$route?: undefined;
      children?: undefined;
    },
    {
      path: "/reset-password/";
      id: "/reset-password/";
      page: true;
      $component: FileRouteLazyRef<typeof import("./routes/reset-password/+page")>;
      $$route?: undefined;
      children?: undefined;
    },
    {
      path: "/account-suspended/";
      id: "/account-suspended/";
      page: true;
      $component: FileRouteLazyRef<typeof import("./routes/account-suspended/+page")>;
      $$route?: undefined;
      children?: undefined;
    },
    {
      path: "/account-unavailable/";
      id: "/account-unavailable/";
      page: true;
      $component: FileRouteLazyRef<typeof import("./routes/account-unavailable/+page")>;
      $$route?: undefined;
      children?: undefined;
    }
  ];
}
