/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type {
  ContactCreateDto,
  ContactDto,
  ContactUpdateDto,
  ErrorResponseDto,
  GetUploadUrlParams,
  IdDto,
  PageContactDto,
  PageRequestContactFilterDtoContactSortDto,
  UploadUrlDto
} from '../index.schemas';


export type getContactByIdResponse200 = {
  data: ContactDto
  status: 200
}

export type getContactByIdResponse400 = {
  data: ErrorResponseDto
  status: 400
}

export type getContactByIdResponse401 = {
  data: ErrorResponseDto
  status: 401
}

export type getContactByIdResponse404 = {
  data: ErrorResponseDto
  status: 404
}

export type getContactByIdResponse500 = {
  data: ErrorResponseDto
  status: 500
}

export type getContactByIdResponseSuccess = (getContactByIdResponse200) & {
  headers: Headers;
};
export type getContactByIdResponseError = (getContactByIdResponse400 | getContactByIdResponse401 | getContactByIdResponse404 | getContactByIdResponse500) & {
  headers: Headers;
};

export type getContactByIdResponse = (getContactByIdResponseSuccess | getContactByIdResponseError)

export const getGetContactByIdUrl = (id: string,) => {


  

  return `/contact/contact/${id}`
}

export const getContactById = async (id: string, options?: RequestInit): Promise<getContactByIdResponse> => {
  
  const res = await fetch(getGetContactByIdUrl(id),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getContactByIdResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getContactByIdResponse
}
  

export type updateContactResponse200 = {
  data: void
  status: 200
}

export type updateContactResponse400 = {
  data: ErrorResponseDto
  status: 400
}

export type updateContactResponse401 = {
  data: ErrorResponseDto
  status: 401
}

export type updateContactResponse404 = {
  data: ErrorResponseDto
  status: 404
}

export type updateContactResponse500 = {
  data: ErrorResponseDto
  status: 500
}

export type updateContactResponseSuccess = (updateContactResponse200) & {
  headers: Headers;
};
export type updateContactResponseError = (updateContactResponse400 | updateContactResponse401 | updateContactResponse404 | updateContactResponse500) & {
  headers: Headers;
};

export type updateContactResponse = (updateContactResponseSuccess | updateContactResponseError)

export const getUpdateContactUrl = (id: string,) => {


  

  return `/contact/contact/${id}`
}

export const updateContact = async (id: string,
    contactUpdateDto: ContactUpdateDto, options?: RequestInit): Promise<updateContactResponse> => {
  
  const res = await fetch(getUpdateContactUrl(id),
  {      
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      contactUpdateDto,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: updateContactResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as updateContactResponse
}
  

export type deleteContactResponse200 = {
  data: void
  status: 200
}

export type deleteContactResponse400 = {
  data: ErrorResponseDto
  status: 400
}

export type deleteContactResponse401 = {
  data: ErrorResponseDto
  status: 401
}

export type deleteContactResponse404 = {
  data: ErrorResponseDto
  status: 404
}

export type deleteContactResponse500 = {
  data: ErrorResponseDto
  status: 500
}

export type deleteContactResponseSuccess = (deleteContactResponse200) & {
  headers: Headers;
};
export type deleteContactResponseError = (deleteContactResponse400 | deleteContactResponse401 | deleteContactResponse404 | deleteContactResponse500) & {
  headers: Headers;
};

export type deleteContactResponse = (deleteContactResponseSuccess | deleteContactResponseError)

export const getDeleteContactUrl = (id: string,) => {


  

  return `/contact/contact/${id}`
}

export const deleteContact = async (id: string, options?: RequestInit): Promise<deleteContactResponse> => {
  
  const res = await fetch(getDeleteContactUrl(id),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: deleteContactResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as deleteContactResponse
}
  

export type createContactResponse200 = {
  data: IdDto
  status: 200
}

export type createContactResponse400 = {
  data: ErrorResponseDto
  status: 400
}

export type createContactResponse401 = {
  data: ErrorResponseDto
  status: 401
}

export type createContactResponse404 = {
  data: ErrorResponseDto
  status: 404
}

export type createContactResponse500 = {
  data: ErrorResponseDto
  status: 500
}

export type createContactResponseSuccess = (createContactResponse200) & {
  headers: Headers;
};
export type createContactResponseError = (createContactResponse400 | createContactResponse401 | createContactResponse404 | createContactResponse500) & {
  headers: Headers;
};

export type createContactResponse = (createContactResponseSuccess | createContactResponseError)

export const getCreateContactUrl = () => {


  

  return `/contact/contact`
}

export const createContact = async (contactCreateDto: ContactCreateDto, options?: RequestInit): Promise<createContactResponse> => {
  
  const res = await fetch(getCreateContactUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      contactCreateDto,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: createContactResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as createContactResponse
}
  

export type getContactsPageResponse200 = {
  data: PageContactDto
  status: 200
}

export type getContactsPageResponse400 = {
  data: ErrorResponseDto
  status: 400
}

export type getContactsPageResponse401 = {
  data: ErrorResponseDto
  status: 401
}

export type getContactsPageResponse404 = {
  data: ErrorResponseDto
  status: 404
}

export type getContactsPageResponse500 = {
  data: ErrorResponseDto
  status: 500
}

export type getContactsPageResponseSuccess = (getContactsPageResponse200) & {
  headers: Headers;
};
export type getContactsPageResponseError = (getContactsPageResponse400 | getContactsPageResponse401 | getContactsPageResponse404 | getContactsPageResponse500) & {
  headers: Headers;
};

export type getContactsPageResponse = (getContactsPageResponseSuccess | getContactsPageResponseError)

export const getGetContactsPageUrl = () => {


  

  return `/contact/contact/fetch`
}

export const getContactsPage = async (pageRequestContactFilterDtoContactSortDto: PageRequestContactFilterDtoContactSortDto, options?: RequestInit): Promise<getContactsPageResponse> => {
  
  const res = await fetch(getGetContactsPageUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      pageRequestContactFilterDtoContactSortDto,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getContactsPageResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getContactsPageResponse
}
  

export type getUploadUrlResponse200 = {
  data: UploadUrlDto
  status: 200
}

export type getUploadUrlResponse400 = {
  data: ErrorResponseDto
  status: 400
}

export type getUploadUrlResponse401 = {
  data: ErrorResponseDto
  status: 401
}

export type getUploadUrlResponse404 = {
  data: ErrorResponseDto
  status: 404
}

export type getUploadUrlResponse500 = {
  data: ErrorResponseDto
  status: 500
}

export type getUploadUrlResponseSuccess = (getUploadUrlResponse200) & {
  headers: Headers;
};
export type getUploadUrlResponseError = (getUploadUrlResponse400 | getUploadUrlResponse401 | getUploadUrlResponse404 | getUploadUrlResponse500) & {
  headers: Headers;
};

export type getUploadUrlResponse = (getUploadUrlResponseSuccess | getUploadUrlResponseError)

export const getGetUploadUrlUrl = (params: GetUploadUrlParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/contact/contact/upload-url?${stringifiedParams}` : `/contact/contact/upload-url`
}

export const getUploadUrl = async (params: GetUploadUrlParams, options?: RequestInit): Promise<getUploadUrlResponse> => {
  
  const res = await fetch(getGetUploadUrlUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getUploadUrlResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getUploadUrlResponse
}
  

