/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type {
  ContactCreateDto,
  ContactDto,
  ContactUpdateDto,
  ErrorResponseDto,
  GetUploadUrlParams,
  IdDto,
  PageContactDto,
  PageRequestContactFilterDtoContactSortDto,
  UploadUrlDto,
} from "../index.schemas";

export type GetContactByIdResponse200 = {
  data: ContactDto;
  status: 200;
};

export type GetContactByIdResponse400 = {
  data: ErrorResponseDto;
  status: 400;
};

export type GetContactByIdResponse401 = {
  data: ErrorResponseDto;
  status: 401;
};

export type GetContactByIdResponse404 = {
  data: ErrorResponseDto;
  status: 404;
};

export type GetContactByIdResponse500 = {
  data: ErrorResponseDto;
  status: 500;
};

export type GetContactByIdResponseSuccess = GetContactByIdResponse200 & {
  headers: Headers;
};
export type GetContactByIdResponseError = (
  | GetContactByIdResponse400
  | GetContactByIdResponse401
  | GetContactByIdResponse404
  | GetContactByIdResponse500
) & {
  headers: Headers;
};

export type GetContactByIdResponse = GetContactByIdResponseSuccess | GetContactByIdResponseError;

export const getGetContactByIdUrl = (id: string) => {
  return `/contact/contact/${id}`;
};

export const getContactById = async (id: string, options?: RequestInit): Promise<GetContactByIdResponse> => {
  const res = await fetch(getGetContactByIdUrl(id), {
    ...options,
    method: "GET",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: GetContactByIdResponse["data"] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as GetContactByIdResponse;
};

export type UpdateContactResponse200 = {
  data: void;
  status: 200;
};

export type UpdateContactResponse400 = {
  data: ErrorResponseDto;
  status: 400;
};

export type UpdateContactResponse401 = {
  data: ErrorResponseDto;
  status: 401;
};

export type UpdateContactResponse404 = {
  data: ErrorResponseDto;
  status: 404;
};

export type UpdateContactResponse500 = {
  data: ErrorResponseDto;
  status: 500;
};

export type UpdateContactResponseSuccess = UpdateContactResponse200 & {
  headers: Headers;
};
export type UpdateContactResponseError = (
  | UpdateContactResponse400
  | UpdateContactResponse401
  | UpdateContactResponse404
  | UpdateContactResponse500
) & {
  headers: Headers;
};

export type UpdateContactResponse = UpdateContactResponseSuccess | UpdateContactResponseError;

export const getUpdateContactUrl = (id: string) => {
  return `/contact/contact/${id}`;
};

export const updateContact = async (
  id: string,
  contactUpdateDto: ContactUpdateDto,
  options?: RequestInit,
): Promise<UpdateContactResponse> => {
  const res = await fetch(getUpdateContactUrl(id), {
    ...options,
    method: "PUT",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(contactUpdateDto),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: UpdateContactResponse["data"] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as UpdateContactResponse;
};

export type DeleteContactResponse200 = {
  data: void;
  status: 200;
};

export type DeleteContactResponse400 = {
  data: ErrorResponseDto;
  status: 400;
};

export type DeleteContactResponse401 = {
  data: ErrorResponseDto;
  status: 401;
};

export type DeleteContactResponse404 = {
  data: ErrorResponseDto;
  status: 404;
};

export type DeleteContactResponse500 = {
  data: ErrorResponseDto;
  status: 500;
};

export type DeleteContactResponseSuccess = DeleteContactResponse200 & {
  headers: Headers;
};
export type DeleteContactResponseError = (
  | DeleteContactResponse400
  | DeleteContactResponse401
  | DeleteContactResponse404
  | DeleteContactResponse500
) & {
  headers: Headers;
};

export type DeleteContactResponse = DeleteContactResponseSuccess | DeleteContactResponseError;

export const getDeleteContactUrl = (id: string) => {
  return `/contact/contact/${id}`;
};

export const deleteContact = async (id: string, options?: RequestInit): Promise<DeleteContactResponse> => {
  const res = await fetch(getDeleteContactUrl(id), {
    ...options,
    method: "DELETE",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: DeleteContactResponse["data"] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as DeleteContactResponse;
};

export type CreateContactResponse200 = {
  data: IdDto;
  status: 200;
};

export type CreateContactResponse400 = {
  data: ErrorResponseDto;
  status: 400;
};

export type CreateContactResponse401 = {
  data: ErrorResponseDto;
  status: 401;
};

export type CreateContactResponse404 = {
  data: ErrorResponseDto;
  status: 404;
};

export type CreateContactResponse500 = {
  data: ErrorResponseDto;
  status: 500;
};

export type CreateContactResponseSuccess = CreateContactResponse200 & {
  headers: Headers;
};
export type CreateContactResponseError = (
  | CreateContactResponse400
  | CreateContactResponse401
  | CreateContactResponse404
  | CreateContactResponse500
) & {
  headers: Headers;
};

export type CreateContactResponse = CreateContactResponseSuccess | CreateContactResponseError;

export const getCreateContactUrl = () => {
  return `/contact/contact`;
};

export const createContact = async (
  contactCreateDto: ContactCreateDto,
  options?: RequestInit,
): Promise<CreateContactResponse> => {
  const res = await fetch(getCreateContactUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(contactCreateDto),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: CreateContactResponse["data"] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as CreateContactResponse;
};

export type GetContactsPageResponse200 = {
  data: PageContactDto;
  status: 200;
};

export type GetContactsPageResponse400 = {
  data: ErrorResponseDto;
  status: 400;
};

export type GetContactsPageResponse401 = {
  data: ErrorResponseDto;
  status: 401;
};

export type GetContactsPageResponse404 = {
  data: ErrorResponseDto;
  status: 404;
};

export type GetContactsPageResponse500 = {
  data: ErrorResponseDto;
  status: 500;
};

export type GetContactsPageResponseSuccess = GetContactsPageResponse200 & {
  headers: Headers;
};
export type GetContactsPageResponseError = (
  | GetContactsPageResponse400
  | GetContactsPageResponse401
  | GetContactsPageResponse404
  | GetContactsPageResponse500
) & {
  headers: Headers;
};

export type GetContactsPageResponse = GetContactsPageResponseSuccess | GetContactsPageResponseError;

export const getGetContactsPageUrl = () => {
  return `/contact/contact/fetch`;
};

export const getContactsPage = async (
  pageRequestContactFilterDtoContactSortDto: PageRequestContactFilterDtoContactSortDto,
  options?: RequestInit,
): Promise<GetContactsPageResponse> => {
  const res = await fetch(getGetContactsPageUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(pageRequestContactFilterDtoContactSortDto),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: GetContactsPageResponse["data"] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as GetContactsPageResponse;
};

export type GetUploadUrlResponse200 = {
  data: UploadUrlDto;
  status: 200;
};

export type GetUploadUrlResponse400 = {
  data: ErrorResponseDto;
  status: 400;
};

export type GetUploadUrlResponse401 = {
  data: ErrorResponseDto;
  status: 401;
};

export type GetUploadUrlResponse404 = {
  data: ErrorResponseDto;
  status: 404;
};

export type GetUploadUrlResponse500 = {
  data: ErrorResponseDto;
  status: 500;
};

export type GetUploadUrlResponseSuccess = GetUploadUrlResponse200 & {
  headers: Headers;
};
export type GetUploadUrlResponseError = (
  | GetUploadUrlResponse400
  | GetUploadUrlResponse401
  | GetUploadUrlResponse404
  | GetUploadUrlResponse500
) & {
  headers: Headers;
};

export type GetUploadUrlResponse = GetUploadUrlResponseSuccess | GetUploadUrlResponseError;

export const getGetUploadUrlUrl = (params: GetUploadUrlParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/contact/contact/upload-url?${stringifiedParams}`
    : `/contact/contact/upload-url`;
};

export const getUploadUrl = async (
  params: GetUploadUrlParams,
  options?: RequestInit,
): Promise<GetUploadUrlResponse> => {
  const res = await fetch(getGetUploadUrlUrl(params), {
    ...options,
    method: "GET",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: GetUploadUrlResponse["data"] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as GetUploadUrlResponse;
};
