/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * utoipa-axum
 * Utoipa's axum bindings for seamless integration for the two
 * OpenAPI spec version: 0.2.0
 */
import type {
  ContactCreateDto,
  ContactDto,
  ContactExportDto,
  ContactFilterDto,
  ContactImportDto,
  ContactImportResultDto,
  ContactUpdateDto,
  ErrorResponse,
  GetContactUploadUrlParams,
  IdDto,
  PageContactDto,
  PageRequestContactFilterDtoContactSortDto,
  Ulid,
  UploadUrlDto,
} from "../index.schemas";

export type CreateContactResponse200 = {
  data: IdDto;
  status: 200;
};

export type CreateContactResponse400 = {
  data: ErrorResponse;
  status: 400;
};

export type CreateContactResponse500 = {
  data: ErrorResponse;
  status: 500;
};

export type CreateContactResponseSuccess = CreateContactResponse200 & {
  headers: Headers;
};
export type CreateContactResponseError = (CreateContactResponse400 | CreateContactResponse500) & {
  headers: Headers;
};

export type CreateContactResponse = CreateContactResponseSuccess | CreateContactResponseError;

export const getCreateContactUrl = () => {
  return `/contact/contact`;
};

export const createContact = async (
  contactCreateDto: ContactCreateDto,
  options?: RequestInit,
): Promise<CreateContactResponse> => {
  const res = await fetch(getCreateContactUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(contactCreateDto),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: CreateContactResponse["data"] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as CreateContactResponse;
};

export type CountContactsResponse200 = {
  data: number;
  status: 200;
};

export type CountContactsResponse400 = {
  data: ErrorResponse;
  status: 400;
};

export type CountContactsResponse500 = {
  data: ErrorResponse;
  status: 500;
};

export type CountContactsResponseSuccess = CountContactsResponse200 & {
  headers: Headers;
};
export type CountContactsResponseError = (CountContactsResponse400 | CountContactsResponse500) & {
  headers: Headers;
};

export type CountContactsResponse = CountContactsResponseSuccess | CountContactsResponseError;

export const getCountContactsUrl = () => {
  return `/contact/contact/count`;
};

export const countContacts = async (
  contactFilterDto: ContactFilterDto,
  options?: RequestInit,
): Promise<CountContactsResponse> => {
  const res = await fetch(getCountContactsUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(contactFilterDto),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: CountContactsResponse["data"] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as CountContactsResponse;
};

export type ExportContactsResponse200 = {
  data: Blob;
  status: 200;
};

export type ExportContactsResponse400 = {
  data: ErrorResponse;
  status: 400;
};

export type ExportContactsResponse500 = {
  data: ErrorResponse;
  status: 500;
};

export type ExportContactsResponseSuccess = ExportContactsResponse200 & {
  headers: Headers;
};
export type ExportContactsResponseError = (ExportContactsResponse400 | ExportContactsResponse500) & {
  headers: Headers;
};

export type ExportContactsResponse = ExportContactsResponseSuccess | ExportContactsResponseError;

export const getExportContactsUrl = () => {
  return `/contact/contact/export`;
};

export const exportContacts = async (
  contactExportDto: ContactExportDto,
  options?: RequestInit,
): Promise<ExportContactsResponse> => {
  const res = await fetch(getExportContactsUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(contactExportDto),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: ExportContactsResponse["data"] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as ExportContactsResponse;
};

export type FetchContactsResponse200 = {
  data: PageContactDto;
  status: 200;
};

export type FetchContactsResponse400 = {
  data: ErrorResponse;
  status: 400;
};

export type FetchContactsResponse500 = {
  data: ErrorResponse;
  status: 500;
};

export type FetchContactsResponseSuccess = FetchContactsResponse200 & {
  headers: Headers;
};
export type FetchContactsResponseError = (FetchContactsResponse400 | FetchContactsResponse500) & {
  headers: Headers;
};

export type FetchContactsResponse = FetchContactsResponseSuccess | FetchContactsResponseError;

export const getFetchContactsUrl = () => {
  return `/contact/contact/fetch`;
};

export const fetchContacts = async (
  pageRequestContactFilterDtoContactSortDto: PageRequestContactFilterDtoContactSortDto,
  options?: RequestInit,
): Promise<FetchContactsResponse> => {
  const res = await fetch(getFetchContactsUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(pageRequestContactFilterDtoContactSortDto),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: FetchContactsResponse["data"] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as FetchContactsResponse;
};

export type ImportContactsResponse200 = {
  data: ContactImportResultDto;
  status: 200;
};

export type ImportContactsResponse400 = {
  data: ErrorResponse;
  status: 400;
};

export type ImportContactsResponse500 = {
  data: ErrorResponse;
  status: 500;
};

export type ImportContactsResponseSuccess = ImportContactsResponse200 & {
  headers: Headers;
};
export type ImportContactsResponseError = (ImportContactsResponse400 | ImportContactsResponse500) & {
  headers: Headers;
};

export type ImportContactsResponse = ImportContactsResponseSuccess | ImportContactsResponseError;

export const getImportContactsUrl = () => {
  return `/contact/contact/import`;
};

export const importContacts = async (
  contactImportDto: ContactImportDto,
  options?: RequestInit,
): Promise<ImportContactsResponse> => {
  const res = await fetch(getImportContactsUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(contactImportDto),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: ImportContactsResponse["data"] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as ImportContactsResponse;
};

export type GetContactUploadUrlResponse200 = {
  data: UploadUrlDto;
  status: 200;
};

export type GetContactUploadUrlResponse400 = {
  data: ErrorResponse;
  status: 400;
};

export type GetContactUploadUrlResponse500 = {
  data: ErrorResponse;
  status: 500;
};

export type GetContactUploadUrlResponse501 = {
  data: ErrorResponse;
  status: 501;
};

export type GetContactUploadUrlResponseSuccess = GetContactUploadUrlResponse200 & {
  headers: Headers;
};
export type GetContactUploadUrlResponseError = (
  | GetContactUploadUrlResponse400
  | GetContactUploadUrlResponse500
  | GetContactUploadUrlResponse501
) & {
  headers: Headers;
};

export type GetContactUploadUrlResponse = GetContactUploadUrlResponseSuccess | GetContactUploadUrlResponseError;

export const getGetContactUploadUrlUrl = (params: GetContactUploadUrlParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/contact/contact/upload-url?${stringifiedParams}`
    : `/contact/contact/upload-url`;
};

export const getContactUploadUrl = async (
  params: GetContactUploadUrlParams,
  options?: RequestInit,
): Promise<GetContactUploadUrlResponse> => {
  const res = await fetch(getGetContactUploadUrlUrl(params), {
    ...options,
    method: "GET",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: GetContactUploadUrlResponse["data"] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as GetContactUploadUrlResponse;
};

export type GetContactResponse200 = {
  data: ContactDto;
  status: 200;
};

export type GetContactResponse404 = {
  data: ErrorResponse;
  status: 404;
};

export type GetContactResponse500 = {
  data: ErrorResponse;
  status: 500;
};

export type GetContactResponseSuccess = GetContactResponse200 & {
  headers: Headers;
};
export type GetContactResponseError = (GetContactResponse404 | GetContactResponse500) & {
  headers: Headers;
};

export type GetContactResponse = GetContactResponseSuccess | GetContactResponseError;

export const getGetContactUrl = (id: Ulid) => {
  return `/contact/contact/${id}`;
};

export const getContact = async (id: Ulid, options?: RequestInit): Promise<GetContactResponse> => {
  const res = await fetch(getGetContactUrl(id), {
    ...options,
    method: "GET",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: GetContactResponse["data"] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as GetContactResponse;
};

export type UpdateContactResponse200 = {
  data: void;
  status: 200;
};

export type UpdateContactResponse400 = {
  data: ErrorResponse;
  status: 400;
};

export type UpdateContactResponse404 = {
  data: ErrorResponse;
  status: 404;
};

export type UpdateContactResponse500 = {
  data: ErrorResponse;
  status: 500;
};

export type UpdateContactResponseSuccess = UpdateContactResponse200 & {
  headers: Headers;
};
export type UpdateContactResponseError = (
  | UpdateContactResponse400
  | UpdateContactResponse404
  | UpdateContactResponse500
) & {
  headers: Headers;
};

export type UpdateContactResponse = UpdateContactResponseSuccess | UpdateContactResponseError;

export const getUpdateContactUrl = (id: Ulid) => {
  return `/contact/contact/${id}`;
};

export const updateContact = async (
  id: Ulid,
  contactUpdateDto: ContactUpdateDto,
  options?: RequestInit,
): Promise<UpdateContactResponse> => {
  const res = await fetch(getUpdateContactUrl(id), {
    ...options,
    method: "PUT",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(contactUpdateDto),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: UpdateContactResponse["data"] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as UpdateContactResponse;
};

export type DeleteContactResponse200 = {
  data: void;
  status: 200;
};

export type DeleteContactResponse404 = {
  data: ErrorResponse;
  status: 404;
};

export type DeleteContactResponse500 = {
  data: ErrorResponse;
  status: 500;
};

export type DeleteContactResponseSuccess = DeleteContactResponse200 & {
  headers: Headers;
};
export type DeleteContactResponseError = (DeleteContactResponse404 | DeleteContactResponse500) & {
  headers: Headers;
};

export type DeleteContactResponse = DeleteContactResponseSuccess | DeleteContactResponseError;

export const getDeleteContactUrl = (id: Ulid) => {
  return `/contact/contact/${id}`;
};

export const deleteContact = async (id: Ulid, options?: RequestInit): Promise<DeleteContactResponse> => {
  const res = await fetch(getDeleteContactUrl(id), {
    ...options,
    method: "DELETE",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: DeleteContactResponse["data"] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as DeleteContactResponse;
};
