query BusinessProfileEdit {
  businessProfile {
    id
    legalCompanyName
    displayName
    entityType
    registrationCountry
    hasTaxId
    businessRegistrationType
    taxIdIssuingCountry
    taxIdLastFour
    industry
    address {
      street
      city
      region
      postalCode
      country
    }
    website
    businessPhone
    businessEmail
    authorizedContact {
      firstName
      lastName
      title
      phone
      email
    }
    privacyPolicyUrl
    termsOfServiceUrl
  }
}
